// Records Export — the 00-START-HERE.pdf audit cover (Phase 4).
//
// Rendered from the finished manifest so the cover and the ZIP agree exactly:
// the period, per-module record/file counts (gaps flagged), generated-by/when,
// and the SHA-256 of every file. First thing a reviewer opens.
import autoTable from 'jspdf-autotable'
import {
  createPdf,
  drawBaseHeader,
  drawReportTitle,
  drawStatBox,
  drawFooter,
  tableStyles,
} from '@/lib/pdf-utils'
import { pdfToExportFile, type ExportFile } from './export-file'
import type { ExportManifest } from './export-manifest'

function periodLabel(p: ExportManifest['period']): string {
  if (p.kind === 'all_time') return 'All time'
  return `${p.from ?? '…'} → ${p.to ?? '…'}`
}

/** Build the audit-cover PDF as an ExportFile at `00-START-HERE.pdf`. */
export function buildCoverFile(m: ExportManifest): ExportFile {
  const ctx = createPdf({ orientation: 'portrait' })
  const { doc, margin, contentWidth } = ctx
  let y = margin

  y = drawBaseHeader(ctx, y, { baseName: m.base.name, baseIcao: m.base.icao, sectionLabel: 'RECORDS DISPOSITION EXPORT' })
  y = drawReportTitle(ctx, y, { title: 'START HERE', subtitle: periodLabel(m.period) })
  y = drawStatBox(ctx, y, [
    { label: 'Modules', value: String(m.modules.length) },
    { label: 'Files', value: String(m.files.length) },
    { label: 'Output', value: m.outputMode },
    { label: 'Generated', value: m.generatedAt.slice(0, 10) },
  ])

  // ── Purpose blurb ──
  doc.setFontSize(9)
  doc.setTextColor(70)
  const blurb = doc.splitTextToSize(
    'Standalone, reviewable records produced from Glidepath for Air Force records disposition '
      + 'and continuity. Each record series is a separate document so it can be filed per the AF '
      + 'Records Disposition Schedule (RDS, in AFRIMS). These files open in any standard tool — no '
      + 'server, internet, or Glidepath account required. AMTR training records export from the AMTR module.',
    contentWidth,
  )
  doc.text(blurb, margin, y + 2)
  y += blurb.length * 4 + 6
  if (m.generatedBy) {
    doc.setFontSize(8)
    doc.setTextColor(110)
    doc.text(`Generated by ${m.generatedBy} at ${m.generatedAt}`, margin, y)
    y += 6
  }

  // ── Module summary table ──
  autoTable(doc, {
    ...tableStyles(ctx),
    startY: y,
    head: [['Module', 'Records', 'Files', 'Note']],
    body: m.modules.map((mod) => [
      mod.label,
      String(mod.records),
      String(mod.files),
      m.gaps.includes(mod.key) ? 'No records in this window' : '',
    ]),
    columnStyles: {
      1: { halign: 'right', cellWidth: 22 },
      2: { halign: 'right', cellWidth: 18 },
    },
    didDrawPage: () => drawFooter(ctx),
  })
  // @ts-expect-error autotable augments doc at runtime
  y = (doc.lastAutoTable?.finalY ?? y) + 8

  // ── Integrity table (SHA-256 per file) ──
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(20)
  doc.text('Integrity — SHA-256', margin, y)
  y += 2
  doc.setFont('helvetica', 'normal')
  autoTable(doc, {
    ...tableStyles(ctx),
    startY: y + 2,
    head: [['File', 'Bytes', 'SHA-256']],
    body: m.files.map((f) => [f.path, String(f.bytes), f.sha256]),
    styles: { fontSize: 6, cellPadding: 1.2 },
    columnStyles: {
      1: { halign: 'right', cellWidth: 18 },
      2: { cellWidth: 92, font: 'courier', fontSize: 5.5 },
    },
    didDrawPage: () => drawFooter(ctx),
  })

  return pdfToExportFile(doc, '00-START-HERE.pdf')
}
