'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, AlertTriangle, Download, Loader2 } from 'lucide-react'
import { fetchOpenDiscrepanciesData, formatDiscrepancyType, type OpenDiscrepanciesData } from '@/lib/reports/open-discrepancies-data'
import { generateOpenDiscrepanciesPdf } from '@/lib/reports/open-discrepancies-pdf'
import { getInspectorName } from '@/lib/supabase/inspections'
import { useInstallation } from '@/lib/installation-context'

export default function OpenDiscrepanciesPage() {
  const router = useRouter()
  const { installationId, currentInstallation } = useInstallation()

  const [loading, setLoading] = useState(true)
  const [data, setData] = useState<OpenDiscrepanciesData | null>(null)
  const [generatorName, setGeneratorName] = useState<string>('Unknown')
  const [exporting, setExporting] = useState(false)

  useEffect(() => {
    let cancelled = false
    async function generate() {
      const [reportData, inspector] = await Promise.all([
        fetchOpenDiscrepanciesData(true, installationId),
        getInspectorName(),
      ])
      if (cancelled) return
      setData(reportData)
      setGeneratorName(inspector.name || 'Unknown')
      setLoading(false)
    }
    generate()
    return () => { cancelled = true }
  }, [])

  const handleExport = async () => {
    if (!data) return
    setExporting(true)

    generateOpenDiscrepanciesPdf(data, {
      generatedBy: generatorName,
      baseName: currentInstallation?.name,
      baseIcao: currentInstallation?.icao,
    })

    setExporting(false)
  }

  // ── Loading View ──
  if (loading) {
    return (
      <div style={{ padding: 16, paddingBottom: 100 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
          <button onClick={() => router.push('/reports')} style={{ background: 'none', border: 'none', color: 'var(--color-text-2)', cursor: 'pointer', padding: 4 }}>
            <ArrowLeft size={20} />
          </button>
          <div style={{ fontSize: 16, fontWeight: 800 }}>Discrepancy Report</div>
        </div>
        <div className="card" style={{ textAlign: 'center', padding: '40px 20px' }}>
          <Loader2 size={32} color="var(--color-warning)" style={{ animation: 'spin 1s linear infinite' }} />
          <div style={{ fontSize: 13, color: 'var(--color-text-2)', marginTop: 12 }}>Fetching open discrepancy data...</div>
          <style>{`@keyframes spin { to { transform: rotate(360deg) } }`}</style>
        </div>
      </div>
    )
  }

  // ── Preview View ──
  if (!data) return null

  const { summary } = data
  const areaEntries = Object.entries(summary.byArea).sort((a, b) => b[1] - a[1])
  const typeEntries = Object.entries(summary.byType).sort((a, b) => b[1] - a[1])

  return (
    <div style={{ padding: 16, paddingBottom: 100 }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
        <button onClick={() => router.push('/reports')} style={{ background: 'none', border: 'none', color: 'var(--color-text-2)', cursor: 'pointer', padding: 4 }}>
          <ArrowLeft size={20} />
        </button>
        <div>
          <div style={{ fontSize: 16, fontWeight: 800 }}>Discrepancy Report</div>
          <div style={{ fontSize: 11, color: 'var(--color-text-3)' }}>As of {new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</div>
        </div>
      </div>

      {/* Total Count */}
      <div className="card" style={{ textAlign: 'center', padding: '16px 20px', marginBottom: 12 }}>
        <AlertTriangle size={28} color="var(--color-warning)" style={{ marginBottom: 8 }} />
        <div style={{ fontSize: 28, fontWeight: 800, color: 'var(--color-text-1)' }}>{summary.total}</div>
        <div style={{ fontSize: 12, color: 'var(--color-text-3)' }}>Open Discrepancies</div>
        {summary.agingOver30 > 0 && (
          <div style={{ fontSize: 11, color: 'var(--color-danger)', marginTop: 4, fontWeight: 600 }}>
            {summary.agingOver30} open &gt; 30 days
          </div>
        )}
        <div style={{ fontSize: 11, color: 'var(--color-text-3)', marginTop: 4 }}>Generated by {generatorName}</div>
      </div>

      {/* By Area — KPI badges */}
      <div className="card" style={{ padding: 14, marginBottom: 8 }}>
        <div style={{ fontSize: 10, color: 'var(--color-text-3)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 10 }}>
          By Area
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {areaEntries.map(([area, count]) => (
            <div key={area} style={{
              display: 'flex', flexDirection: 'column', alignItems: 'center',
              padding: '8px 14px', borderRadius: 10,
              background: 'rgba(56,189,248,0.08)', border: '1px solid rgba(56,189,248,0.15)',
              minWidth: 64,
            }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--color-accent)' }}>{count}</div>
              <div style={{ fontSize: 9, color: 'var(--color-text-2)', fontWeight: 600, textAlign: 'center', marginTop: 2 }}>{area}</div>
            </div>
          ))}
        </div>
      </div>

      {/* By Type — KPI badges */}
      <div className="card" style={{ padding: 14, marginBottom: 14 }}>
        <div style={{ fontSize: 10, color: 'var(--color-text-3)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 10 }}>
          By Type
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
          {typeEntries.map(([type, count]) => (
            <div key={type} style={{
              display: 'flex', flexDirection: 'column', alignItems: 'center',
              padding: '8px 14px', borderRadius: 10,
              background: 'rgba(251,191,36,0.08)', border: '1px solid rgba(251,191,36,0.15)',
              minWidth: 64,
            }}>
              <div style={{ fontSize: 20, fontWeight: 800, color: 'var(--color-warning)' }}>{count}</div>
              <div style={{ fontSize: 9, color: 'var(--color-text-2)', fontWeight: 600, textAlign: 'center', marginTop: 2 }}>{formatDiscrepancyType(type)}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Export Button */}
      <button
        onClick={handleExport}
        disabled={exporting}
        style={{
          width: '100%', padding: '14px 0', borderRadius: 10,
          border: '1px solid rgba(34,197,94,0.4)',
          background: 'rgba(34,197,94,0.1)',
          color: '#22C55E', fontSize: 15, fontWeight: 700,
          cursor: exporting ? 'default' : 'pointer', fontFamily: 'inherit',
          opacity: exporting ? 0.7 : 1,
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
        }}
      >
        <Download size={18} />
        {exporting ? 'Generating PDF...' : 'Export PDF'}
      </button>
    </div>
  )
}
