// Static directory of all installations for dropdown selection.
// When a user selects one, it is created in the database on-demand.

export type BaseDirectoryEntry = { name: string; icao: string }

export const BASE_DIRECTORY: readonly BaseDirectoryEntry[] = [
  { name: 'Air Force Academy', icao: 'KAFF' },
  { name: 'Al Udeid Air Base', icao: 'OTBH' },
  { name: 'Altus Air Force Base', icao: 'KLTS' },
  { name: 'Andersen Air Force Base', icao: 'PGUA' },
  { name: 'Arnold Air Force Base', icao: 'KTHA' },
  { name: 'Atlantic City ANG Base', icao: 'KACY' },
  { name: 'Aviano Air Base', icao: 'LIPA' },
  { name: 'Bangor ANG Base', icao: 'KBGR' },
  { name: 'Barksdale Air Force Base', icao: 'KBAD' },
  { name: 'Barnes ANG Base', icao: 'KBAF' },
  { name: 'Battle Creek ANG Base', icao: 'KBTL' },
  { name: 'Beale Air Force Base', icao: 'KBAB' },
  { name: 'Berry Field ANG Base (Nashville)', icao: 'KBNA' },
  { name: 'Birmingham ANG Base', icao: 'KBHM' },
  { name: 'Buckley Space Force Base', icao: 'KBKF' },
  { name: 'Burlington ANG Base', icao: 'KBTV' },
  { name: 'Camp Murray (Tacoma)', icao: 'KTCM' },
  { name: 'Cannon Air Force Base', icao: 'KCVS' },
  { name: 'Cape Canaveral Space Force Station', icao: 'KXMR' },
  { name: 'Cape Cod Space Force Station', icao: '' },
  { name: 'Cavalier Space Force Station', icao: '' },
  { name: 'Channel Islands ANG Station', icao: 'KNLC' },
  { name: 'Charlotte Douglas ANG Base', icao: 'KCLT' },
  { name: 'Cheyenne ANG Base', icao: 'KCYS' },
  { name: 'Cheyenne Mountain SFS', icao: '' },
  { name: 'Clear Space Force Station', icao: 'PACL' },
  { name: 'Columbus Air Force Base', icao: 'KCBM' },
  { name: 'Creech Air Force Base', icao: 'KINS' },
  { name: 'Davis-Monthan Air Force Base', icao: 'KDMA' },
  { name: 'Des Moines ANG Base', icao: 'KDSM' },
  { name: 'Dobbins Air Reserve Base', icao: 'KMGE' },
  { name: 'Dover Air Force Base', icao: 'KDOV' },
  { name: 'Duke Field (Eglin Auxiliary)', icao: 'KEGI' },
  { name: 'Duluth ANG Base', icao: 'KDLH' },
  { name: 'Dyess Air Force Base', icao: 'KDYS' },
  { name: 'Ebbing ANG Base (Fort Smith)', icao: 'KFSM' },
  { name: 'Edwards Air Force Base', icao: 'KEDW' },
  { name: 'Eglin Air Force Base', icao: 'KVPS' },
  { name: 'Eielson Air Force Base', icao: 'PAEI' },
  { name: 'Ellington Field ANG Base', icao: 'KEFD' },
  { name: 'Ellsworth Air Force Base', icao: 'KRCA' },
  { name: 'F.E. Warren Air Force Base', icao: 'KFEW' },
  { name: 'Fairchild Air Force Base', icao: 'KSKA' },
  { name: 'Forbes Field ANG Base (Topeka)', icao: 'KFOE' },
  { name: 'Fort Wayne ANG Base', icao: 'KFWA' },
  { name: 'Fresno ANG Base', icao: 'KFAT' },
  { name: 'Gabreski ANG Base (Westhampton)', icao: 'KFOK' },
  { name: 'General Mitchell ANG Base', icao: 'KMKE' },
  { name: 'Goodfellow Air Force Base', icao: 'KSJT' },
  { name: 'Gowen Field ANG Base (Boise)', icao: 'KBOI' },
  { name: 'Grand Forks Air Force Base', icao: 'KRDR' },
  { name: 'Great Falls ANG Base', icao: 'KGTF' },
  { name: 'Grissom Air Reserve Base', icao: 'KGUS' },
  { name: 'Hancock Field ANG Base (Syracuse)', icao: 'KSYR' },
  { name: 'Hanscom Air Force Base', icao: 'KBED' },
  { name: 'Harrisburg ANG Base', icao: 'KMDT' },
  { name: 'Hector ANG Base (Fargo)', icao: 'KFAR' },
  { name: 'Hill Air Force Base', icao: 'KHIF' },
  { name: 'Holloman Air Force Base', icao: 'KHMN' },
  { name: 'Homestead Air Reserve Base', icao: 'KHST' },
  { name: 'Horsham ANG Base', icao: 'KNXX' },
  { name: 'Hulman Field ANG Base', icao: 'KHUF' },
  { name: 'Hurlburt Field', icao: 'KHRT' },
  { name: 'Incirlik Air Base', icao: 'LTAG' },
  { name: 'Jacksonville ANG Base', icao: 'KJAX' },
  { name: 'JB McGuire-Dix-Lakehurst', icao: 'KWRI' },
  { name: 'JB San Antonio-Lackland', icao: 'KSKF' },
  { name: 'JB San Antonio-Randolph', icao: 'KRND' },
  { name: 'Joint Base Andrews', icao: 'KADW' },
  { name: 'Joint Base Elmendorf-Richardson', icao: 'PAED' },
  { name: 'Joint Base Langley-Eustis', icao: 'KLFI' },
  { name: 'Joint Base Lewis-McChord', icao: 'KTCM' },
  { name: 'Joint Base Pearl Harbor-Hickam', icao: 'PHIK' },
  { name: 'Joe Foss Field ANG Base', icao: 'KFSD' },
  { name: "Ka'ena Point Space Force Station", icao: '' },
  { name: 'Kadena Air Base', icao: 'RODN' },
  { name: 'Keesler Air Force Base', icao: 'KBIX' },
  { name: 'Kelly Field (JBSA-Lackland)', icao: 'KSKF' },
  { name: 'Key Field ANG Base (Meridian)', icao: 'KMEI' },
  { name: 'Kingsley Field ANG Base', icao: 'KLMT' },
  { name: 'Kirtland Air Force Base', icao: 'KABQ' },
  { name: 'Kunsan Air Base', icao: 'RKJK' },
  { name: 'Lajes Field (Azores)', icao: 'LPLA' },
  { name: 'Laughlin Air Force Base', icao: 'KDLF' },
  { name: 'Lincoln ANG Base', icao: 'KLNK' },
  { name: 'Little Rock Air Force Base', icao: 'KLRF' },
  { name: 'Los Angeles Air Force Base', icao: '' },
  { name: 'Louisville ANG Base', icao: 'KSDF' },
  { name: 'Luke Air Force Base', icao: 'KLUF' },
  { name: 'MacDill Air Force Base', icao: 'KMCF' },
  { name: 'Malmstrom Air Force Base', icao: 'KGFA' },
  { name: 'Mansfield Lahm ANG Base', icao: 'KMFD' },
  { name: 'March Air Reserve Base', icao: 'KRIV' },
  { name: 'Maxwell Air Force Base', icao: 'KMXF' },
  { name: 'McConnell Air Force Base', icao: 'KIAB' },
  { name: 'McEntire ANG Base', icao: 'KMMT' },
  { name: 'McGhee Tyson ANG Base', icao: 'KTYS' },
  { name: 'McLaughlin ANG Base (Charleston)', icao: 'KCHS' },
  { name: 'Memphis ANG Base', icao: 'KNQA' },
  { name: 'Minot Air Force Base', icao: 'KMIB' },
  { name: 'Minneapolis-St. Paul ANG Base', icao: 'KMSP' },
  { name: 'Minneapolis-St. Paul ARS', icao: 'KMSP' },
  { name: 'Misawa Air Base', icao: 'RJSM' },
  { name: 'Montgomery ANG Base (Dannelly Field)', icao: 'KMGM' },
  { name: 'Moody Air Force Base', icao: 'KVAD' },
  { name: 'Moron Air Base', icao: 'LEMO' },
  { name: 'Morris ANG Base (Tucson)', icao: 'KTUS' },
  { name: 'Mountain Home Air Force Base', icao: 'KMUO' },
  { name: 'Muwaffaq Salti Air Base', icao: 'OJMS' },
  { name: 'NAS JRB Fort Worth', icao: 'KNFW' },
  { name: 'NAS JRB New Orleans', icao: 'KNBG' },
  { name: 'Nellis Air Force Base', icao: 'KLSV' },
  { name: 'New Boston Space Force Station', icao: '' },
  { name: 'New Castle ANG Base', icao: 'KILG' },
  { name: 'Niagara Falls Air Reserve Station', icao: 'KIAG' },
  { name: 'Offutt Air Force Base', icao: 'KOFF' },
  { name: 'Osan Air Base', icao: 'RKSO' },
  { name: 'Otis ANG Base (Cape Cod)', icao: 'KFMH' },
  { name: 'Patrick Space Force Base', icao: 'KCOF' },
  { name: 'Pease ANG Base', icao: 'KPSM' },
  { name: 'Peterson Space Force Base', icao: 'KCOS' },
  { name: 'Pituffik Space Base', icao: 'BGTL' },
  { name: 'Pittsburgh Air Reserve Station', icao: 'KPIT' },
  { name: 'Pittsburgh ANG Base', icao: 'KPIT' },
  { name: 'Pope Field', icao: 'KPOB' },
  { name: 'Portland ANG Base', icao: 'KPDX' },
  { name: 'RAF Alconbury', icao: 'EGWZ' },
  { name: 'RAF Lakenheath', icao: 'EGUL' },
  { name: 'RAF Mildenhall', icao: 'EGUN' },
  { name: 'Ramstein Air Base', icao: 'ETAR' },
  { name: 'Reno-Tahoe ANG Base', icao: 'KRNO' },
  { name: 'Rickenbacker ANG Base (Columbus)', icao: 'KLCK' },
  { name: 'Robins Air Force Base', icao: 'KWRB' },
  { name: 'Roland R. Wright ANG Base', icao: 'KSLC' },
  { name: 'Rosecrans ANG Base (St. Joseph)', icao: 'KSTJ' },
  { name: 'Savannah ANG Base', icao: 'KSAV' },
  { name: 'Schriever Space Force Base', icao: '' },
  { name: 'Scott Air Force Base', icao: 'KBLV' },
  { name: 'Selfridge ANG Base', icao: 'KMTC' },
  { name: 'Seymour Johnson Air Force Base', icao: 'KGSB' },
  { name: 'Shaw Air Force Base', icao: 'KSSC' },
  { name: 'Shepherd Field ANG Base', icao: 'KMRB' },
  { name: 'Sheppard Air Force Base', icao: 'KSPS' },
  { name: 'Sioux City ANG Base', icao: 'KSUX' },
  { name: 'Spangdahlem Air Base', icao: 'ETAD' },
  { name: 'Stewart ANG Base (Newburgh)', icao: 'KSWF' },
  { name: 'Tinker Air Force Base', icao: 'KTIK' },
  { name: 'Toledo ANG Base', icao: 'KTOL' },
  { name: 'Travis Air Force Base', icao: 'KSUU' },
  { name: 'Truax Field ANG Base (Madison)', icao: 'KMSN' },
  { name: 'Tyndall Air Force Base', icao: 'KPAM' },
  { name: 'Vance Air Force Base', icao: 'KEND' },
  { name: 'Vandenberg Space Force Base', icao: 'KVBG' },
  { name: 'Warfield ANG Base (Martin State)', icao: 'KMTN' },
  { name: 'Westover Air Reserve Base', icao: 'KCEF' },
  { name: 'Whiteman Air Force Base', icao: 'KNKX' },
  { name: 'Will Rogers ANG Base (OKC)', icao: 'KOKC' },
  { name: 'Wright-Patterson Air Force Base', icao: 'KFFO' },
  { name: 'Yokota Air Base', icao: 'RJTY' },
  { name: 'Youngstown-Warren ARS', icao: 'KYNG' },
] as const
