// Static directory of all installations for dropdown selection.
// When a user selects one, it is created in the database on-demand.

export const BASE_DIRECTORY = [
  'Air Force Academy',
  'Al Udeid Air Base',
  'Altus Air Force Base',
  'Andersen Air Force Base',
  'Arnold Air Force Base',
  'Atlantic City ANG Base',
  'Aviano Air Base',
  'Bangor ANG Base',
  'Barksdale Air Force Base',
  'Barnes ANG Base',
  'Battle Creek ANG Base',
  'Beale Air Force Base',
  'Berry Field ANG Base (Nashville)',
  'Birmingham ANG Base',
  'Buckley Space Force Base',
  'Burlington ANG Base',
  'Camp Murray (Tacoma)',
  'Cannon Air Force Base',
  'Cape Canaveral Space Force Station',
  'Cape Cod Space Force Station',
  'Cavalier Space Force Station',
  'Channel Islands ANG Station',
  'Charlotte Douglas ANG Base',
  'Cheyenne ANG Base',
  'Cheyenne Mountain SFS',
  'Clear Space Force Station',
  'Columbus Air Force Base',
  'Creech Air Force Base',
  'Davis-Monthan Air Force Base',
  'Des Moines ANG Base',
  'Dobbins Air Reserve Base',
  'Dover Air Force Base',
  'Duke Field (Eglin Auxiliary)',
  'Duluth ANG Base',
  'Dyess Air Force Base',
  'Ebbing ANG Base (Fort Smith)',
  'Edwards Air Force Base',
  'Eglin Air Force Base',
  'Eielson Air Force Base',
  'Ellington Field ANG Base',
  'Ellsworth Air Force Base',
  'F.E. Warren Air Force Base',
  'Fairchild Air Force Base',
  'Forbes Field ANG Base (Topeka)',
  'Fort Wayne ANG Base',
  'Fresno ANG Base',
  'Gabreski ANG Base (Westhampton)',
  'General Mitchell ANG Base',
  'Goodfellow Air Force Base',
  'Gowen Field ANG Base (Boise)',
  'Grand Forks Air Force Base',
  'Great Falls ANG Base',
  'Grissom Air Reserve Base',
  'Hancock Field ANG Base (Syracuse)',
  'Hanscom Air Force Base',
  'Harrisburg ANG Base',
  'Hector ANG Base (Fargo)',
  'Hill Air Force Base',
  'Holloman Air Force Base',
  'Homestead Air Reserve Base',
  'Horsham ANG Base',
  'Hulman Field ANG Base',
  'Hurlburt Field',
  'Incirlik Air Base',
  'Jacksonville ANG Base',
  'JB McGuire-Dix-Lakehurst',
  'JB San Antonio-Lackland',
  'JB San Antonio-Randolph',
  'Joint Base Andrews',
  'Joint Base Elmendorf-Richardson',
  'Joint Base Langley-Eustis',
  'Joint Base Lewis-McChord',
  'Joint Base Pearl Harbor-Hickam',
  'Joe Foss Field ANG Base',
  "Ka'ena Point Space Force Station",
  'Kadena Air Base',
  'Keesler Air Force Base',
  'Kelly Field (JBSA-Lackland)',
  'Key Field ANG Base (Meridian)',
  'Kingsley Field ANG Base',
  'Kirtland Air Force Base',
  'Kunsan Air Base',
  'Lajes Field (Azores)',
  'Laughlin Air Force Base',
  'Lincoln ANG Base',
  'Little Rock Air Force Base',
  'Los Angeles Air Force Base',
  'Louisville ANG Base',
  'Luke Air Force Base',
  'MacDill Air Force Base',
  'Malmstrom Air Force Base',
  'Mansfield Lahm ANG Base',
  'March Air Reserve Base',
  'Maxwell Air Force Base',
  'McConnell Air Force Base',
  'McEntire ANG Base',
  'McGhee Tyson ANG Base',
  'McLaughlin ANG Base (Charleston)',
  'Memphis ANG Base',
  'Minot Air Force Base',
  'Minneapolis-St. Paul ANG Base',
  'Minneapolis-St. Paul ARS',
  'Misawa Air Base',
  'Montgomery ANG Base (Dannelly Field)',
  'Moody Air Force Base',
  'Moron Air Base',
  'Morris ANG Base (Tucson)',
  'Mountain Home Air Force Base',
  'Muwaffaq Salti Air Base',
  'NAS JRB Fort Worth',
  'NAS JRB New Orleans',
  'Nellis Air Force Base',
  'New Boston Space Force Station',
  'New Castle ANG Base',
  'Niagara Falls Air Reserve Station',
  'Offutt Air Force Base',
  'Osan Air Base',
  'Otis ANG Base (Cape Cod)',
  'Patrick Space Force Base',
  'Pease ANG Base',
  'Peterson Space Force Base',
  'Pituffik Space Base',
  'Pittsburgh Air Reserve Station',
  'Pittsburgh ANG Base',
  'Pope Field',
  'Portland ANG Base',
  'RAF Alconbury',
  'RAF Lakenheath',
  'RAF Mildenhall',
  'Ramstein Air Base',
  'Reno-Tahoe ANG Base',
  'Rickenbacker ANG Base (Columbus)',
  'Robins Air Force Base',
  'Roland R. Wright ANG Base',
  'Rosecrans ANG Base (St. Joseph)',
  'Savannah ANG Base',
  'Schriever Space Force Base',
  'Scott Air Force Base',
  'Selfridge ANG Base',
  'Seymour Johnson Air Force Base',
  'Shaw Air Force Base',
  'Shepherd Field ANG Base',
  'Sheppard Air Force Base',
  'Sioux City ANG Base',
  'Spangdahlem Air Base',
  'Stewart ANG Base (Newburgh)',
  'Tinker Air Force Base',
  'Toledo ANG Base',
  'Travis Air Force Base',
  'Truax Field ANG Base (Madison)',
  'Tyndall Air Force Base',
  'Vance Air Force Base',
  'Vandenberg Space Force Base',
  'Warfield ANG Base (Martin State)',
  'Westover Air Reserve Base',
  'Whiteman Air Force Base',
  'Will Rogers ANG Base (OKC)',
  'Wright-Patterson Air Force Base',
  'Yokota Air Base',
  'Youngstown-Warren ARS',
] as const
