// Demo data matching the Airfield_OPS_Unified_Prototype.jsx
// Used for UI rendering until Supabase is connected (Step 9)

export const DEMO_DISCREPANCIES = [
  {
    id: 'demo-001', display_id: 'D-2026-0042', type: 'pavement', severity: 'critical' as const,
    status: 'open' as const, current_status: 'submitted_to_ces' as const,
    title: 'Pavement spall TWY A intersection',
    description: '12x18 inch spall, 2 inch depth. FOD potential from loose aggregate.',
    location_text: 'TWY', assigned_shop: 'CE Pavements', reported_by: 'demo-user',
    work_order_number: 'WO-2026-0038',
    photo_count: 2, linked_notam_id: null, created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    days_open: 9,
  },
  {
    id: 'demo-002', display_id: 'D-2026-0041', type: 'lighting', severity: 'critical' as const,
    status: 'open' as const, current_status: 'awaiting_action_by_ces' as const,
    title: 'MALSR RWY 01 Stations 7&8 OTS',
    description: 'MALSR stations 7 and 8 inoperative. Approach lighting degraded. Parts ETA Monday.',
    location_text: 'RWY', assigned_shop: 'CE Electrical', reported_by: 'demo-user',
    work_order_number: 'WO-2026-0037',
    photo_count: 3, linked_notam_id: 'demo-notam-1', created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    days_open: 4,
  },
  {
    id: 'demo-003', display_id: 'D-2026-0039', type: 'marking', severity: 'medium' as const,
    status: 'open' as const, current_status: 'submitted_to_afm' as const,
    title: 'TDZ marking faded RWY 01',
    description: 'Touchdown zone markings below minimum reflectivity per UFC 3-260-01.',
    location_text: 'RWY', assigned_shop: 'CE Pavements', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: null, created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    days_open: 16,
  },
  {
    id: 'demo-004', display_id: 'D-2026-0038', type: 'lighting', severity: 'low' as const,
    status: 'open' as const, current_status: 'submitted_to_afm' as const,
    title: 'TWY B edge light #14 lens cracked',
    description: 'Blue edge light lens cracked but illuminating. Replacement on order.',
    location_text: 'TWY', assigned_shop: 'CE Electrical', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: 'demo-notam-2', created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    days_open: 18,
  },
  {
    id: 'demo-005', display_id: 'D-2026-0037', type: 'drainage', severity: 'medium' as const,
    status: 'completed' as const, current_status: 'work_completed_awaiting_verification' as const,
    title: 'Standing water near TWY C holdshort',
    description: 'Drain inlet cleared. Monitoring for recurrence.',
    location_text: 'TWY', assigned_shop: 'CE Grounds', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 2, linked_notam_id: null, created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    days_open: 0,
  },
  {
    id: 'demo-006', display_id: 'D-2026-0036', type: 'signage', severity: 'low' as const,
    status: 'completed' as const, current_status: 'work_completed_awaiting_verification' as const,
    title: 'Runway distance remaining sign tilted',
    description: 'Sign post base re-secured and leveled.',
    location_text: 'RWY', assigned_shop: 'CE Structures', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: null, created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    days_open: 0,
  },
]

export const DEMO_NOTAMS = [
  {
    id: 'demo-notam-1', notam_number: '01/003', source: 'faa' as const, status: 'active' as const,
    notam_type: 'Lighting', title: 'MALSR RWY 01 STA 7-8 OTS',
    full_text: 'KMTC MALSR RWY 01 STATIONS 7 AND 8 OUT OF SERVICE.',
    effective_start: '2026-02-03T00:00:00Z', effective_end: '2026-02-15T00:00:00Z',
    linked_discrepancy_id: 'demo-002', created_at: '2026-02-03T00:00:00Z',
  },
  {
    id: 'demo-notam-2', notam_number: '01/002', source: 'faa' as const, status: 'active' as const,
    notam_type: 'Lighting', title: 'TWY B EDGE LGT 14 REDUCED INTST',
    full_text: 'KMTC TWY B EDGE LIGHT 14 REDUCED INTENSITY.',
    effective_start: '2026-01-21T00:00:00Z', effective_end: '2026-03-01T00:00:00Z',
    linked_discrepancy_id: 'demo-004', created_at: '2026-01-21T00:00:00Z',
  },
  {
    id: 'demo-notam-3', notam_number: 'L-2026-0088', source: 'local' as const, status: 'active' as const,
    notam_type: 'Construction', title: 'TWY A/B REPAIR AREA',
    full_text: 'CAUTION: PAVEMENT REPAIR IN PROGRESS TWY A/B INTERSECTION.',
    effective_start: '2026-02-01T00:00:00Z', effective_end: '2026-02-28T00:00:00Z',
    linked_discrepancy_id: null, created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'demo-notam-4', notam_number: '01/001', source: 'faa' as const, status: 'expired' as const,
    notam_type: 'NAVAID', title: 'ILS RWY 01 GP OTS FOR MAINT',
    full_text: 'KMTC ILS RWY 01 GLIDEPATH OUT OF SERVICE.',
    effective_start: '2026-01-10T00:00:00Z', effective_end: '2026-01-12T00:00:00Z',
    linked_discrepancy_id: null, created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'demo-notam-5', notam_number: 'M-2026-0012', source: 'local' as const, status: 'active' as const,
    notam_type: 'Runway Closure', title: 'RWY 01/19 CLSD FOR EMERG REPAIR',
    full_text: 'KMTC RWY 01/19 CLOSED FOR EMERGENCY PAVEMENT REPAIR. ETA REOPENING 1800Z.',
    effective_start: '2026-02-25T06:00:00Z', effective_end: '2026-02-26T18:00:00Z',
    linked_discrepancy_id: null, created_at: '2026-02-25T06:00:00Z',
  },
]

export const DEMO_CHECKS = [
  {
    id: 'demo-check-1', display_id: 'AC-0098', check_type: 'fod' as const,
    areas: ['RWY 01/19', 'TWY A', 'TWY B'],
    data: {},
    completed_by: 'TSgt Williams', completed_at: new Date().toISOString(),
    latitude: 42.6108, longitude: -82.8371,
    photo_count: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-check-2', display_id: 'AC-0097', check_type: 'bash' as const,
    areas: ['Entire Airfield'],
    data: { condition_code: 'LOW', species_observed: 'Canada geese (4, grazing N side), Red-tailed hawk (1, perched)' },
    completed_by: 'MSgt Proctor', completed_at: new Date().toISOString(),
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-check-3', display_id: 'AC-0096', check_type: 'rcr' as const,
    areas: ['RWY 01/19'],
    data: { rcr_value: '64', condition_type: 'Dry' },
    completed_by: 'SrA Martinez', completed_at: new Date(Date.now() - 86400000).toISOString(),
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: new Date(Date.now() - 86400000).toISOString(), updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-check-4', display_id: 'AC-0095', check_type: 'rsc' as const,
    areas: ['RWY 01/19'],
    data: { condition: 'Wet' },
    completed_by: 'TSgt Williams', completed_at: '2026-02-05T06:30:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-05T06:30:00Z', updated_at: '2026-02-05T06:30:00Z',
  },
  {
    id: 'demo-check-5', display_id: 'AC-0094', check_type: 'ife' as const,
    areas: ['RWY 01/19'],
    data: { aircraft_type: 'KC-135R', callsign: 'BOLT 31', nature: 'Hydraulic failure', actions: ['Notified ATC / Tower', 'Activated crash phone / primary crash net', 'Coordinated with Fire Department / ARFF'], agencies_notified: ['SOF', 'Fire Chief / ARFF', 'ATC / Tower', 'Command Post'] },
    completed_by: 'MSgt Proctor', completed_at: '2026-02-04T14:22:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-04T14:22:00Z', updated_at: '2026-02-04T14:22:00Z',
  },
  {
    id: 'demo-check-6', display_id: 'AC-0093', check_type: 'heavy_aircraft' as const,
    areas: ['RWY 01/19', 'TWY A', 'Apron/Ramp'],
    data: { aircraft_type: 'C-17A Globemaster III' },
    completed_by: 'MSgt Proctor', completed_at: '2026-02-03T18:45:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-03T18:45:00Z', updated_at: '2026-02-03T18:45:00Z',
  },
  {
    id: 'demo-check-7', display_id: 'AC-0092', check_type: 'ground_emergency' as const,
    areas: ['Apron/Ramp'],
    data: { aircraft_type: 'A-10C', nature: 'Hot brakes', actions: ['Notified ATC / Tower', 'Coordinated with Fire Department / ARFF'], agencies_notified: ['Fire Chief / ARFF', 'MOC', 'Wing Safety'] },
    completed_by: 'TSgt Williams', completed_at: '2026-02-02T11:15:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-02T11:15:00Z', updated_at: '2026-02-02T11:15:00Z',
  },
]

export const DEMO_INSPECTIONS = [
  {
    id: 'demo-insp-1',
    display_id: 'AI-2026-00A1',
    inspection_type: 'airfield' as const,
    inspector_id: 'demo-user',
    inspector_name: 'MSgt Proctor',
    inspection_date: new Date().toISOString().split('T')[0],
    status: 'completed' as const,
    items: [
      { id: 'af-1', section: 'Section 1 — Obstacle Clearance Criteria', item: "Primary Surface — 1000' from runway centerline", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-2', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Transitional Slope (7:1)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-3', section: 'Section 1 — Obstacle Clearance Criteria', item: "Runway Clear Zones — 3000'L x 3000'W", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-4', section: 'Section 1 — Obstacle Clearance Criteria', item: "Graded Portion of Clear Zone — 1000'L x 3000'W", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-5', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Approach / Departure Surface (50:1)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-6', section: 'Section 1 — Obstacle Clearance Criteria', item: "Taxiway — 200' from centerline", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-7', section: 'Section 1 — Obstacle Clearance Criteria', item: "Apron — 110' from boundary marking", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-8', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Construction Areas', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-11', section: 'Section 2 — Signs/Lights', item: 'VFR Holding Positions', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-12', section: 'Section 2 — Signs/Lights', item: 'Instrument Holding Positions', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-13', section: 'Section 2 — Signs/Lights', item: 'Elevation Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-14', section: 'Section 2 — Signs/Lights', item: 'Taxiway Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-15', section: 'Section 2 — Signs/Lights', item: 'Windcone', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-16', section: 'Section 2 — Signs/Lights', item: 'FOD/STOP', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-17', section: 'Section 2 — Signs/Lights', item: 'Runway Signs', response: 'fail' as const, notes: 'Sign #4 reflectivity below minimum', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-18', section: 'Section 2 — Signs/Lights', item: 'NAVAID Ground Receiver Checkpoints', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-19', section: 'Section 2 — Signs/Lights', item: 'Closed Areas', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-20', section: 'Section 3 — Construction', item: 'Parking', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-21', section: 'Section 3 — Construction', item: 'Rules Compliance', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-22', section: 'Section 3 — Construction', item: 'Construction Site Lighting/Marking', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-23', section: 'Section 3 — Construction', item: 'Storage', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-24', section: 'Section 3 — Construction', item: 'Vehicles Lighted/Marked', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-25', section: 'Section 3 — Construction', item: 'FOD Control (Debris/Trash/Vehicle Routes)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-26', section: 'Section 4 — Habitat Management', item: 'Grass Height (7–14")', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-27', section: 'Section 4 — Habitat Management', item: 'Ponding Effects', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-28', section: 'Section 4 — Habitat Management', item: 'Bird/Animal Survey', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-29', section: 'Section 4 — Habitat Management', item: 'Bird Watch Condition (BWC)', response: 'pass' as const, notes: 'LOW', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-30', section: 'Section 5 — Pavement Condition / Markings', item: 'Runway/Overruns 01/19', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-31', section: 'Section 5 — Pavement Condition / Markings', item: 'Taxiways', response: 'fail' as const, notes: 'TWY A/B intersection spall — existing discrepancy D-2026-0042', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-32', section: 'Section 5 — Pavement Condition / Markings', item: 'Access Roads / FOD Checks', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-33', section: 'Section 5 — Pavement Condition / Markings', item: 'Grounding Points', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-34', section: 'Section 6 — Airfield Driving', item: 'FOD Control', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-35', section: 'Section 6 — Airfield Driving', item: 'Compliance with Procedures', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-36', section: 'Section 6 — Airfield Driving', item: 'Properly Stowed/Secured Equipment', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-37', section: 'Section 7 — FOD Control', item: 'Runways/Overruns, Taxiways/Shoulders', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-38', section: 'Section 7 — FOD Control', item: 'Parking Aprons', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-39', section: 'Section 7 — FOD Control', item: 'Infield Areas Between Runways/Taxiways', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-40', section: 'Section 7 — FOD Control', item: 'Perimeter/Access Roads', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
    ],
    total_items: 40,
    passed_count: 36,
    failed_count: 2,
    na_count: 2,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    personnel: [] as string[],
    bwc_value: 'LOW',
    weather_conditions: 'Clear',
    temperature_f: 28,
    notes: null,
    daily_group_id: 'demo-daily-1',
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-insp-2',
    display_id: 'LI-2026-009F',
    inspection_type: 'lighting' as const,
    inspector_id: 'demo-user',
    inspector_name: 'TSgt Williams',
    inspection_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    status: 'completed' as const,
    items: [
      { id: 'lt-1', section: 'Section 1 — Runway 01 Lighting', item: '01/19 Edge Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-2', section: 'Section 1 — Runway 01 Lighting', item: '01 Approach Lighting (SALS)', response: 'fail' as const, notes: 'Stations 7-8 OTS — see D-2026-0041', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-3', section: 'Section 1 — Runway 01 Lighting', item: '01 Threshold Bar / 19 Runway End Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-4', section: 'Section 1 — Runway 01 Lighting', item: '01 PAPI', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-5', section: 'Section 1 — Runway 01 Lighting', item: 'South Hammerhead Edge Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-6', section: 'Section 2 — Runway 19 Lighting', item: '19 Threshold Bar / 01 Runway End Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-7', section: 'Section 2 — Runway 19 Lighting', item: '19 PAPI', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-8', section: 'Section 2 — Runway 19 Lighting', item: '19 REILs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-9', section: 'Section 2 — Runway 19 Lighting', item: 'Intensity Level Check on HIRLs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-10', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY A', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-11', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY K', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-12', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY B', response: 'fail' as const, notes: 'Edge light #14 lens cracked — see D-2026-0038', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-13', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY L', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-14', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY J', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-15', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY E', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-16', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY G', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-17', section: 'Section 3 — Taxiway/Apron Lighting', item: 'East Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-18', section: 'Section 3 — Taxiway/Apron Lighting', item: 'West Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-19', section: 'Section 3 — Taxiway/Apron Lighting', item: 'USCG Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-20', section: 'Section 3 — Taxiway/Apron Lighting', item: 'DHS Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-21', section: 'Section 3 — Taxiway/Apron Lighting', item: 'West Side Stadium Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-22', section: 'Section 3 — Taxiway/Apron Lighting', item: 'East Side Stadium Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-23', section: 'Section 4 — Signs & Markings', item: 'Runway Hold Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-24', section: 'Section 4 — Signs & Markings', item: 'Taxiway Guidance Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-25', section: 'Section 4 — Signs & Markings', item: 'Instrument Hold Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-26', section: 'Section 4 — Signs & Markings', item: '01/19 DRMs (Distance Remaining Markers)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-27', section: 'Section 4 — Signs & Markings', item: 'NAVAID Checkpoint', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-28', section: 'Section 4 — Signs & Markings', item: 'Marking Retroreflectivity', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-29', section: 'Section 5 — Miscellaneous', item: 'Obstruction Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-30', section: 'Section 5 — Miscellaneous', item: 'Rotating Beacon', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-31', section: 'Section 5 — Miscellaneous', item: 'Wind Cones', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-32', section: 'Section 5 — Miscellaneous', item: 'Construction Barriers', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
    ],
    total_items: 32,
    passed_count: 29,
    failed_count: 2,
    na_count: 1,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    personnel: [] as string[],
    bwc_value: null,
    weather_conditions: 'Overcast',
    temperature_f: 32,
    notes: 'Night lighting inspection — all systems operational except noted discrepancies.',
    daily_group_id: 'demo-daily-1',
    completed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'demo-insp-3',
    display_id: 'AI-2026-008E',
    inspection_type: 'airfield' as const,
    inspector_id: 'demo-user',
    inspector_name: 'SrA Martinez',
    inspection_date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    status: 'completed' as const,
    items: [],
    total_items: 40,
    passed_count: 40,
    failed_count: 0,
    na_count: 0,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    personnel: [] as string[],
    bwc_value: 'LOW',
    weather_conditions: 'Clear',
    temperature_f: 35,
    notes: 'All items satisfactory. No discrepancies noted.',
    daily_group_id: 'demo-daily-2',
    completed_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
]

export const DEMO_WAIVERS = [
  {
    id: 'demo-waiver-1', base_id: 'demo-base',
    waiver_number: 'VGLZ050224002', classification: 'permanent' as const, status: 'active' as const,
    hazard_rating: 'medium' as const, action_requested: 'new' as const,
    description: 'Runway 01/19 Lateral Clear Zone obstruction — Base perimeter fence within 500\' of runway CL. Fence required by DoD security standards.',
    justification: 'Security fence is a DoD-mandated force protection requirement. Cannot be relocated without MAJCOM/A7 waiver of security standards.',
    risk_assessment_summary: 'Fence is frangible construction, located outside primary surface. Risk mitigated by frangible design and NOTAM.',
    corrective_action: null, criteria_impact: '500\' clear zone encroachment',
    proponent: '127 CES/CEAO', project_number: null, program_fy: null,
    estimated_cost: null, project_status: null,
    faa_case_number: null, period_valid: 'Indefinite',
    date_submitted: '2024-02-15', date_approved: '2024-05-01', expiration_date: null,
    last_reviewed_date: '2025-02-20', next_review_due: '2026-02-01',
    location_description: 'RWY 01/19 Lateral CZ', location_lat: 42.6125, location_lng: -82.8345,
    notes: null, photo_count: 1, attachment_count: 2,
    created_by: null, updated_by: null,
    created_at: new Date(Date.now() - 365 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'demo-waiver-2', base_id: 'demo-base',
    waiver_number: 'VGLZ050224007', classification: 'temporary' as const, status: 'active' as const,
    hazard_rating: 'high' as const, action_requested: 'new' as const,
    description: 'TWY B edge lights inoperative — 6 of 22 fixtures failed, below minimum 85% threshold. Parts on order, ECD Jun 2026.',
    justification: 'Parts lead time exceeds 120 days. TWY B required for daily F-16 operations. Alternate routing via TWY A adds 15 min per sortie.',
    risk_assessment_summary: 'Night ops restricted to PAPI-guided approach only. Added reflective markers at affected positions.',
    corrective_action: 'Replace 6 inoperative edge light fixtures', criteria_impact: '73% TWY B edge light operability (min 85%)',
    proponent: '127 CES/CEIE', project_number: 'VGLZ009082', program_fy: 2026,
    estimated_cost: 45000, project_status: 'Parts on order',
    faa_case_number: null, period_valid: '8-Years',
    date_submitted: '2025-01-10', date_approved: '2025-03-15', expiration_date: '2033-03-15',
    last_reviewed_date: '2025-02-20', next_review_due: '2026-02-01',
    location_description: 'TWY B', location_lat: 42.6098, location_lng: -82.8389,
    notes: null, photo_count: 2, attachment_count: 3,
    created_by: null, updated_by: null,
    created_at: new Date(Date.now() - 200 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'demo-waiver-3', base_id: 'demo-base',
    waiver_number: 'P-VGLZ-26-01', classification: 'permanent' as const, status: 'draft' as const,
    hazard_rating: null, action_requested: 'new' as const,
    description: 'RWY 01 approach slope penetration — tree line 4,200\' from threshold exceeds 50:1 approach surface by 9\'.',
    justification: 'Trees are on non-DoD land (Mt. Clemens city property). Trimming agreement pending city council approval.',
    risk_assessment_summary: null,
    corrective_action: 'Negotiate tree-trimming easement with City of Mt. Clemens', criteria_impact: '9\' approach surface penetration',
    proponent: '127 CES/CEAO', project_number: null, program_fy: 2027,
    estimated_cost: 85000, project_status: 'Pending city council',
    faa_case_number: '2026-AGL-1234-OE', period_valid: null,
    date_submitted: null, date_approved: null, expiration_date: null,
    last_reviewed_date: null, next_review_due: null,
    location_description: 'RWY 01 Approach', location_lat: 42.6052, location_lng: -82.8360,
    notes: 'Draft — awaiting risk assessment completion', photo_count: 0, attachment_count: 0,
    created_by: null, updated_by: null,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'demo-waiver-4', base_id: 'demo-base',
    waiver_number: 'VGLZ050224010', classification: 'construction' as const, status: 'completed' as const,
    hazard_rating: 'medium' as const, action_requested: 'new' as const,
    description: 'TWY A/B intersection joint sealing project — temporary closure and equipment staging within transitional surface.',
    justification: 'Joint sealing prevents pavement deterioration and FOD generation. Project window limited to summer months.',
    risk_assessment_summary: 'Equipment staged below transitional surface limits. Obstruction lights installed on all equipment.',
    corrective_action: 'Complete joint sealing operations', criteria_impact: 'TWY A/B intersection closure',
    proponent: '127 CES/CEAO', project_number: 'VGLZ009045', program_fy: 2025,
    estimated_cost: 120000, project_status: 'Completed Aug 2025',
    faa_case_number: null, period_valid: 'Duration of Construction',
    date_submitted: '2025-04-15', date_approved: '2025-05-01', expiration_date: '2025-09-30',
    last_reviewed_date: '2025-02-20', next_review_due: null,
    location_description: 'TWY A/B Intersection', location_lat: 42.6115, location_lng: -82.8372,
    notes: 'Project completed on schedule. All equipment removed. Waiver closed.', photo_count: 3, attachment_count: 4,
    created_by: null, updated_by: null,
    created_at: new Date(Date.now() - 300 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 150 * 86400000).toISOString(),
  },
  {
    id: 'demo-waiver-5', base_id: 'demo-base',
    waiver_number: 'VGLZ050224015', classification: 'temporary' as const, status: 'active' as const,
    hazard_rating: 'low' as const, action_requested: 'new' as const,
    description: 'Airfield perimeter road drainage deficiency — standing water on access road segment D-7 during heavy rain events.',
    justification: 'Drainage project programmed for FY27. Interim mitigation: grading and temporary culvert installed.',
    risk_assessment_summary: 'Road passable except during extreme events (>2" rain/hr). Alternate route available via Gate 4.',
    corrective_action: 'Drainage improvement project — new culvert and regrading', criteria_impact: 'Perimeter road segment D-7 flooding',
    proponent: '127 CES/CEOH', project_number: 'VGLZ009091', program_fy: 2027,
    estimated_cost: 250000, project_status: 'Design 60% complete',
    faa_case_number: null, period_valid: '8-Years',
    date_submitted: '2024-06-01', date_approved: '2024-08-15', expiration_date: '2032-08-15',
    last_reviewed_date: '2025-02-20', next_review_due: '2026-02-01',
    location_description: 'Perimeter Road Segment D-7', location_lat: 42.6142, location_lng: -82.8410,
    notes: null, photo_count: 1, attachment_count: 1,
    created_by: null, updated_by: null,
    created_at: new Date(Date.now() - 600 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
]

export const DEMO_ACSI_INSPECTIONS = [
  {
    id: 'demo-acsi-1',
    display_id: 'ACSI-2025-A1B2',
    base_id: 'demo-base',
    airfield_name: 'Selfridge ANGB',
    inspection_date: '2025-09-15',
    fiscal_year: 2025,
    status: 'completed' as const,
    items: [],
    total_items: 90,
    passed_count: 82,
    failed_count: 5,
    na_count: 3,
    inspection_team: [
      { id: 't1', role: 'afm', name: 'MSgt Proctor', rank: 'MSgt', title: 'Airfield Manager' },
      { id: 't2', role: 'ce', name: 'Maj Smith', rank: 'Maj', title: 'CE Representative' },
      { id: 't3', role: 'safety', name: 'TSgt Rivera', rank: 'TSgt', title: 'Wing Safety' },
    ],
    risk_cert_signatures: [
      { organization: '127 OG', name: 'Col Johnson', rank: 'Col', title: 'OG/CC' },
      { organization: '127 MSG', name: 'Col Adams', rank: 'Col', title: 'MSG/CC' },
      { organization: '127 WG', name: 'Brig Gen Taylor', rank: 'Brig Gen', title: 'WG/CC' },
    ],
    notes: 'Annual ACSI completed. 5 discrepancies documented with work orders assigned. All risk control measures in place.',
    inspector_id: 'demo-user',
    inspector_name: 'MSgt Proctor',
    draft_data: null,
    completed_at: '2025-09-15T16:00:00Z',
    completed_by_name: 'MSgt Proctor',
    completed_by_id: 'demo-user',
    filed_at: '2025-09-20T12:00:00Z',
    filed_by_name: 'MSgt Proctor',
    filed_by_id: 'demo-user',
    saved_at: null,
    saved_by_name: null,
    saved_by_id: null,
    created_at: '2025-09-15T08:00:00Z',
    updated_at: '2025-09-20T12:00:00Z',
  },
  {
    id: 'demo-acsi-2',
    display_id: 'ACSI-2026-C3D4',
    base_id: 'demo-base',
    airfield_name: 'Selfridge ANGB',
    inspection_date: new Date().toISOString().split('T')[0],
    fiscal_year: 2026,
    status: 'in_progress' as const,
    items: [],
    total_items: 90,
    passed_count: 34,
    failed_count: 2,
    na_count: 1,
    inspection_team: [
      { id: 't1', role: 'afm', name: 'MSgt Proctor', rank: 'MSgt', title: 'Airfield Manager' },
      { id: 't2', role: 'ce', name: 'Maj Smith', rank: 'Maj', title: 'CE Representative' },
      { id: 't3', role: 'safety', name: '', rank: '', title: 'Safety' },
    ],
    risk_cert_signatures: [],
    notes: null,
    inspector_id: 'demo-user',
    inspector_name: 'MSgt Proctor',
    draft_data: null,
    completed_at: null,
    completed_by_name: null,
    completed_by_id: null,
    filed_at: null,
    filed_by_name: null,
    filed_by_id: null,
    saved_at: new Date().toISOString(),
    saved_by_name: 'MSgt Proctor',
    saved_by_id: 'demo-user',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_WAIVER_CRITERIA = [
  { id: 'demo-wc-1', waiver_id: 'demo-waiver-1', criteria_source: 'ufc_3_260_01' as const, reference: 'Table 5.1, Item 3', description: 'Lateral Clear Zone — 500\' from runway CL', sort_order: 0 },
  { id: 'demo-wc-2', waiver_id: 'demo-waiver-2', criteria_source: 'ufc_3_535_01' as const, reference: 'Para 6.12.3', description: 'Taxiway edge lights — minimum 85% operability', sort_order: 0 },
  { id: 'demo-wc-3', waiver_id: 'demo-waiver-3', criteria_source: 'ufc_3_260_01' as const, reference: 'Table 5.1, Item 1', description: 'Approach Surface (50:1) — 9\' penetration', sort_order: 0 },
  { id: 'demo-wc-4', waiver_id: 'demo-waiver-4', criteria_source: 'ufc_3_260_04' as const, reference: 'Para 3.2.1', description: 'Taxiway closure — transitional surface equipment staging', sort_order: 0 },
  { id: 'demo-wc-5', waiver_id: 'demo-waiver-5', criteria_source: 'ufc_3_260_01' as const, reference: 'Para 8.4.2', description: 'Perimeter road drainage requirements', sort_order: 0 },
]

export const DEMO_WAIVER_REVIEWS = [
  { id: 'demo-wr-1', waiver_id: 'demo-waiver-1', review_year: 2025, review_date: '2025-02-20', reviewed_by: null, recommendation: 'retain' as const, mitigation_verified: true, project_status_update: 'No change — permanent condition', notes: null, presented_to_facilities_board: true, facilities_board_date: '2025-03-15', created_at: '2025-02-20T12:00:00Z' },
  { id: 'demo-wr-2', waiver_id: 'demo-waiver-2', review_year: 2025, review_date: '2025-02-20', reviewed_by: null, recommendation: 'retain' as const, mitigation_verified: true, project_status_update: 'Parts on order — ECD Jun 2026', notes: null, presented_to_facilities_board: true, facilities_board_date: '2025-03-15', created_at: '2025-02-20T12:00:00Z' },
  { id: 'demo-wr-3', waiver_id: 'demo-waiver-4', review_year: 2025, review_date: '2025-02-20', reviewed_by: null, recommendation: 'cancel' as const, mitigation_verified: true, project_status_update: 'Project completed Aug 2025', notes: 'Recommend closing — construction complete', presented_to_facilities_board: true, facilities_board_date: '2025-03-15', created_at: '2025-02-20T12:00:00Z' },
  { id: 'demo-wr-4', waiver_id: 'demo-waiver-5', review_year: 2025, review_date: '2025-02-20', reviewed_by: null, recommendation: 'retain' as const, mitigation_verified: true, project_status_update: 'Design 60% complete, FY27 funded', notes: null, presented_to_facilities_board: true, facilities_board_date: '2025-03-15', created_at: '2025-02-20T12:00:00Z' },
]

export const DEMO_WAIVER_COORDINATION = [
  { id: 'demo-coord-1', waiver_id: 'demo-waiver-1', office: 'civil_engineer' as const, office_label: null, coordinator_name: 'Maj Smith', coordinated_date: '2024-03-01', status: 'concur' as const, comments: null },
  { id: 'demo-coord-2', waiver_id: 'demo-waiver-1', office: 'airfield_manager' as const, office_label: null, coordinator_name: 'MSgt Proctor', coordinated_date: '2024-03-05', status: 'concur' as const, comments: null },
  { id: 'demo-coord-3', waiver_id: 'demo-waiver-1', office: 'base_safety' as const, office_label: null, coordinator_name: 'TSgt Rivera', coordinated_date: '2024-03-10', status: 'concur' as const, comments: 'Frangible construction verified' },
  { id: 'demo-coord-4', waiver_id: 'demo-waiver-2', office: 'civil_engineer' as const, office_label: null, coordinator_name: 'Maj Smith', coordinated_date: '2025-01-15', status: 'concur' as const, comments: null },
  { id: 'demo-coord-5', waiver_id: 'demo-waiver-2', office: 'airfield_manager' as const, office_label: null, coordinator_name: 'MSgt Proctor', coordinated_date: '2025-01-18', status: 'concur' as const, comments: 'Night ops restrictions acknowledged' },
]

export const DEMO_CHECK_COMMENTS = [
  {
    id: 'demo-cc-1', check_id: 'demo-check-1', comment: 'Metal bolt (1/4") found near TWY A intersection — disposed.',
    user_name: 'TSgt Williams', created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-cc-2', check_id: 'demo-check-1', comment: 'Rubber fragment (3") found midfield — disposed. All areas clear.',
    user_name: 'TSgt Williams', created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-cc-3', check_id: 'demo-check-5', comment: 'Aircraft landed safely RWY 01. Post-landing inspection complete. Runway released to ATC.',
    user_name: 'MSgt Proctor', created_at: '2026-02-04T15:04:00Z',
  },
]

export const DEMO_CONTRACTORS = [
  {
    id: 'demo-contr-1', base_id: 'demo-base',
    company_name: 'Kiewit Infrastructure', contact_name: 'Mike Daniels',
    location: 'TWY A/B Intersection', work_description: 'Joint sealing and pavement repair — Phase 2',
    status: 'active' as const, start_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    end_date: null, notes: 'Crew of 6, daily 0700-1600. Equipment staged on south apron.',
    radio_number: 'R-14', flag_number: 'F-3', callsign: 'KIEWIT 1',
    created_by: null, created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'demo-contr-2', base_id: 'demo-base',
    company_name: 'Musco Lighting LLC', contact_name: 'Sarah Chen',
    location: 'RWY 01/19 Approach', work_description: 'MALSR station 7-8 replacement and re-alignment',
    status: 'active' as const, start_date: new Date(Date.now() - 2 * 86400000).toISOString().split('T')[0],
    end_date: null, notes: 'FAA coordination required. Night work only 2200-0500.',
    radio_number: 'R-15', flag_number: null, callsign: 'MUSCO',
    created_by: null, created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'demo-contr-3', base_id: 'demo-base',
    company_name: 'AECOM', contact_name: 'John Reeves',
    location: 'West Ramp', work_description: 'Apron drainage assessment and core sampling',
    status: 'completed' as const, start_date: new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    notes: 'Final report delivered to CE.',
    radio_number: 'R-12', flag_number: 'F-1', callsign: 'AECOM SURVEY',
    created_by: null, created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'demo-contr-4', base_id: 'demo-base',
    company_name: 'Striping Solutions Inc', contact_name: null,
    location: 'RWY 01/19 TDZ', work_description: 'Touchdown zone and centerline marking repaint',
    status: 'completed' as const, start_date: new Date(Date.now() - 45 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() - 40 * 86400000).toISOString().split('T')[0],
    notes: null,
    radio_number: null, flag_number: null, callsign: null,
    created_by: null, created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
]
