// Demo data matching the Airfield_OPS_Unified_Prototype.jsx
// Used for UI rendering until Supabase is connected (Step 9)

export const DEMO_DISCREPANCIES = [
  {
    id: 'demo-001', display_id: 'D-2026-0042', type: 'pavement', severity: 'critical' as const,
    status: 'open' as const, current_status: 'submitted_to_ces' as const,
    title: 'Pavement spall TWY A intersection',
    description: '12x18 inch spall, 2 inch depth. FOD potential from loose aggregate.',
    location_text: 'TWY', assigned_shop: 'CE Pavements', reported_by: 'demo-user',
    work_order_number: 'WO-2026-0038',
    photo_count: 2, linked_notam_id: null, created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    days_open: 9,
  },
  {
    id: 'demo-002', display_id: 'D-2026-0041', type: 'lighting', severity: 'critical' as const,
    status: 'open' as const, current_status: 'awaiting_action_by_ces' as const,
    title: 'MALSR RWY 01 Stations 7&8 OTS',
    description: 'MALSR stations 7 and 8 inoperative. Approach lighting degraded. Parts ETA Monday.',
    location_text: 'RWY', assigned_shop: 'CE Electrical', reported_by: 'demo-user',
    work_order_number: 'WO-2026-0037',
    photo_count: 3, linked_notam_id: 'demo-notam-1', created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    days_open: 4,
  },
  {
    id: 'demo-003', display_id: 'D-2026-0039', type: 'marking', severity: 'medium' as const,
    status: 'open' as const, current_status: 'submitted_to_afm' as const,
    title: 'TDZ marking faded RWY 01',
    description: 'Touchdown zone markings below minimum reflectivity per UFC 3-260-01.',
    location_text: 'RWY', assigned_shop: 'CE Pavements', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: null, created_at: new Date(Date.now() - 16 * 86400000).toISOString(),
    days_open: 16,
  },
  {
    id: 'demo-004', display_id: 'D-2026-0038', type: 'lighting', severity: 'low' as const,
    status: 'open' as const, current_status: 'submitted_to_afm' as const,
    title: 'TWY B edge light #14 lens cracked',
    description: 'Blue edge light lens cracked but illuminating. Replacement on order.',
    location_text: 'TWY', assigned_shop: 'CE Electrical', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: 'demo-notam-2', created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
    days_open: 18,
  },
  {
    id: 'demo-005', display_id: 'D-2026-0037', type: 'drainage', severity: 'medium' as const,
    status: 'completed' as const, current_status: 'work_completed_awaiting_verification' as const,
    title: 'Standing water near TWY C holdshort',
    description: 'Drain inlet cleared. Monitoring for recurrence.',
    location_text: 'TWY', assigned_shop: 'CE Grounds', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 2, linked_notam_id: null, created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    days_open: 0,
  },
  {
    id: 'demo-006', display_id: 'D-2026-0036', type: 'signage', severity: 'low' as const,
    status: 'completed' as const, current_status: 'work_completed_awaiting_verification' as const,
    title: 'Runway distance remaining sign tilted',
    description: 'Sign post base re-secured and leveled.',
    location_text: 'RWY', assigned_shop: 'CE Structures', reported_by: 'demo-user',
    work_order_number: null,
    photo_count: 1, linked_notam_id: null, created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    days_open: 0,
  },
]

export const DEMO_NOTAMS = [
  {
    id: 'demo-notam-1', notam_number: '01/003', source: 'faa' as const, status: 'active' as const,
    notam_type: 'Lighting', title: 'MALSR RWY 01 STA 7-8 OTS',
    full_text: 'KMTC MALSR RWY 01 STATIONS 7 AND 8 OUT OF SERVICE.',
    effective_start: '2026-02-03T00:00:00Z', effective_end: '2026-02-15T00:00:00Z',
    linked_discrepancy_id: 'demo-002', created_at: '2026-02-03T00:00:00Z',
  },
  {
    id: 'demo-notam-2', notam_number: '01/002', source: 'faa' as const, status: 'active' as const,
    notam_type: 'Lighting', title: 'TWY B EDGE LGT 14 REDUCED INTST',
    full_text: 'KMTC TWY B EDGE LIGHT 14 REDUCED INTENSITY.',
    effective_start: '2026-01-21T00:00:00Z', effective_end: '2026-03-01T00:00:00Z',
    linked_discrepancy_id: 'demo-004', created_at: '2026-01-21T00:00:00Z',
  },
  {
    id: 'demo-notam-3', notam_number: 'N-2026-0088', source: 'local' as const, status: 'active' as const,
    notam_type: 'Construction', title: 'TWY A/B REPAIR AREA',
    full_text: 'CAUTION: PAVEMENT REPAIR IN PROGRESS TWY A/B INTERSECTION.',
    effective_start: '2026-02-01T00:00:00Z', effective_end: '2026-02-28T00:00:00Z',
    linked_discrepancy_id: null, created_at: '2026-02-01T00:00:00Z',
  },
  {
    id: 'demo-notam-4', notam_number: '01/001', source: 'faa' as const, status: 'expired' as const,
    notam_type: 'NAVAID', title: 'ILS RWY 01 GP OTS FOR MAINT',
    full_text: 'KMTC ILS RWY 01 GLIDEPATH OUT OF SERVICE.',
    effective_start: '2026-01-10T00:00:00Z', effective_end: '2026-01-12T00:00:00Z',
    linked_discrepancy_id: null, created_at: '2026-01-10T00:00:00Z',
  },
]

export const DEMO_CHECKS = [
  {
    id: 'demo-check-1', display_id: 'AC-0098', check_type: 'fod' as const,
    areas: ['RWY 01/19', 'TWY A', 'TWY B'],
    data: {},
    completed_by: 'TSgt Williams', completed_at: new Date().toISOString(),
    latitude: 42.6108, longitude: -82.8371,
    photo_count: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-check-2', display_id: 'AC-0097', check_type: 'bash' as const,
    areas: ['Entire Airfield'],
    data: { condition_code: 'LOW', species_observed: 'Canada geese (4, grazing N side), Red-tailed hawk (1, perched)' },
    completed_by: 'MSgt Proctor', completed_at: new Date().toISOString(),
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-check-3', display_id: 'AC-0096', check_type: 'rcr' as const,
    areas: ['RWY 01/19'],
    data: { rcr_value: '64', condition_type: 'Dry' },
    completed_by: 'SrA Martinez', completed_at: new Date(Date.now() - 86400000).toISOString(),
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: new Date(Date.now() - 86400000).toISOString(), updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-check-4', display_id: 'AC-0095', check_type: 'rsc' as const,
    areas: ['RWY 01/19'],
    data: { condition: 'Wet' },
    completed_by: 'TSgt Williams', completed_at: '2026-02-05T06:30:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-05T06:30:00Z', updated_at: '2026-02-05T06:30:00Z',
  },
  {
    id: 'demo-check-5', display_id: 'AC-0094', check_type: 'ife' as const,
    areas: ['RWY 01/19'],
    data: { aircraft_type: 'KC-135R', callsign: 'BOLT 31', nature: 'Hydraulic failure', actions: ['Notified ATC / Tower', 'Activated crash phone / primary crash net', 'Coordinated with Fire Department / ARFF'], agencies_notified: ['SOF', 'Fire Chief / ARFF', 'ATC / Tower', 'Command Post'] },
    completed_by: 'MSgt Proctor', completed_at: '2026-02-04T14:22:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-04T14:22:00Z', updated_at: '2026-02-04T14:22:00Z',
  },
  {
    id: 'demo-check-6', display_id: 'AC-0093', check_type: 'heavy_aircraft' as const,
    areas: ['RWY 01/19', 'TWY A', 'Apron/Ramp'],
    data: { aircraft_type: 'C-17A Globemaster III' },
    completed_by: 'MSgt Proctor', completed_at: '2026-02-03T18:45:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-03T18:45:00Z', updated_at: '2026-02-03T18:45:00Z',
  },
  {
    id: 'demo-check-7', display_id: 'AC-0092', check_type: 'ground_emergency' as const,
    areas: ['Apron/Ramp'],
    data: { aircraft_type: 'A-10C', nature: 'Hot brakes', actions: ['Notified ATC / Tower', 'Coordinated with Fire Department / ARFF'], agencies_notified: ['Fire Chief / ARFF', 'MOC', 'Wing Safety'] },
    completed_by: 'TSgt Williams', completed_at: '2026-02-02T11:15:00Z',
    latitude: null as number | null, longitude: null as number | null,
    photo_count: 0, created_at: '2026-02-02T11:15:00Z', updated_at: '2026-02-02T11:15:00Z',
  },
]

export const DEMO_INSPECTIONS = [
  {
    id: 'demo-insp-1',
    display_id: 'AI-2026-00A1',
    inspection_type: 'airfield' as const,
    inspector_id: 'demo-user',
    inspector_name: 'MSgt Proctor',
    inspection_date: new Date().toISOString().split('T')[0],
    status: 'completed' as const,
    items: [
      { id: 'af-1', section: 'Section 1 — Obstacle Clearance Criteria', item: "Primary Surface — 1000' from runway centerline", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-2', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Transitional Slope (7:1)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-3', section: 'Section 1 — Obstacle Clearance Criteria', item: "Runway Clear Zones — 3000'L x 3000'W", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-4', section: 'Section 1 — Obstacle Clearance Criteria', item: "Graded Area — 1000'L x 1000'W", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-5', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Approach / Departure Surface (50:1)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-6', section: 'Section 1 — Obstacle Clearance Criteria', item: "Taxiway — 200' from centerline", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-7', section: 'Section 1 — Obstacle Clearance Criteria', item: "Apron — 110' from boundary marking", response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-8', section: 'Section 1 — Obstacle Clearance Criteria', item: 'Construction Areas', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-11', section: 'Section 2 — Signs/Lights', item: 'VFR Holding Positions', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-12', section: 'Section 2 — Signs/Lights', item: 'Instrument Holding Positions', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-13', section: 'Section 2 — Signs/Lights', item: 'Elevation Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-14', section: 'Section 2 — Signs/Lights', item: 'Taxiway Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-15', section: 'Section 2 — Signs/Lights', item: 'Windcone', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-16', section: 'Section 2 — Signs/Lights', item: 'FOD/STOP', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-17', section: 'Section 2 — Signs/Lights', item: 'Runway Signs', response: 'fail' as const, notes: 'Sign #4 reflectivity below minimum', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-18', section: 'Section 2 — Signs/Lights', item: 'NAVAID Ground Receiver Checkpoints', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-19', section: 'Section 2 — Signs/Lights', item: 'Closed Areas', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-20', section: 'Section 3 — Construction', item: 'Parking', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-21', section: 'Section 3 — Construction', item: 'Rules Compliance', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-22', section: 'Section 3 — Construction', item: 'Construction Site Lighting/Marking', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-23', section: 'Section 3 — Construction', item: 'Storage', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-24', section: 'Section 3 — Construction', item: 'Vehicles Lighted/Marked', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-25', section: 'Section 3 — Construction', item: 'FOD Control (Debris/Trash/Vehicle Routes)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-26', section: 'Section 4 — Habitat Management', item: 'Grass Height (7–14")', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-27', section: 'Section 4 — Habitat Management', item: 'Ponding Effects', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-28', section: 'Section 4 — Habitat Management', item: 'Bird/Animal Survey', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-29', section: 'Section 4 — Habitat Management', item: 'Bird Watch Condition (BWC)', response: 'pass' as const, notes: 'LOW', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-30', section: 'Section 5 — Pavement Condition / Markings', item: 'Runway/Overruns 05/23', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-31', section: 'Section 5 — Pavement Condition / Markings', item: 'Taxiways', response: 'fail' as const, notes: 'TWY A/B intersection spall — existing discrepancy D-2026-0042', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-32', section: 'Section 5 — Pavement Condition / Markings', item: 'North & South Hot Pits', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-33', section: 'Section 5 — Pavement Condition / Markings', item: 'Parking Loops', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-34', section: 'Section 5 — Pavement Condition / Markings', item: 'Access Roads / FOD Checks', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-35', section: 'Section 5 — Pavement Condition / Markings', item: 'Grounding Points', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-36', section: 'Section 6 — Airfield Driving', item: 'FOD Control', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-37', section: 'Section 6 — Airfield Driving', item: 'Compliance with Procedures', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-38', section: 'Section 6 — Airfield Driving', item: 'Properly Stowed/Secured Equipment', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-39', section: 'Section 7 — FOD Control', item: 'Runways/Overruns, Taxiways/Shoulders', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-40', section: 'Section 7 — FOD Control', item: 'Parking Aprons', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-41', section: 'Section 7 — FOD Control', item: 'Infield Areas Between Runways/Taxiways', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'af-42', section: 'Section 7 — FOD Control', item: 'Perimeter/Access Roads', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
    ],
    total_items: 42,
    passed_count: 38,
    failed_count: 2,
    na_count: 2,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    bwc_value: 'LOW',
    weather_conditions: 'Clear',
    temperature_f: 28,
    notes: null,
    daily_group_id: 'demo-daily-1',
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-insp-2',
    display_id: 'LI-2026-009F',
    inspection_type: 'lighting' as const,
    inspector_id: 'demo-user',
    inspector_name: 'TSgt Williams',
    inspection_date: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    status: 'completed' as const,
    items: [
      { id: 'lt-1', section: 'Section 1 — Runway 01 Lighting', item: '01/19 Edge Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-2', section: 'Section 1 — Runway 01 Lighting', item: '01 Approach Lighting (SALS)', response: 'fail' as const, notes: 'Stations 7-8 OTS — see D-2026-0041', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-3', section: 'Section 1 — Runway 01 Lighting', item: '01 Threshold Bar / 19 Runway End Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-4', section: 'Section 1 — Runway 01 Lighting', item: '01 PAPI', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-5', section: 'Section 1 — Runway 01 Lighting', item: 'South Hammerhead Edge Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-6', section: 'Section 2 — Runway 19 Lighting', item: '19 Threshold Bar / 01 Runway End Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-7', section: 'Section 2 — Runway 19 Lighting', item: '19 PAPI', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-8', section: 'Section 2 — Runway 19 Lighting', item: '19 REILs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-9', section: 'Section 2 — Runway 19 Lighting', item: 'Intensity Level Check on HIRLs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-10', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY A', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-11', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY K', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-12', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY B', response: 'fail' as const, notes: 'Edge light #14 lens cracked — see D-2026-0038', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-13', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY L', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-14', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY J', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-15', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY E', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-16', section: 'Section 3 — Taxiway/Apron Lighting', item: 'TWY G', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-17', section: 'Section 3 — Taxiway/Apron Lighting', item: 'East Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-18', section: 'Section 3 — Taxiway/Apron Lighting', item: 'West Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-19', section: 'Section 3 — Taxiway/Apron Lighting', item: 'USCG Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-20', section: 'Section 3 — Taxiway/Apron Lighting', item: 'DHS Ramp', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-21', section: 'Section 3 — Taxiway/Apron Lighting', item: 'West Side Stadium Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-22', section: 'Section 3 — Taxiway/Apron Lighting', item: 'East Side Stadium Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-23', section: 'Section 4 — Signs & Markings', item: 'Runway Hold Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-24', section: 'Section 4 — Signs & Markings', item: 'Taxiway Guidance Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-25', section: 'Section 4 — Signs & Markings', item: 'Instrument Hold Signs', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-26', section: 'Section 4 — Signs & Markings', item: '01/19 DRMs (Distance Remaining Markers)', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-27', section: 'Section 4 — Signs & Markings', item: 'NAVAID Checkpoint', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-28', section: 'Section 4 — Signs & Markings', item: 'Marking Retroreflectivity', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-29', section: 'Section 5 — Miscellaneous', item: 'Obstruction Lights', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-30', section: 'Section 5 — Miscellaneous', item: 'Rotating Beacon', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-31', section: 'Section 5 — Miscellaneous', item: 'Wind Cones', response: 'pass' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
      { id: 'lt-32', section: 'Section 5 — Miscellaneous', item: 'Construction Barriers', response: 'na' as const, notes: '', photo_id: null, generated_discrepancy_id: null },
    ],
    total_items: 32,
    passed_count: 29,
    failed_count: 2,
    na_count: 1,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    bwc_value: null,
    weather_conditions: 'Overcast',
    temperature_f: 32,
    notes: 'Night lighting inspection — all systems operational except noted discrepancies.',
    daily_group_id: 'demo-daily-1',
    completed_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'demo-insp-3',
    display_id: 'AI-2026-008E',
    inspection_type: 'airfield' as const,
    inspector_id: 'demo-user',
    inspector_name: 'SrA Martinez',
    inspection_date: new Date(Date.now() - 7 * 86400000).toISOString().split('T')[0],
    status: 'completed' as const,
    items: [],
    total_items: 42,
    passed_count: 42,
    failed_count: 0,
    na_count: 0,
    completion_percent: 100,
    construction_meeting: false,
    joint_monthly: false,
    bwc_value: 'LOW',
    weather_conditions: 'Clear',
    temperature_f: 35,
    notes: 'All items satisfactory. No discrepancies noted.',
    daily_group_id: 'demo-daily-2',
    completed_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
]

export const DEMO_CHECK_COMMENTS = [
  {
    id: 'demo-cc-1', check_id: 'demo-check-1', comment: 'Metal bolt (1/4") found near TWY A intersection — disposed.',
    user_name: 'TSgt Williams', created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-cc-2', check_id: 'demo-check-1', comment: 'Rubber fragment (3") found midfield — disposed. All areas clear.',
    user_name: 'TSgt Williams', created_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-cc-3', check_id: 'demo-check-5', comment: 'Aircraft landed safely RWY 01. Post-landing inspection complete. Runway released to ATC.',
    user_name: 'MSgt Proctor', created_at: '2026-02-04T15:04:00Z',
  },
]
