import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatZuluDateTime } from '@/lib/utils'
import { sanitizePdfText } from '@/lib/pdf-config'
import type { CustomerFeedback } from '@/lib/supabase/feedback'

interface FeedbackPdfInput {
  feedback: CustomerFeedback[]
  stats: {
    total: number
    avgRating: number | null
    ratingCounts: Record<number, number>
    recentCount: number
  }
  windowLabel: string
  baseName?: string
  baseIcao?: string
}

export async function generateFeedbackPdf(input: FeedbackPdfInput): Promise<{ doc: jsPDF; filename: string }> {
  const { feedback, stats, windowLabel, baseName, baseIcao } = input
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = margin

  // ── Header ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text(sanitizePdfText(baseName ? `${baseName.toUpperCase()}${baseIcao ? ` (${baseIcao})` : ''}` : 'AIRFIELD OPERATIONS'), margin, y)
  y += 4
  doc.text('AIRFIELD MANAGEMENT SECTION', margin, y)
  y += 8

  // ── Title ──
  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.text('CUSTOMER FEEDBACK REPORT', margin, y)
  y += 7

  doc.setFontSize(11)
  doc.setTextColor(60)
  doc.text(`Window: ${windowLabel}`, margin, y)
  y += 8

  // ── Info / stats box ──
  doc.setDrawColor(200)
  doc.setFillColor(248, 248, 248)
  doc.roundedRect(margin, y, contentWidth, 24, 2, 2, 'FD')

  const col1 = margin + 4
  const col2 = margin + contentWidth / 3
  const col3 = margin + (contentWidth * 2) / 3

  doc.setFontSize(7)
  doc.setTextColor(120)
  doc.text('Submissions:', col1, y + 5)
  doc.text('Average Rating:', col2, y + 5)
  doc.text('Generated:', col3, y + 5)

  doc.setFontSize(11)
  doc.setTextColor(0)
  doc.text(String(stats.recentCount), col1, y + 12)
  doc.text(stats.avgRating != null ? `${stats.avgRating.toFixed(1)} / 5` : 'N/A', col2, y + 12)
  doc.setFontSize(9)
  doc.text(formatZuluDateTime(new Date()), col3, y + 12)
  y += 28

  // ── Rating distribution ──
  if (stats.avgRating != null && Object.keys(stats.ratingCounts).length > 0) {
    doc.setFontSize(10)
    doc.setTextColor(60)
    doc.text('Rating distribution', margin, y)
    y += 5

    const totalRated = Object.values(stats.ratingCounts).reduce((sum, c) => sum + c, 0)
    const barX = margin + 18
    const barMaxWidth = contentWidth - 40
    const barHeight = 4

    for (const star of [5, 4, 3, 2, 1]) {
      const count = stats.ratingCounts[star] || 0
      const pct = totalRated > 0 ? count / totalRated : 0

      doc.setFontSize(8)
      doc.setTextColor(120)
      doc.text(`${star} star`, margin, y + 3)

      doc.setDrawColor(220)
      doc.setFillColor(235, 235, 235)
      doc.rect(barX, y, barMaxWidth, barHeight, 'FD')

      if (pct > 0) {
        doc.setFillColor(251, 191, 36)
        doc.rect(barX, y, barMaxWidth * pct, barHeight, 'F')
      }

      doc.setTextColor(80)
      doc.text(String(count), barX + barMaxWidth + 4, y + 3)
      y += 6
    }
    y += 4
  }

  // ── Entries table ──
  if (feedback.length === 0) {
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text('No feedback in the selected window.', margin, y)
  } else {
    doc.setFontSize(10)
    doc.setTextColor(60)
    doc.text(`Individual entries (${feedback.length})`, margin, y)
    y += 4

    autoTable(doc, {
      startY: y,
      head: [['Submitted', 'Name', 'Org', 'Rating', 'Comments']],
      body: feedback.map(fb => {
        const responseSummary = Object.entries(fb.responses || {})
          .map(([k, v]) => `${k}: ${String(v)}`)
          .join(' · ')
        const comments = [fb.comments, responseSummary].filter(Boolean).join('\n')
        return [
          formatZuluDateTime(fb.submitted_at),
          sanitizePdfText(fb.name || ''),
          sanitizePdfText(fb.organization || ''),
          fb.overall_rating != null ? `${fb.overall_rating}/5` : '',
          sanitizePdfText(comments),
        ]
      }),
      theme: 'grid',
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 1.5, overflow: 'linebreak' },
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold', fontSize: 7 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        0: { cellWidth: 32 },
        1: { cellWidth: 28 },
        2: { cellWidth: 28 },
        3: { cellWidth: 14, halign: 'center' },
      },
      didDrawPage: () => {
        const total = doc.getNumberOfPages()
        const current = doc.getCurrentPageInfo().pageNumber
        doc.setFontSize(7)
        doc.setTextColor(140)
        doc.text(
          `Generated by Glidepath — ${formatZuluDateTime(new Date())}`,
          margin,
          pageHeight - 8,
        )
        doc.text(`Page ${current} of ${total}`, pageWidth - margin, pageHeight - 8, { align: 'right' })
      },
    })
  }

  const today = new Date().toISOString().slice(0, 10)
  const filename = `customer-feedback-${today}.pdf`
  return { doc, filename }
}
