import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatZuluDateTime, formatZuluDate } from '@/lib/utils'
import { sanitizePdfText } from '@/lib/pdf-config'
import type { PprColumn, PprEntry } from '@/lib/supabase/ppr'

interface PprPdfInput {
  columns: PprColumn[]
  entries: PprEntry[]
  dateFrom: string
  dateTo: string
  baseName?: string | null
  baseIcao?: string | null
}

function formatYesNoNa(v: string): string {
  if (v === 'yes') return 'YES'
  if (v === 'no') return 'NO'
  if (v === 'na') return 'N/A'
  return v || ''
}

function formatCell(col: PprColumn, raw: string): string {
  if (!raw) return ''
  switch (col.column_type) {
    case 'yes_no_na':
      return formatYesNoNa(raw)
    case 'date':
      try { return new Date(raw + 'T00:00:00').toLocaleDateString() } catch { return raw }
    default:
      return raw
  }
}

export async function generatePprPdf(input: PprPdfInput): Promise<{ doc: jsPDF; filename: string }> {
  const { columns, entries, dateFrom, dateTo, baseName, baseIcao } = input

  // Landscape gives us more columns worth of horizontal room
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 12
  const contentWidth = pageWidth - margin * 2
  let y = margin

  // ── Header ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text(sanitizePdfText(baseName ? `${baseName.toUpperCase()}${baseIcao ? ` (${baseIcao})` : ''}` : 'AIRFIELD OPERATIONS'), margin, y)
  y += 4
  doc.text('AIRFIELD MANAGEMENT SECTION', margin, y)
  y += 8

  // ── Title ──
  doc.setFontSize(16)
  doc.setTextColor(0)
  doc.text('PPR LOG', margin, y)
  y += 7

  doc.setFontSize(11)
  doc.setTextColor(60)
  const rangeLabel = dateFrom === dateTo
    ? formatZuluDate(new Date(dateFrom + 'T00:00:00'))
    : `${formatZuluDate(new Date(dateFrom + 'T00:00:00'))} – ${formatZuluDate(new Date(dateTo + 'T00:00:00'))}`
  doc.text(`Arrival date: ${rangeLabel}`, margin, y)
  y += 8

  // ── Info box ──
  doc.setDrawColor(200)
  doc.setFillColor(248, 248, 248)
  doc.roundedRect(margin, y, contentWidth, 16, 2, 2, 'FD')

  doc.setFontSize(7)
  doc.setTextColor(120)
  doc.text('Entries:', margin + 4, y + 5)
  doc.text('Columns:', margin + 60, y + 5)
  doc.text('Generated:', margin + 120, y + 5)

  doc.setFontSize(9)
  doc.setTextColor(0)
  doc.text(String(entries.length), margin + 4, y + 11)
  doc.text(String(columns.length), margin + 60, y + 11)
  doc.text(formatZuluDateTime(new Date()), margin + 120, y + 11)
  y += 22

  // ── Table ──
  if (entries.length === 0) {
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text('No PPR entries for the selected range.', margin, y)
  } else {
    // Build columns: PPR# + Arrival Date + configured columns + Notes
    const head: string[] = ['PPR #', 'Arrival', ...columns.map(c => sanitizePdfText(c.column_name)), 'OI', 'Notes']
    const body: string[][] = entries.map(entry => {
      const row: string[] = [
        entry.ppr_number,
        entry.arrival_date,
        ...columns.map(c => sanitizePdfText(formatCell(c, entry.column_values?.[c.id] || ''))),
        entry.approver_oi || '',
        sanitizePdfText(entry.notes || ''),
      ]
      return row
    })

    autoTable(doc, {
      startY: y,
      head: [head],
      body,
      theme: 'grid',
      margin: { left: margin, right: margin },
      styles: { fontSize: 7, cellPadding: 1.5, overflow: 'linebreak' },
      headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold', fontSize: 7 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didDrawPage: () => {
        // Footer (drawn per page)
        const total = doc.getNumberOfPages()
        const current = doc.getCurrentPageInfo().pageNumber
        doc.setFontSize(7)
        doc.setTextColor(140)
        doc.text(
          `Generated by Glidepath — ${formatZuluDateTime(new Date())}`,
          margin,
          pageHeight - 8,
        )
        doc.text(`Page ${current} of ${total}`, pageWidth - margin, pageHeight - 8, { align: 'right' })
      },
    })
  }

  const filename = `ppr-log-${dateFrom}${dateFrom === dateTo ? '' : '-to-' + dateTo}.pdf`
  return { doc, filename }
}
