import type { QrcStep } from './supabase/types'

export type QrcSeedTemplate = {
  qrc_number: number
  title: string
  notes?: string
  steps: QrcStep[]
  references?: string
  has_scn_form?: boolean
  scn_fields?: Record<string, unknown>
}

export const QRC_SEED_DATA: QrcSeedTemplate[] = [
  {
    qrc_number: 1,
    title: 'IFE/GE (In-Flight/Ground Emergency)',
    notes: 'WARNING: Do not transmit on Secondary Crash Net until directed by the IC or Senior Fire Official.',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of IFE/GE from ATC/Pilot/other source' },
      { id: '2', type: 'checkbox_with_note', label: 'Obtain and record aircraft information', note: 'Type, callsign, tail#, souls on board, fuel remaining, nature of emergency, hazardous cargo, ordnance' },
      { id: '3', type: 'notify_agencies', label: 'Activate Secondary Crash Net (SCN) and notify', agencies: ['Fire Dept / ARFF', 'Security Forces', 'Command Post', 'Medical (Ambulance)', 'Safety', 'MOC/MXG', 'Airfield Management'] },
      { id: '4', type: 'checkbox', label: 'Upgrade/downgrade runway status as required' },
      { id: '5', type: 'checkbox', label: 'Issue NOTAMs as required' },
      { id: '6', type: 'checkbox', label: 'Coordinate with ATC for runway/taxiway closures' },
      { id: '7', type: 'checkbox', label: 'Respond to scene as directed or required' },
      { id: '8', type: 'checkbox', label: 'Document all actions and times in Events Log' },
      { id: '9', type: 'conditional', label: 'If aircraft mishap occurs, transition to QRC-2', cross_ref_qrc: 2 },
      { id: '10', type: 'checkbox', label: 'Coordinate airfield reopening with ATC and Fire' },
      { id: '11', type: 'time_field', label: 'Record time airfield returned to normal operations', field_label: 'Normal Ops Time (Z)' },
    ],
    references: 'AFI 13-204V3, AFMAN 91-203',
    has_scn_form: true,
    scn_fields: {
      fields: [
        { key: 'aircraft_type', label: 'Aircraft Type', type: 'text' },
        { key: 'callsign', label: 'Callsign', type: 'text' },
        { key: 'tail_number', label: 'Tail Number', type: 'text' },
        { key: 'souls_on_board', label: 'Souls on Board', type: 'text' },
        { key: 'fuel_remaining', label: 'Fuel Remaining', type: 'text' },
        { key: 'nature_of_emergency', label: 'Nature of Emergency', type: 'textarea' },
        { key: 'hazardous_cargo', label: 'Hazardous Cargo', type: 'text' },
        { key: 'ordnance', label: 'Ordnance', type: 'text' },
        { key: 'runway_requested', label: 'Runway Requested', type: 'text' },
        { key: 'ern', label: 'ERN', type: 'text' },
      ],
    },
  },
  {
    qrc_number: 2,
    title: 'Aircraft Mishap',
    notes: 'WARNING: Preserve evidence. Do not disturb wreckage unless to save lives or prevent further damage.',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of aircraft mishap' },
      { id: '2', type: 'notify_agencies', label: 'Activate SCN and notify', agencies: ['Fire Dept / ARFF', 'Security Forces', 'Command Post', 'Medical', 'Safety', 'Wing/CC', 'MOC/MXG', 'Chaplain', 'PA/Public Affairs'] },
      { id: '3', type: 'checkbox', label: 'Close affected runway(s) and update airfield status' },
      { id: '4', type: 'checkbox', label: 'Issue NOTAMs for runway/airfield closures' },
      { id: '5', type: 'checkbox', label: 'Coordinate alternate landing options with ATC' },
      { id: '6', type: 'checkbox', label: 'Establish and enforce cordon/perimeter' },
      { id: '7', type: 'checkbox', label: 'Document scene and all actions in Events Log' },
      { id: '8', type: 'checkbox', label: 'Coordinate with Safety for mishap investigation board' },
      { id: '9', type: 'checkbox', label: 'Support recovery operations as directed' },
      { id: '10', type: 'checkbox', label: 'Coordinate airfield reopening with IC and ATC' },
      { id: '11', type: 'time_field', label: 'Record time airfield returned to normal operations', field_label: 'Normal Ops Time (Z)' },
    ],
    references: 'AFI 91-204, AFI 13-204V3',
    has_scn_form: true,
    scn_fields: {
      fields: [
        { key: 'aircraft_type', label: 'Aircraft Type', type: 'text' },
        { key: 'callsign', label: 'Callsign', type: 'text' },
        { key: 'tail_number', label: 'Tail Number', type: 'text' },
        { key: 'location', label: 'Location on Airfield', type: 'text' },
        { key: 'casualties', label: 'Casualties', type: 'text' },
        { key: 'damage_description', label: 'Damage Description', type: 'textarea' },
      ],
    },
  },
  {
    qrc_number: 3,
    title: 'Bird/Wildlife Strike (BASH)',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive report of bird/wildlife strike' },
      { id: '2', type: 'fill_field', label: 'Record aircraft and strike details', field_label: 'Aircraft/Strike Info' },
      { id: '3', type: 'checkbox', label: 'Dispatch to collect bird/wildlife remains if applicable' },
      { id: '4', type: 'checkbox', label: 'Conduct FOD sweep of affected runway/taxiway' },
      { id: '5', type: 'checkbox', label: 'Notify Flight Safety (BASH program manager)' },
      { id: '6', type: 'checkbox', label: 'Complete AF Form 853 (Bird/Wildlife Strike Report)' },
      { id: '7', type: 'checkbox', label: 'Submit remains to Smithsonian Feather Lab if unidentifiable' },
      { id: '8', type: 'checkbox', label: 'Update AHAS (Avian Hazard Advisory System) if required' },
      { id: '9', type: 'checkbox', label: 'Log event in Events Log' },
      { id: '10', type: 'conditional', label: 'If aircraft damage, transition to QRC-1 (IFE/GE)', cross_ref_qrc: 1 },
    ],
    references: 'AFI 91-212, AFPAM 91-212',
  },
  {
    qrc_number: 4,
    title: 'Runway Condition Assessment (RCA/RSC)',
    steps: [
      { id: '1', type: 'checkbox', label: 'Determine need for runway condition assessment' },
      { id: '2', type: 'checkbox', label: 'Coordinate with ATC for runway access' },
      { id: '3', type: 'checkbox', label: 'Conduct visual assessment of runway condition' },
      { id: '4', type: 'checkbox', label: 'Assess each runway third (touchdown, midpoint, rollout)' },
      { id: '5', type: 'fill_field', label: 'Record RSC value', field_label: 'RSC' },
      { id: '6', type: 'fill_field', label: 'Record RCR value (if applicable)', field_label: 'RCR' },
      { id: '7', type: 'checkbox', label: 'Update airfield status board with new RSC/RCR values' },
      { id: '8', type: 'checkbox', label: 'Notify ATC of updated runway condition' },
      { id: '9', type: 'checkbox', label: 'Issue NOTAM if conditions warrant' },
      { id: '10', type: 'checkbox', label: 'Coordinate snow/ice removal with CE if needed' },
      { id: '11', type: 'checkbox', label: 'Log assessment in Events Log' },
    ],
    references: 'UFC 3-260-01, AFI 13-204V3',
  },
  {
    qrc_number: 5,
    title: 'Tornado Warning',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive tornado warning notification' },
      { id: '2', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Fire Dept', 'Command Post', 'Security Forces', 'MOC'] },
      { id: '3', type: 'checkbox', label: 'Update airfield advisory to TORNADO WARNING' },
      { id: '4', type: 'checkbox', label: 'Coordinate with ATC to divert/hold inbound aircraft' },
      { id: '5', type: 'checkbox', label: 'Direct personnel to take shelter' },
      { id: '6', type: 'checkbox', label: 'Secure loose equipment on airfield' },
      { id: '7', type: 'checkbox', label: 'After all clear: conduct airfield damage assessment' },
      { id: '8', type: 'checkbox', label: 'Report damage to Command Post and CE' },
      { id: '9', type: 'checkbox', label: 'Coordinate airfield reopening with ATC' },
      { id: '10', type: 'checkbox', label: 'Issue/cancel NOTAMs as appropriate' },
      { id: '11', type: 'time_field', label: 'Record time warning lifted', field_label: 'Warning Lifted (Z)' },
    ],
    references: 'AFI 10-2501, Installation Emergency Management Plan',
  },
  {
    qrc_number: 6,
    title: 'Severe Weather / Thunderstorm',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive severe weather advisory/warning' },
      { id: '2', type: 'fill_field', label: 'Record weather details', field_label: 'Weather Info' },
      { id: '3', type: 'checkbox', label: 'Update airfield advisory status' },
      { id: '4', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Fire Dept', 'Command Post', 'MOC'] },
      { id: '5', type: 'checkbox', label: 'Coordinate with ATC for flight operations changes' },
      { id: '6', type: 'checkbox', label: 'Monitor lightning within 5 NM — initiate lightning watch/warning' },
      { id: '7', type: 'checkbox', label: 'Halt outdoor operations if lightning within 5 NM' },
      { id: '8', type: 'checkbox', label: 'Conduct post-weather airfield inspection' },
      { id: '9', type: 'checkbox', label: 'Update RSC/RCR if precipitation affects runway' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 15-128, AFI 13-204V3',
  },
  {
    qrc_number: 7,
    title: 'FOD Walk / FOD Sweeper Operations',
    steps: [
      { id: '1', type: 'checkbox', label: 'Determine FOD walk/sweep requirement' },
      { id: '2', type: 'checkbox', label: 'Coordinate with ATC for access to movement area' },
      { id: '3', type: 'fill_field', label: 'Record area(s) to be swept', field_label: 'Area(s)' },
      { id: '4', type: 'checkbox', label: 'Brief participants on safety, boundaries, and procedures' },
      { id: '5', type: 'checkbox', label: 'Conduct FOD walk/sweep' },
      { id: '6', type: 'checkbox', label: 'Collect and document all FOD found' },
      { id: '7', type: 'checkbox', label: 'Log FOD items (type, location, quantity)' },
      { id: '8', type: 'checkbox', label: 'Release area back to ATC' },
      { id: '9', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 21-101, TO 00-25-172',
  },
  {
    qrc_number: 8,
    title: 'Runway/Taxiway Closure',
    steps: [
      { id: '1', type: 'checkbox', label: 'Determine need for runway/taxiway closure' },
      { id: '2', type: 'fill_field', label: 'Record surface being closed', field_label: 'Surface ID' },
      { id: '3', type: 'fill_field', label: 'Record reason for closure', field_label: 'Reason' },
      { id: '4', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Command Post', 'Fire Dept', 'MOC'] },
      { id: '5', type: 'checkbox', label: 'Update airfield status board' },
      { id: '6', type: 'checkbox', label: 'Issue NOTAM for closure' },
      { id: '7', type: 'checkbox', label: 'Place X-markers/barricades if long-term closure' },
      { id: '8', type: 'checkbox', label: 'Monitor and coordinate reopening' },
      { id: '9', type: 'checkbox', label: 'Cancel NOTAM upon reopening' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 13-204V3, FAA Order 7930.2',
  },
  {
    qrc_number: 9,
    title: 'Airfield Lighting Failure',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive report of airfield lighting failure' },
      { id: '2', type: 'fill_field', label: 'Record affected system(s)', field_label: 'Affected System' },
      { id: '3', type: 'checkbox', label: 'Notify ATC of lighting outage' },
      { id: '4', type: 'checkbox', label: 'Issue NOTAM for lighting outage' },
      { id: '5', type: 'checkbox', label: 'Submit work order to CE for repair' },
      { id: '6', type: 'checkbox', label: 'Coordinate with CE on estimated repair time' },
      { id: '7', type: 'checkbox', label: 'Evaluate impact on flight operations (night/IFR)' },
      { id: '8', type: 'checkbox', label: 'Update airfield status if operations restricted' },
      { id: '9', type: 'checkbox', label: 'Cancel NOTAM upon restoration' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 32-1044, UFC 3-535-01',
  },
  {
    qrc_number: 10,
    title: 'NAVAID Outage / Failure',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive report of NAVAID outage' },
      { id: '2', type: 'fill_field', label: 'Record affected NAVAID', field_label: 'NAVAID' },
      { id: '3', type: 'checkbox', label: 'Notify ATC' },
      { id: '4', type: 'checkbox', label: 'Issue NOTAM for NAVAID outage' },
      { id: '5', type: 'checkbox', label: 'Update NAVAID status board' },
      { id: '6', type: 'checkbox', label: 'Coordinate with ATCALS maintenance for repair' },
      { id: '7', type: 'checkbox', label: 'Evaluate impact on instrument approaches' },
      { id: '8', type: 'checkbox', label: 'Cancel NOTAM upon restoration' },
      { id: '9', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 13-204V3, AFMAN 13-204V2',
  },
  {
    qrc_number: 11,
    title: 'Unauthorized Airfield Entry / Incursion',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive report of unauthorized entry on airfield' },
      { id: '2', type: 'fill_field', label: 'Record location and description', field_label: 'Location/Description' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Security Forces', 'Fire Dept', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Coordinate with ATC to halt/reroute traffic if needed' },
      { id: '5', type: 'checkbox', label: 'Respond to scene or direct Security Forces response' },
      { id: '6', type: 'checkbox', label: 'Ensure intruder is removed from movement area' },
      { id: '7', type: 'checkbox', label: 'Conduct airfield check of affected area' },
      { id: '8', type: 'checkbox', label: 'Document incident for runway incursion reporting' },
      { id: '9', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 13-204V3, FAA Order 7050.1',
  },
  {
    qrc_number: 12,
    title: 'Fuel Spill on Airfield',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive report of fuel spill' },
      { id: '2', type: 'fill_field', label: 'Record location and estimated quantity', field_label: 'Location/Quantity' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['Fire Dept', 'CE (Environmental)', 'Safety', 'Bio-Environmental'] },
      { id: '4', type: 'checkbox', label: 'Close affected pavement area' },
      { id: '5', type: 'checkbox', label: 'Coordinate with ATC for traffic rerouting' },
      { id: '6', type: 'checkbox', label: 'Ensure spill containment measures are in place' },
      { id: '7', type: 'checkbox', label: 'Issue NOTAM if movement area affected' },
      { id: '8', type: 'checkbox', label: 'Monitor cleanup operations' },
      { id: '9', type: 'checkbox', label: 'Reopen area after cleanup verified' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 32-7002, Installation Spill Response Plan',
  },
  {
    qrc_number: 13,
    title: 'Barrier Engagement',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of barrier engagement' },
      { id: '2', type: 'fill_field', label: 'Record aircraft and barrier details', field_label: 'Aircraft/Barrier Info' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['Fire Dept / ARFF', 'Security Forces', 'Command Post', 'MOC', 'Safety', 'CE'] },
      { id: '4', type: 'checkbox', label: 'Close affected runway' },
      { id: '5', type: 'checkbox', label: 'Issue NOTAM for runway closure' },
      { id: '6', type: 'checkbox', label: 'Conduct airfield inspection of barrier system and runway' },
      { id: '7', type: 'checkbox', label: 'Coordinate barrier reset with CE' },
      { id: '8', type: 'checkbox', label: 'Coordinate aircraft removal/towing' },
      { id: '9', type: 'checkbox', label: 'Reopen runway after barrier reset and inspection' },
      { id: '10', type: 'checkbox', label: 'Cancel NOTAM upon reopening' },
      { id: '11', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 32-1043, TO 35E2-4-1',
  },
  {
    qrc_number: 14,
    title: 'DV/POTUS Arrival/Departure',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of DV arrival/departure' },
      { id: '2', type: 'fill_field', label: 'Record ETA/ETD and aircraft info', field_label: 'DV Details' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Security Forces', 'Fire Dept', 'Command Post', 'Protocol', 'PA'] },
      { id: '4', type: 'checkbox', label: 'Conduct FOD walk of arrival/departure route' },
      { id: '5', type: 'checkbox', label: 'Ensure airfield lighting systems operational' },
      { id: '6', type: 'checkbox', label: 'Coordinate parking spot and ground support' },
      { id: '7', type: 'checkbox', label: 'Brief all involved agencies on timeline' },
      { id: '8', type: 'checkbox', label: 'Restrict airfield access as directed' },
      { id: '9', type: 'checkbox', label: 'Monitor and support arrival/departure operations' },
      { id: '10', type: 'checkbox', label: 'Return airfield to normal operations' },
      { id: '11', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 34-1201, Installation OPlan',
  },
  {
    qrc_number: 15,
    title: 'Hot Brakes / Hung Ordnance',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of hot brakes or hung ordnance' },
      { id: '2', type: 'fill_field', label: 'Record aircraft type and tail number', field_label: 'Aircraft Info' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['Fire Dept / ARFF', 'MOC/MXG', 'Security Forces', 'EOD (if ordnance)', 'Safety'] },
      { id: '4', type: 'checkbox', label: 'Coordinate safe parking location with ATC' },
      { id: '5', type: 'checkbox', label: 'Establish evacuation zone as required' },
      { id: '6', type: 'checkbox', label: 'Await ARFF assessment/cooldown period' },
      { id: '7', type: 'checkbox', label: 'Coordinate with MXG for maintenance response' },
      { id: '8', type: 'checkbox', label: 'Release aircraft from emergency status when safe' },
      { id: '9', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 21-101, AFI 91-203',
  },
  {
    qrc_number: 16,
    title: 'HAZMAT Incident on Airfield',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of HAZMAT incident' },
      { id: '2', type: 'fill_field', label: 'Record material type and location', field_label: 'HAZMAT Details' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['Fire Dept', 'CE (Environmental)', 'Bio-Environmental', 'Safety', 'Security Forces', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Establish perimeter/evacuation zone' },
      { id: '5', type: 'checkbox', label: 'Close affected airfield area' },
      { id: '6', type: 'checkbox', label: 'Coordinate with ATC for traffic rerouting' },
      { id: '7', type: 'checkbox', label: 'Issue NOTAM if movement area affected' },
      { id: '8', type: 'checkbox', label: 'Support HAZMAT team response' },
      { id: '9', type: 'checkbox', label: 'Reopen area after all-clear from HAZMAT team' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 10-2501, AFMAN 32-7002',
  },
  {
    qrc_number: 17,
    title: 'Active Shooter / Force Protection',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive active threat/force protection notification' },
      { id: '2', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Command Post', 'Fire Dept', 'Security Forces'] },
      { id: '3', type: 'checkbox', label: 'Implement shelter-in-place for airfield personnel' },
      { id: '4', type: 'checkbox', label: 'Close airfield to all operations' },
      { id: '5', type: 'checkbox', label: 'Coordinate with ATC to divert/hold aircraft' },
      { id: '6', type: 'checkbox', label: 'Lock and secure all airfield access points' },
      { id: '7', type: 'checkbox', label: 'Account for all airfield management personnel' },
      { id: '8', type: 'checkbox', label: 'Await all-clear from Security Forces/Command Post' },
      { id: '9', type: 'checkbox', label: 'Conduct airfield sweep before resuming operations' },
      { id: '10', type: 'checkbox', label: 'Coordinate airfield reopening with ATC' },
      { id: '11', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 31-101, Installation FPCON procedures',
  },
  {
    qrc_number: 18,
    title: 'Power Outage / Airfield Systems Failure',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of power outage' },
      { id: '2', type: 'fill_field', label: 'Record affected systems', field_label: 'Affected Systems' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'CE', 'Fire Dept', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Verify generator/UPS backup operation' },
      { id: '5', type: 'checkbox', label: 'Assess impact on airfield lighting and NAVAIDs' },
      { id: '6', type: 'checkbox', label: 'Issue NOTAMs for affected systems' },
      { id: '7', type: 'checkbox', label: 'Coordinate with CE for power restoration' },
      { id: '8', type: 'checkbox', label: 'Update airfield status as needed' },
      { id: '9', type: 'checkbox', label: 'Cancel NOTAMs upon restoration' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'UFC 3-535-01, AFI 32-1044',
  },
  {
    qrc_number: 19,
    title: 'Construction Zone Safety',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of construction activity on/near airfield' },
      { id: '2', type: 'fill_field', label: 'Record location and scope of work', field_label: 'Location/Scope' },
      { id: '3', type: 'checkbox', label: 'Review construction safety plan and NOTAM requirements' },
      { id: '4', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Safety', 'CE'] },
      { id: '5', type: 'checkbox', label: 'Issue NOTAM for construction area' },
      { id: '6', type: 'checkbox', label: 'Verify barricades, markers, and lighting are in place' },
      { id: '7', type: 'checkbox', label: 'Brief contractor on airfield safety requirements' },
      { id: '8', type: 'checkbox', label: 'Monitor construction area during operations' },
      { id: '9', type: 'checkbox', label: 'Conduct post-construction FOD check of area' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'UFC 3-260-01, AFI 13-204V3',
  },
  {
    qrc_number: 20,
    title: 'Disabled Aircraft on Runway/Taxiway',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of disabled aircraft' },
      { id: '2', type: 'fill_field', label: 'Record aircraft location and condition', field_label: 'Aircraft/Location' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Fire Dept', 'MOC/MXG', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Close affected pavement/runway' },
      { id: '5', type: 'checkbox', label: 'Issue NOTAM for closure' },
      { id: '6', type: 'checkbox', label: 'Coordinate aircraft recovery/towing with MXG' },
      { id: '7', type: 'checkbox', label: 'Inspect pavement for damage after aircraft removal' },
      { id: '8', type: 'checkbox', label: 'Reopen area after inspection' },
      { id: '9', type: 'checkbox', label: 'Cancel NOTAM upon reopening' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 21-101, TO 00-80C-1',
  },
  {
    qrc_number: 21,
    title: 'Bomb Threat',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive bomb threat notification' },
      { id: '2', type: 'notify_agencies', label: 'Notify', agencies: ['Security Forces', 'Command Post', 'EOD', 'Fire Dept', 'ATC'] },
      { id: '3', type: 'checkbox', label: 'Close airfield if directed' },
      { id: '4', type: 'checkbox', label: 'Coordinate with ATC to divert/hold aircraft' },
      { id: '5', type: 'checkbox', label: 'Evacuate airfield facilities as directed' },
      { id: '6', type: 'checkbox', label: 'Establish safe perimeter' },
      { id: '7', type: 'checkbox', label: 'Support EOD sweep operations' },
      { id: '8', type: 'checkbox', label: 'Await all-clear from EOD/Security Forces' },
      { id: '9', type: 'checkbox', label: 'Conduct airfield inspection before reopening' },
      { id: '10', type: 'checkbox', label: 'Coordinate reopening with ATC' },
      { id: '11', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 10-2501, AFI 31-101',
  },
  {
    qrc_number: 22,
    title: 'Aeromedical Evacuation (AE) Support',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of AE mission' },
      { id: '2', type: 'fill_field', label: 'Record ETA and aircraft info', field_label: 'AE Details' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Fire Dept', 'Medical', 'Security Forces', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Coordinate parking and ground support' },
      { id: '5', type: 'checkbox', label: 'Ensure ambulance/medical team positioned' },
      { id: '6', type: 'checkbox', label: 'Coordinate airfield access for medical vehicles' },
      { id: '7', type: 'checkbox', label: 'Monitor operations and provide support' },
      { id: '8', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 41-301, AFI 13-204V3',
  },
  {
    qrc_number: 23,
    title: 'Airfield Inspection (Daily/Weekly/Special)',
    steps: [
      { id: '1', type: 'checkbox', label: 'Determine inspection type and scope' },
      { id: '2', type: 'checkbox', label: 'Coordinate with ATC for airfield access' },
      { id: '3', type: 'checkbox', label: 'Conduct visual inspection of all movement areas' },
      { id: '4', type: 'checkbox', label: 'Check pavement condition, markings, and signage' },
      { id: '5', type: 'checkbox', label: 'Inspect airfield lighting systems' },
      { id: '6', type: 'checkbox', label: 'Check drainage and grade areas' },
      { id: '7', type: 'checkbox', label: 'Document all discrepancies found' },
      { id: '8', type: 'checkbox', label: 'Submit work orders for discrepancies to CE' },
      { id: '9', type: 'checkbox', label: 'File inspection in Glidepath' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 13-204V3, UFC 3-260-01',
  },
  {
    qrc_number: 24,
    title: 'FPCON Change',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive FPCON change directive' },
      { id: '2', type: 'fill_field', label: 'Record new FPCON level', field_label: 'FPCON Level' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Security Forces', 'Fire Dept', 'Command Post'] },
      { id: '4', type: 'checkbox', label: 'Implement airfield-specific FPCON measures' },
      { id: '5', type: 'checkbox', label: 'Increase/decrease airfield access controls per FPCON' },
      { id: '6', type: 'checkbox', label: 'Brief all airfield personnel on new FPCON posture' },
      { id: '7', type: 'checkbox', label: 'Update airfield status/advisory as required' },
      { id: '8', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 10-245, Installation AT/FP Plan',
  },
  {
    qrc_number: 25,
    title: 'Exercises / Surge Operations',
    steps: [
      { id: '1', type: 'checkbox', label: 'Receive notification of exercise/surge operations' },
      { id: '2', type: 'fill_field', label: 'Record exercise name and scope', field_label: 'Exercise Details' },
      { id: '3', type: 'notify_agencies', label: 'Notify', agencies: ['ATC', 'Fire Dept', 'Security Forces', 'Command Post', 'MOC'] },
      { id: '4', type: 'checkbox', label: 'Review and brief airfield operations plan for exercise' },
      { id: '5', type: 'checkbox', label: 'Coordinate increased/modified flight operations with ATC' },
      { id: '6', type: 'checkbox', label: 'Ensure ARFF posture meets surge requirements' },
      { id: '7', type: 'checkbox', label: 'Conduct additional airfield checks as needed' },
      { id: '8', type: 'checkbox', label: 'Monitor FOD conditions during increased operations' },
      { id: '9', type: 'checkbox', label: 'Coordinate return to normal operations' },
      { id: '10', type: 'checkbox', label: 'Log event in Events Log' },
    ],
    references: 'AFI 10-401, Wing OPlan',
  },
]
