import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  createPdf, drawBaseHeader, drawReportTitle, drawStatBox, drawFooter, tableStyles,
} from '@/lib/pdf-utils'
import { formatZuluDateTime } from '@/lib/utils'
import { getMonthlyReviewStatus, STATE_LABEL, type MonthlyReviewState } from '@/lib/qrc/monthly-review-status'
import type { QrcTemplate } from '@/lib/supabase/types'
import type { QrcMonthlyReviewWithUser, EligibleReviewer } from '@/lib/supabase/qrc-reviews'

export interface QrcMonthlyReviewPdfInput {
  baseName?: string | null
  baseIcao?: string | null
  /** Calendar month + year the report covers. Filename + cover header. */
  month: number  // 1–12
  year: number
  templates: QrcTemplate[]
  eligibleUsers: EligibleReviewer[]
  /**
   * Every review row at the base ≥ start of the report month. The generator
   * filters to the [monthStart, monthEnd) window itself so callers can hand
   * in a wider window without rework.
   */
  reviews: QrcMonthlyReviewWithUser[]
  /** Generator attribution — rank + name string. */
  generatedBy?: string | null
}

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
]

// Brand-aligned RGB tuples for status pills in the table.
const STATE_COLOR: Record<MonthlyReviewState, [number, number, number]> = {
  current: [34, 139, 64],   // green
  updated: [217, 119, 6],   // amber
  overdue: [200, 0, 0],     // red
  never:   [200, 0, 0],     // red
}

export async function generateQrcMonthlyReviewPdf(
  input: QrcMonthlyReviewPdfInput,
): Promise<{ doc: jsPDF; filename: string }> {
  const { baseName, baseIcao, month, year, templates, eligibleUsers, reviews, generatedBy } = input

  const ctx = createPdf({ orientation: 'portrait', format: 'letter' })
  const { doc, margin, pageHeight } = ctx

  // ── Window the reviews to the requested calendar month ──
  const monthStart = new Date(Date.UTC(year, month - 1, 1)).getTime()
  const monthEnd = new Date(Date.UTC(year, month, 1)).getTime()
  const reviewsInWindow = reviews.filter(r => {
    const t = new Date(r.reviewed_at).getTime()
    return t >= monthStart && t < monthEnd
  })

  // ── Per-(user, template) latest review IN WINDOW ──
  // Used to render the per-operator detail tables. Sort by reviewed_at DESC
  // (already DESC from the fetch) and collapse.
  const latestByUserTemplate = new Map<string, QrcMonthlyReviewWithUser>()
  for (const r of reviewsInWindow) {
    const k = `${r.user_id}|${r.template_id}`
    if (!latestByUserTemplate.has(k)) latestByUserTemplate.set(k, r)
  }

  // Active templates — reviews against inactive templates still appear, but
  // the per-operator tables list every active template (so gaps are visible).
  const activeTemplates = templates
    .filter(t => t.is_active)
    .sort((a, b) => a.qrc_number - b.qrc_number)

  // ── Per-operator stats for the cover roll-up ──
  const stats = eligibleUsers.map(u => {
    let reviewedCount = 0
    let pendingCount = 0
    for (const tmpl of activeTemplates) {
      const r = latestByUserTemplate.get(`${u.user_id}|${tmpl.id}`)
      const status = getMonthlyReviewStatus(tmpl, r ?? null)
      if (status.state === 'current' || status.state === 'updated') reviewedCount++
      else pendingCount++
    }
    const compliance = activeTemplates.length > 0
      ? Math.round((reviewedCount / activeTemplates.length) * 100)
      : 0
    return { user: u, reviewedCount, pendingCount, compliance }
  })

  const fullyCurrent = stats.filter(s => s.pendingCount === 0).length
  const qrcsWithGap = activeTemplates.filter(tmpl =>
    eligibleUsers.some(u => {
      const r = latestByUserTemplate.get(`${u.user_id}|${tmpl.id}`)
      const s = getMonthlyReviewStatus(tmpl, r ?? null)
      return s.state === 'overdue' || s.state === 'never'
    }),
  ).length

  // ─────────────────────────────────────────────────────────
  // COVER PAGE
  // ─────────────────────────────────────────────────────────
  let y = margin
  y = drawBaseHeader(ctx, y, { baseName, baseIcao })
  y = drawReportTitle(ctx, y, {
    title: 'AMOPS Monthly QRC Review',
    subtitle: `Compliance Report — ${MONTH_NAMES[month - 1]} ${year}`,
  })

  y = drawStatBox(ctx, y, [
    { label: 'OPERATORS FULLY CURRENT', value: `${fullyCurrent} of ${eligibleUsers.length}` },
    { label: 'QRCs WITH GAPS', value: String(qrcsWithGap) },
    { label: 'ACTIVE TEMPLATES', value: String(activeTemplates.length) },
    { label: 'GENERATED', value: formatZuluDateTime(new Date()) },
  ])

  if (generatedBy) {
    doc.setFontSize(8)
    doc.setTextColor(100)
    doc.text(`Generated by: ${generatedBy}`, margin, y)
    y += 6
  }

  // Cover roll-up table
  doc.setFontSize(10)
  doc.setTextColor(0)
  doc.text('Operator Roll-Up', margin, y)
  y += 4

  autoTable(doc, {
    startY: y,
    head: [['Rank', 'Name', 'Role', 'Reviewed', 'Pending', 'Compliance']],
    body: stats.length === 0
      ? [['—', '(no AMOPS-eligible operators at this base)', '', '', '', '']]
      : stats.map(s => [
          s.user.rank ?? '',
          s.user.name,
          formatRole(s.user.role),
          String(s.reviewedCount),
          String(s.pendingCount),
          `${s.compliance}%`,
        ]),
    ...tableStyles(ctx),
    columnStyles: {
      0: { cellWidth: 18 },
      3: { cellWidth: 22, halign: 'center' },
      4: { cellWidth: 22, halign: 'center' },
      5: { cellWidth: 28, halign: 'center', fontStyle: 'bold' },
    },
    didParseCell: data => {
      // Color the compliance % cell by tier.
      if (data.section === 'body' && data.column.index === 5 && stats[data.row.index]) {
        const c = stats[data.row.index].compliance
        if (c === 100) data.cell.styles.textColor = STATE_COLOR.current
        else if (c >= 70) data.cell.styles.textColor = STATE_COLOR.updated
        else data.cell.styles.textColor = STATE_COLOR.overdue
      }
    },
  })

  // ─────────────────────────────────────────────────────────
  // PER-OPERATOR DETAIL PAGES — one section per eligible user
  // ─────────────────────────────────────────────────────────
  for (let i = 0; i < eligibleUsers.length; i++) {
    const u = eligibleUsers[i]
    doc.addPage()
    y = margin
    y = drawBaseHeader(ctx, y, { baseName, baseIcao })

    // Section header
    doc.setFontSize(13)
    doc.setTextColor(0)
    doc.setFont('helvetica', 'bold')
    const headerLine = u.rank ? `${u.rank} ${u.name}` : u.name
    doc.text(headerLine, margin, y)
    doc.setFont('helvetica', 'normal')
    y += 6
    doc.setFontSize(9)
    doc.setTextColor(100)
    const meta: string[] = [formatRole(u.role)]
    if (u.operating_initials) meta.push(`OI: ${u.operating_initials}`)
    doc.text(meta.join(' · '), margin, y)
    y += 8

    const stat = stats.find(s => s.user.user_id === u.user_id)
    if (stat) {
      y = drawStatBox(ctx, y, [
        { label: 'REVIEWED', value: `${stat.reviewedCount} of ${activeTemplates.length}` },
        { label: 'PENDING', value: String(stat.pendingCount) },
        { label: 'COMPLIANCE', value: `${stat.compliance}%` },
      ])
    }

    // Per-template table
    autoTable(doc, {
      startY: y,
      head: [['#', 'Title', 'Status', 'Last reviewed', 'Notes']],
      body: activeTemplates.map(tmpl => {
        const r = latestByUserTemplate.get(`${u.user_id}|${tmpl.id}`)
        const status = getMonthlyReviewStatus(tmpl, r ?? null)
        const lastReviewed = status.reviewedAt
          ? new Date(status.reviewedAt).toISOString().slice(0, 10)
          : '—'
        return [
          String(tmpl.qrc_number),
          tmpl.title,
          STATE_LABEL[status.state],
          lastReviewed,
          (r?.notes || '').slice(0, 80),
        ]
      }),
      ...tableStyles(ctx),
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        2: { cellWidth: 32, halign: 'center', fontStyle: 'bold' },
        3: { cellWidth: 26, halign: 'center' },
      },
      didParseCell: data => {
        if (data.section === 'body' && data.column.index === 2) {
          const tmpl = activeTemplates[data.row.index]
          if (!tmpl) return
          const r = latestByUserTemplate.get(`${u.user_id}|${tmpl.id}`)
          const s = getMonthlyReviewStatus(tmpl, r ?? null)
          data.cell.styles.textColor = STATE_COLOR[s.state]
        }
      },
    })

    // Operator signature line at the bottom of the page
    const finalY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y
    let sigY = finalY + 16
    if (sigY > pageHeight - 40) sigY = pageHeight - 40
    doc.setDrawColor(150)
    doc.line(margin, sigY, margin + 90, sigY)
    doc.setFontSize(8)
    doc.setTextColor(120)
    doc.text('Operator signature', margin, sigY + 4)
    doc.line(margin + 110, sigY, margin + 170, sigY)
    doc.text('Date', margin + 110, sigY + 4)
  }

  // ─────────────────────────────────────────────────────────
  // FOOTER on every page
  // ─────────────────────────────────────────────────────────
  const total = doc.getNumberOfPages()
  for (let p = 1; p <= total; p++) {
    doc.setPage(p)
    drawFooter(ctx)
  }

  const monthSlug = `${year}-${String(month).padStart(2, '0')}`
  const baseSlug = (baseIcao || baseName || 'base').toString().toLowerCase().replace(/\s+/g, '-')
  const filename = `qrc-monthly-review-${baseSlug}-${monthSlug}.pdf`

  return { doc, filename }
}

function formatRole(role: string): string {
  switch (role) {
    case 'airfield_manager': return 'Airfield Manager'
    case 'namo': return 'NAMO'
    case 'amops': return 'AMOPS'
    default: return role
  }
}
