// AOMS Regulation Database — 78 Total Entries
// 3 Core + 32 Direct Refs + 29 Cross-Refs + 15 Scrubbed from Vols 1–3
// Generated February 18, 2026 | Source: AOMS_Regulation_Database_v4
//
// Used as demo/seed data until Supabase is connected.
// Each entry matches the RegulationRow type from lib/supabase/regulations.ts

export type RegulationEntry = {
  reg_id: string
  title: string
  description: string
  publication_date: string | null
  url: string | null
  source_section: string
  source_volume: string | null
  category: string
  pub_type: string
  is_core: boolean
  is_cross_ref: boolean
  is_scrubbed: boolean
  tags: string[]
}

// ═══════════════════════════════════════════════════════════════════
// CORE PUBLICATIONS — The Airfield Management Bibles (3)
// ═══════════════════════════════════════════════════════════════════

const CORE_PUBLICATIONS: RegulationEntry[] = [
  {
    reg_id: 'DAFMAN 13-204, Vol. 1',
    title: 'Management of Airfield Operations',
    description: 'The foundational DAF manual for airfield operations management. Defines AOF organization, commander responsibilities, AO Compliance Verification (AO-CV), airfield waiver processes, and MAJCOM oversight. Implements AFPD 13-2.',
    publication_date: '22 Jul 2020',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafman13-204v1/dafman13-204v1.pdf',
    source_section: 'core',
    source_volume: null,
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: true,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['AOF', 'AO-CV', 'AFPD 13-2', 'airfield operations', 'commander responsibilities', 'waiver'],
  },
  {
    reg_id: 'DAFMAN 13-204, Vol. 2',
    title: 'Airfield Management',
    description: 'The primary manual for airfield management (AM) operations. Covers AM duties and qualifications, airfield inspections, NOTAM procedures, flight plan processing, airfield driving programs, transient aircraft services, and local procedures.',
    publication_date: '20 Sep 2024',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafman13-204v2/dafman13-204v2.pdf',
    source_section: 'core',
    source_volume: null,
    category: 'airfield_mgmt',
    pub_type: 'DAF',
    is_core: true,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['AM', 'airfield management', 'NOTAM', 'inspections', 'airfield driving', 'transient aircraft'],
  },
  {
    reg_id: 'DAFMAN 13-204, Vol. 3',
    title: 'Air Traffic Control',
    description: 'The primary manual for DAF air traffic control operations. Covers ATC duties and qualifications, facility ratings, local procedures, ATC training programs, watch supervisor responsibilities, and coordination with FAA JO 7110.65.',
    publication_date: '10 Jun 2020',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafman13-204v3/dafman13-204v3.pdf',
    source_section: 'core',
    source_volume: null,
    category: 'atc',
    pub_type: 'DAF',
    is_core: true,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['ATC', 'air traffic control', 'facility rating', 'watch supervisor', 'JO 7110.65'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION I — References from DAFMAN 13-204, Vol. 1 (6)
// ═══════════════════════════════════════════════════════════════════

const SECTION_I: RegulationEntry[] = [
  {
    reg_id: 'DAFI 90-160',
    title: 'Publications and Forms Management',
    description: 'Procedures for developing and managing DAF publications and forms.',
    publication_date: '14 Apr 2022',
    url: 'https://static.e-publishing.af.mil/production/1/saf_aa/publication/dafi90-160/dafi90-160.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'publications',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['publications', 'forms', 'administrative'],
  },
  {
    reg_id: 'DAFI 90-302',
    title: 'The Inspection System of the DAF',
    description: 'Guidance on AO-CV and general inspection standards.',
    publication_date: '15 Mar 2023',
    url: 'https://static.e-publishing.af.mil/production/1/saf_ig/publication/dafi90-302/dafi90-302.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['AO-CV', 'inspection', 'compliance verification'],
  },
  {
    reg_id: 'DAFMAN 90-161',
    title: 'Publishing Processes and Procedures',
    description: 'Lifecycle and administrative control of official manuals.',
    publication_date: '18 Oct 2023',
    url: 'https://static.e-publishing.af.mil/production/1/saf_aa/publication/dafman90-161/dafman90-161.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'publications',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['publishing', 'manual lifecycle', 'administrative'],
  },
  {
    reg_id: 'AFI 10-1002',
    title: 'Joint Use Agreements for Military and Civilian Flying Facilities',
    description: 'Coordinating airfield usage between DAF and civilian entities.',
    publication_date: '8 Aug 2018',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afi10-1002/afi10-1002.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'international',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['joint use', 'civilian', 'agreement', 'shared airfield'],
  },
  {
    reg_id: 'AFI 10-1801',
    title: 'Foreign Governmental Aircraft Landings at USAF Installations',
    description: 'Policy for authorizing foreign military aircraft arrivals.',
    publication_date: '25 Sep 2018',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afi10-1801/afi10-1801.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'international',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['foreign aircraft', 'landing permits', 'international'],
  },
  {
    reg_id: 'AFI 38-402',
    title: 'Airmen Powered by Innovation',
    description: 'Program for submitting innovative process improvements.',
    publication_date: '8 Feb 2018',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi38-402/afi38-402.pdf',
    source_section: 'I',
    source_volume: 'Vol. 1',
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['innovation', 'process improvement'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION II — References from DAFMAN 13-204, Vol. 2 (6)
// ═══════════════════════════════════════════════════════════════════

const SECTION_II: RegulationEntry[] = [
  {
    reg_id: '14 CFR Part 139',
    title: 'Certification of Airports',
    description: 'FAA standards for airport safety, firefighting, and emergency planning at joint-use airfields.',
    publication_date: '12 Feb 2026',
    url: 'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-139',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'safety',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['Part 139', 'airport certification', 'ARFF', 'emergency planning', 'joint-use'],
  },
  {
    reg_id: 'AFI 90-201',
    title: 'The Air Force Inspection System',
    description: 'Wing inspections and the Management Internal Control Toolset (MICT).',
    publication_date: '21 Jul 2023',
    url: 'https://static.e-publishing.af.mil/production/1/saf_ig/publication/afi90-201/afi90-201.pdf',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['inspection system', 'MICT', 'wing inspection'],
  },
  {
    reg_id: 'AFI 10-1001',
    title: 'Civil Aircraft Landing Permits',
    description: 'Issuing landing permits and processing civilian aircraft fees.',
    publication_date: '23 Aug 2018',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afi10-1001/afi10-1001.pdf',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'international',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['civil aircraft', 'landing permits', 'fees'],
  },
  {
    reg_id: 'AFI 10-2501',
    title: 'Air Force Emergency Management Program',
    description: 'All-hazards response to airfield mishaps and disasters.',
    publication_date: '10 Mar 2020',
    url: 'https://static.e-publishing.af.mil/production/1/af_a4/publication/afi10-2501/afi10-2501.pdf',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'emergency',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['emergency management', 'all-hazards', 'disaster response', 'mishap'],
  },
  {
    reg_id: 'AFH 32-7084',
    title: 'AICUZ Program Manager\'s Guide',
    description: 'Air Installations Compatible Use Zones; land use and noise management.',
    publication_date: '2 Nov 2017',
    url: 'https://static.e-publishing.af.mil/production/1/af_a4/publication/afh32-7084/afh32-7084.pdf',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'airfield_design',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['AICUZ', 'land use', 'noise', 'compatible use zones'],
  },
  {
    reg_id: 'AFMAN 32-1084',
    title: 'Facility Requirements',
    description: 'Space allocations for airfield buildings and hangars.',
    publication_date: '26 Feb 2016',
    url: 'https://static.e-publishing.af.mil/production/1/af_a4/publication/afman32-1084/afman32-1084.pdf',
    source_section: 'II',
    source_volume: 'Vol. 2',
    category: 'construction',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['facility requirements', 'space allocation', 'hangars', 'buildings'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION III — References from DAFMAN 13-204, Vol. 3 (5)
// ═══════════════════════════════════════════════════════════════════

const SECTION_III: RegulationEntry[] = [
  {
    reg_id: 'FAA Order JO 7210.3',
    title: 'Facility Operation and Administration',
    description: 'Administration of air traffic control facilities.',
    publication_date: '22 Jan 2026',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1040564',
    source_section: 'III',
    source_volume: 'Vol. 3',
    category: 'atc',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['ATC facility', 'administration', 'JO 7210.3'],
  },
  {
    reg_id: 'FAA Order JO 7110.10',
    title: 'Flight Services',
    description: 'Flight service personnel briefings and radio contact.',
    publication_date: '22 Jan 2026',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1040566',
    source_section: 'III',
    source_volume: 'Vol. 3',
    category: 'atc',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['flight services', 'briefings', 'radio contact', 'JO 7110.10'],
  },
  {
    reg_id: 'FAA Order JO 1900.47',
    title: 'ATC Operational Readiness and Contingency Planning',
    description: 'ATC facility management during emergencies or disruptions.',
    publication_date: '30 Apr 2024',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1042413',
    source_section: 'III',
    source_volume: 'Vol. 3',
    category: 'emergency',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['ATC contingency', 'operational readiness', 'emergency', 'JO 1900.47'],
  },
  {
    reg_id: 'AFI 17-221',
    title: 'Spectrum Interference Resolution Program',
    description: 'Resolving radio interference affecting ATC communications.',
    publication_date: '11 May 2018',
    url: 'https://static.e-publishing.af.mil/production/1/saf_cn/publication/afi17-221/afi17-221.pdf',
    source_section: 'III',
    source_volume: 'Vol. 3',
    category: 'atc',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['spectrum', 'radio interference', 'communications', 'ATC'],
  },
  {
    reg_id: 'AFI 33-322',
    title: 'Records Management and Information Governance',
    description: 'Official logs, recorded radio data, and historical files.',
    publication_date: '6 Mar 2020',
    url: 'https://static.e-publishing.af.mil/production/1/saf_cn/publication/afi33-322/afi33-322.pdf',
    source_section: 'III',
    source_volume: 'Vol. 3',
    category: 'publications',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['records management', 'radio recordings', 'logs', 'information governance'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION IV — References from UFC 3-260-01 (9)
// ═══════════════════════════════════════════════════════════════════

const SECTION_IV: RegulationEntry[] = [
  {
    reg_id: 'UFC 1-200-01',
    title: 'DoD Building Code',
    description: 'Overarching criteria for all DoD facility construction and modernization.',
    publication_date: '17 Dec 2024',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_1_200_01_2022_c4.pdf',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'construction',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['building code', 'DoD construction', 'modernization'],
  },
  {
    reg_id: 'UFC 3-201-01',
    title: 'Civil Engineering',
    description: 'Site development, grading, and storm drainage.',
    publication_date: '20 Dec 2022',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_201_01_2022.pdf',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'construction',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['civil engineering', 'site development', 'grading', 'drainage'],
  },
  {
    reg_id: 'UFC 3-260-16',
    title: 'Airfield Pavement Condition Surveys',
    description: 'PCI surveys and identifying pavement distress.',
    publication_date: '3 Feb 2019',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_260_16_2019.pdf',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'pavement',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['PCI', 'pavement condition', 'survey', 'distress'],
  },
  {
    reg_id: 'FAA AC 150/5300-13',
    title: 'Airport Design',
    description: 'Primary civilian standard for airfield geometry and runway layout.',
    publication_date: 'Current Ed.',
    url: 'https://www.faa.gov/airports/resources/advisory_circulars/index.cfm/go/document.current/documentNumber/150_5300-13',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'airfield_design',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['airport design', 'runway layout', 'geometry', 'AC 150/5300-13'],
  },
  {
    reg_id: 'FAA Order 8260.3',
    title: 'US Standard for TERPS',
    description: 'Criteria for instrument approach and departure procedures.',
    publication_date: 'Current Ed.',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1029737',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'atc',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['TERPS', 'instrument approach', 'departure procedures', '8260.3'],
  },
  {
    reg_id: 'NFPA 780',
    title: 'Lightning Protection Systems',
    description: 'Protecting airfield facilities and aircraft parking spots.',
    publication_date: '2017 Ed.',
    url: 'https://www.nfpa.org/codes-and-standards/nfpa-780-standard-for-the-installation-of-lightning-protection-systems',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'safety',
    pub_type: 'NFPA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['lightning protection', 'NFPA', 'aircraft parking'],
  },
  {
    reg_id: 'NFPA 415',
    title: 'Airport Terminal Buildings',
    description: 'Fire protection for fueling ramps and passenger boarding areas.',
    publication_date: '2016 Ed.',
    url: 'https://www.nfpa.org/codes-and-standards/nfpa-415-standard-on-airport-terminal-buildings-fueling-ramp-drainage-and-loading-walkways',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'fueling',
    pub_type: 'NFPA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['fire protection', 'fueling ramps', 'terminal buildings', 'NFPA'],
  },
  {
    reg_id: 'MIL-STD 3007',
    title: 'UFC Format and Standard',
    description: 'How technical criteria are updated across tri-services.',
    publication_date: '13 Dec 2019',
    url: 'https://www.wbdg.org/FFC/FEDMIL/milstd3007g.pdf',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'construction',
    pub_type: 'DoD',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['MIL-STD', 'UFC format', 'tri-service', 'technical criteria'],
  },
  {
    reg_id: 'ICAO Annex 14',
    title: 'Aerodromes - Vol. I',
    description: 'International aerodrome design and operations standards.',
    publication_date: 'Jul 2022',
    url: 'https://store.icao.int/en/annex-14-aerodromes-volume-i-aerodrome-design-and-operations',
    source_section: 'IV',
    source_volume: 'UFC 3-260-01',
    category: 'airfield_design',
    pub_type: 'ICAO',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['ICAO', 'aerodrome', 'international standards', 'Annex 14'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION V — Additional Airfield Systems Publications (5)
// ═══════════════════════════════════════════════════════════════════

const SECTION_V: RegulationEntry[] = [
  {
    reg_id: 'UFC 3-260-17',
    title: 'Dust Control for Roads and Airfields',
    description: 'Stabilizing unpaved surfaces to prevent FOD and engine damage.',
    publication_date: '26 Apr 2023',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_260_17_2018_c1.pdf',
    source_section: 'V',
    source_volume: null,
    category: 'pavement',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['dust control', 'FOD prevention', 'unpaved surfaces', 'engine damage'],
  },
  {
    reg_id: 'UFC 3-270-01',
    title: 'Pavement Maintenance and Repair',
    description: 'Asphalt spall repair and joint sealing.',
    publication_date: '17 Mar 2022',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_270_01_2018_c1.pdf',
    source_section: 'V',
    source_volume: null,
    category: 'pavement',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['pavement maintenance', 'spall repair', 'joint sealing', 'asphalt'],
  },
  {
    reg_id: 'UFC 3-270-08',
    title: 'Pavement Management',
    description: 'Long-term airfield pavement lifecycle planning.',
    publication_date: '19 Jan 2024',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_270_08_2024.pdf',
    source_section: 'V',
    source_volume: null,
    category: 'pavement',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['pavement management', 'lifecycle planning', 'long-term'],
  },
  {
    reg_id: 'UFC 4-211-01',
    title: 'Aircraft Maintenance Hangars',
    description: 'Structural and safety requirements for maintenance bays.',
    publication_date: '1 Oct 2024',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_4_211_01_2017_c3.pdf',
    source_section: 'V',
    source_volume: null,
    category: 'construction',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['hangars', 'maintenance bays', 'structural requirements'],
  },
  {
    reg_id: 'IEEE 142',
    title: 'Grounding of Industrial Power Systems',
    description: 'Electrical grounding systems for the flightline.',
    publication_date: '2007 Ed.',
    url: 'https://standards.ieee.org/ieee/142/4669/',
    source_section: 'V',
    source_volume: null,
    category: 'lighting',
    pub_type: 'IEEE',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: false,
    tags: ['grounding', 'electrical', 'flightline', 'IEEE', 'power systems'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VI-A — DAF Cross-Referenced Publications (15)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VI_A: RegulationEntry[] = [
  {
    reg_id: 'AFPD 13-2',
    title: 'Air Traffic Control, Airfield, Airspace, and Range Management',
    description: 'Parent policy directive implemented by DAFMAN 13-204 (all volumes). Establishes DAF policy for ATC and airfield ops.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afpd13-2/afpd13-2.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['AFPD', 'parent directive', 'ATC policy', 'airfield policy'],
  },
  {
    reg_id: 'DAFI 13-213',
    title: 'Airfield Driving',
    description: 'Procedures for safe vehicle operation on the airfield; licensing, training, and vehicle identification.',
    publication_date: '4 Feb 2020',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafi13-213/dafi13-213.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'driving',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['airfield driving', 'vehicle operations', 'licensing', 'training'],
  },
  {
    reg_id: 'DAFMAN 13-217',
    title: 'Drop Zone and Landing Zone Operations',
    description: 'Standards for establishing, surveying, and managing drop zones and landing zones for tactical airlift.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafman13-217/dafman13-217.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['drop zone', 'landing zone', 'DZ', 'LZ', 'tactical airlift'],
  },
  {
    reg_id: 'DAFI 91-212',
    title: 'Bird/Wildlife Aircraft Strike Hazard (BASH) Management Program',
    description: 'DAF-wide guidance for reducing bird and wildlife strike risks. Coordinates with 14 CFR 139.337.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_se/publication/dafi91-212/dafi91-212.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'bash_wildlife',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['BASH', 'bird strike', 'wildlife', 'hazard management'],
  },
  {
    reg_id: 'DAFI 91-202',
    title: 'DAF Mishap Prevention Program',
    description: 'DAF safety program including airfield mishap reporting, risk management, and safety investigation.',
    publication_date: '12 Mar 2020',
    url: 'https://static.e-publishing.af.mil/production/1/af_se/publication/dafi91-202/dafi91-202.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'safety',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['mishap prevention', 'risk management', 'safety investigation'],
  },
  {
    reg_id: 'DAFI 91-204',
    title: 'Safety Investigations and Reports',
    description: 'Investigating and reporting DAF mishaps including airfield and flight-related incidents.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_se/publication/dafi91-204/dafi91-204.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'safety',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['safety investigation', 'mishap reports', 'incident reporting'],
  },
  {
    reg_id: 'DAFMAN 91-203',
    title: 'Air Force Occupational Safety, Fire, and Health Standards',
    description: 'Occupational safety standards for airfield maintenance, ARFF, and flightline operations.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_se/publication/dafman91-203/dafman91-203.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'safety',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['occupational safety', 'fire', 'ARFF', 'flightline', 'health standards'],
  },
  {
    reg_id: 'AFI 33-332',
    title: 'Air Force Privacy and Civil Liberties Program',
    description: 'Privacy Act compliance for ATC recordings, personnel data, and airfield ops records.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/saf_cn/publication/afi33-332/afi33-332.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'publications',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['privacy', 'civil liberties', 'ATC recordings', 'personnel data'],
  },
  {
    reg_id: 'AFI 36-2101',
    title: 'Classifying Military Personnel (Officer and Enlisted)',
    description: 'AFSC management for 13MX, 1C1X1 (ATC), 1C7X1 (AM), 1C8X3 (RAWS) career fields.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-2101/afi36-2101.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['AFSC', 'personnel classification', '1C1X1', '1C7X1', '1C8X3', '13MX'],
  },
  {
    reg_id: 'AFI 36-2670',
    title: 'Total Force Development',
    description: 'Training, education, and professional development for airfield operations career fields.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-2670/afi36-2670.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['training', 'education', 'professional development', 'total force'],
  },
  {
    reg_id: 'AFI 38-201',
    title: 'Management of Manpower Requirements and Authorizations',
    description: 'Manpower requirements determination for AOF staffing levels.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi38-201/afi38-201.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'financial',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['manpower', 'staffing', 'AOF', 'authorizations'],
  },
  {
    reg_id: 'AFH 36-2618',
    title: 'The Enlisted Force Structure',
    description: 'Enlisted ranks, duties, and leadership responsibilities for ATC and AM personnel.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afh36-2618/afh36-2618.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['enlisted', 'force structure', 'leadership', 'ATC', 'AM'],
  },
  {
    reg_id: 'AFI 32-1041',
    title: 'Pavement Evaluation Management',
    description: 'Evaluating airfield pavement structural capacity; supports weight-bearing decisions.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a4/publication/afi32-1041/afi32-1041.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'pavement',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['pavement evaluation', 'structural capacity', 'weight-bearing'],
  },
  {
    reg_id: 'AFMAN 11-230',
    title: 'Instrument Procedures',
    description: 'Instrument approach/departure procedures managed by TERPS specialists within the AOF.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afman11-230/afman11-230.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'atc',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['instrument procedures', 'TERPS', 'approach', 'departure'],
  },
  {
    reg_id: 'AFMAN 11-202 Vol 3',
    title: 'General Flight Rules',
    description: 'General USAF flight rules; intersects with ATC procedures in DAFMAN 13-204 Vol 3.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afman11-202v3/afman11-202v3.pdf',
    source_section: 'VI-A',
    source_volume: null,
    category: 'atc',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['flight rules', 'USAF', 'ATC procedures', 'general flight'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VI-B — FAA / DOT / NTSB Federal Regulations (8)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VI_B: RegulationEntry[] = [
  {
    reg_id: 'FAA JO 7110.65',
    title: 'Air Traffic Control',
    description: 'Primary FAA order for ATC procedures, phraseology, and separation standards. Core reference for Vol 3.',
    publication_date: 'Current Ed.',
    url: 'https://www.faa.gov/air_traffic/publications/atpubs/atc_html/',
    source_section: 'VI-B',
    source_volume: null,
    category: 'atc',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['ATC', '7110.65', 'phraseology', 'separation standards', 'procedures'],
  },
  {
    reg_id: '14 CFR Part 77',
    title: 'Safe, Efficient Use, and Preservation of the Navigable Airspace',
    description: 'FAA obstruction evaluation standards; defines imaginary surfaces for airfield planning.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-E/part-77',
    source_section: 'VI-B',
    source_volume: null,
    category: 'airfield_design',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['Part 77', 'obstruction evaluation', 'imaginary surfaces', 'navigable airspace'],
  },
  {
    reg_id: '14 CFR Part 121',
    title: 'Operating Requirements: Domestic, Flag, and Supplemental Operations',
    description: 'Air carrier operational standards referenced by 14 CFR Part 139 for airport certification.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-121',
    source_section: 'VI-B',
    source_volume: null,
    category: 'safety',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['Part 121', 'air carrier', 'operations', 'certification'],
  },
  {
    reg_id: '14 CFR Part 380',
    title: 'Public Charters',
    description: 'Public charter operations regulations referenced in 14 CFR Part 139 applicability.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-14/chapter-II/subchapter-D/part-380',
    source_section: 'VI-B',
    source_volume: null,
    category: 'international',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['Part 380', 'public charters', 'charter operations'],
  },
  {
    reg_id: '14 CFR Part 5',
    title: 'Safety Management Systems',
    description: 'FAA SMS requirements; referenced in 14 CFR 139 Subpart E for airport-tenant SMS data sharing.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-A/part-5',
    source_section: 'VI-B',
    source_volume: null,
    category: 'safety',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['SMS', 'safety management systems', 'Part 5', 'data sharing'],
  },
  {
    reg_id: '14 CFR Part 11',
    title: 'General Rulemaking Procedures',
    description: 'Procedures for petitioning FAA for exemptions from Part 139 requirements.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-14/chapter-I/subchapter-B/part-11',
    source_section: 'VI-B',
    source_volume: null,
    category: 'publications',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['Part 11', 'rulemaking', 'exemptions', 'petitions'],
  },
  {
    reg_id: '49 CFR 171-180',
    title: 'Hazardous Materials Regulations',
    description: 'DOT hazmat handling/transport; referenced by 14 CFR 139.321 for cargo and fueling safety.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-I/subchapter-C',
    source_section: 'VI-B',
    source_volume: null,
    category: 'fueling',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['hazmat', 'hazardous materials', 'fueling safety', 'cargo', 'DOT'],
  },
  {
    reg_id: '49 CFR 830',
    title: 'NTSB Notification and Reporting',
    description: 'Defines aircraft accidents/incidents; Part 139 references 830.2 for hazard definitions.',
    publication_date: 'Current Ed.',
    url: 'https://www.ecfr.gov/current/title-49/subtitle-B/chapter-VIII/part-830',
    source_section: 'VI-B',
    source_volume: null,
    category: 'safety',
    pub_type: 'CFR',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['NTSB', 'accident reporting', 'incident notification', 'hazard definitions'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VI-C — UFC / DoD Engineering Criteria Cross-Refs (6)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VI_C: RegulationEntry[] = [
  {
    reg_id: 'UFC 3-260-02',
    title: 'Pavement Design for Airfields',
    description: 'Flexible and rigid airfield pavement design criteria including CBR and layered analysis.',
    publication_date: '30 Jun 2001',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_260_02_2001.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'pavement',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['pavement design', 'CBR', 'layered analysis', 'flexible', 'rigid'],
  },
  {
    reg_id: 'UFC 3-260-04',
    title: 'Airfield and Heliport Marking',
    description: 'DoD airfield/heliport marking standards; uses FHWA Manual of Uniform Traffic Control Devices.',
    publication_date: '2018 Ed.',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_260_04_2018.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'airfield_design',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['marking', 'heliport', 'traffic control devices', 'FHWA'],
  },
  {
    reg_id: 'UFC 3-460-01',
    title: 'Design: Petroleum Fuel Facilities',
    description: 'Fuel storage, distribution, and dispensing facility design standards for DoD airfields.',
    publication_date: 'Current Ed.',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_460_01_2019_c3.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'fueling',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['fuel facilities', 'petroleum', 'storage', 'distribution', 'dispensing'],
  },
  {
    reg_id: 'UFC 3-535-01',
    title: 'Visual Air Navigation Facilities',
    description: 'Airfield lighting: approach, runway, taxiway, and obstruction lighting systems.',
    publication_date: 'Current Ed.',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_3_535_01_2017_c3.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'lighting',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['airfield lighting', 'approach lights', 'runway lights', 'taxiway lights', 'obstruction lights'],
  },
  {
    reg_id: 'UFC 4-010-01',
    title: 'DoD Minimum Antiterrorism Standards for Buildings',
    description: 'Security and force protection standards for airfield facilities and access control points.',
    publication_date: 'Current Ed.',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_4_010_01_2018_c3.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'security',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['antiterrorism', 'force protection', 'security', 'access control'],
  },
  {
    reg_id: 'UFC 1-200-02',
    title: 'High-Performance and Sustainable Building Requirements',
    description: 'Energy and sustainability standards for airfield support facility construction/renovation.',
    publication_date: 'Current Ed.',
    url: 'https://www.wbdg.org/FFC/DOD/UFC/ufc_1_200_02_2020_c2.pdf',
    source_section: 'VI-C',
    source_volume: null,
    category: 'construction',
    pub_type: 'UFC',
    is_core: false,
    is_cross_ref: true,
    is_scrubbed: false,
    tags: ['sustainability', 'energy', 'high-performance', 'green building'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VII-A — Scrubbed from Vols 1-3: DAF Publications (11)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VII_A: RegulationEntry[] = [
  {
    reg_id: 'DAFMAN 13-204, Vol. 4',
    title: 'Radar, Airfield and Weather Systems (RAWS)',
    description: 'Companion volume governing RAWS personnel duties, qualifications, equipment maintenance, and flight inspection support. Directly referenced throughout Vol 1 Ch 1, 2, 3, and Attachment 7.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/dafman13-204v4/dafman13-204v4.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'airfield_ops',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['RAWS', 'radar', 'weather systems', 'equipment maintenance', 'flight inspection'],
  },
  {
    reg_id: 'DAFMAN 36-2806',
    title: 'Military Awards: Criteria and Procedures',
    description: 'Governs the Lt Gen Gordon A. Blake Aircraft Save/Assist Award and AF Airfield Operations Annual Awards. Referenced in Vol 1 para 2.1.1.6 and 2.3.2.1.',
    publication_date: '27 Oct 2022',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/dafman36-2806/dafman36-2806.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['awards', 'Blake Award', 'airfield operations awards', 'recognition'],
  },
  {
    reg_id: 'AFMAN 91-223',
    title: 'Aviation Safety Investigations and Reports',
    description: 'Procedures for investigating and reporting aviation safety events. Referenced in Vol 1 para 2.1.1.15 and 2.1.2.6 for SIB representation.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_se/publication/afman91-223/afman91-223.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'safety',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['aviation safety', 'SIB', 'safety investigation', 'reporting'],
  },
  {
    reg_id: 'AFI 36-701',
    title: 'Labor Management Relations',
    description: 'AF guidance for managers/supervisors dealing with unionized civilian employees. Referenced in Vol 1 para 2.9 for DoD civilian ATC/AM personnel.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-701/afi36-701.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['labor relations', 'civilian employees', 'union', 'ATC civilian'],
  },
  {
    reg_id: 'AFI 36-129',
    title: 'Civilian Personnel Management and Administration',
    description: 'Key employee designation for GS-2150/2152/2154 airfield ops civilians at CONUS locations. Referenced in Vol 1 para 2.9.1.5 and 2.9.2.5.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-129/afi36-129.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['civilian personnel', 'key employee', 'GS-2150', 'CONUS'],
  },
  {
    reg_id: 'AFI 51-403',
    title: 'International Agreements',
    description: 'Coordination requirements for LOPs with host nation agencies. Referenced in Vol 1 para 4.1.1.2.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_ja/publication/afi51-403/afi51-403.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'international',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['international agreements', 'LOP', 'host nation', 'coordination'],
  },
  {
    reg_id: 'AFI 10-401',
    title: 'Air Force Operations Planning and Execution',
    description: 'Format and content guidance for OPLANs containing airfield operations tasks. Referenced in Vol 1 para 4.1.2.5.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afi10-401/afi10-401.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'contingency',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['OPLAN', 'operations planning', 'execution', 'airfield tasks'],
  },
  {
    reg_id: 'AFMAN 11-502',
    title: 'Small Unmanned Aircraft Systems',
    description: 'Defines DoD UAS categories (Groups 1-5) used for UAS airfield ops procedures. Referenced in Vol 1 para 3.10.2.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afman11-502/afman11-502.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'uas',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['UAS', 'sUAS', 'unmanned', 'drone', 'Groups 1-5'],
  },
  {
    reg_id: 'AFI 36-2619',
    title: 'Military Personnel Appropriation Manday Program',
    description: 'Provides manday resources for critical ATC/AM manning shortfalls. Referenced in Vol 1 para 4.5.7.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-2619/afi36-2619.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'financial',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['manday', 'manning', 'ATC', 'AM', 'personnel shortfall'],
  },
  {
    reg_id: 'AFTTP 3-4.4',
    title: 'Contingency Airfield Operations',
    description: 'Tactical, Techniques, and Procedures for opening and operating deployed/contingency airfields. Referenced in Vol 1 para 1.4.3.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afttp3-4.4/afttp3-4.4.pdf',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'contingency',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['contingency', 'deployed', 'TTP', 'tactical', 'opening airfield'],
  },
  {
    reg_id: 'DoD 7000.14-R',
    title: 'DoD Financial Management Regulation',
    description: 'Governs Basic Allowance for Subsistence authorization for rotating-shift airfield ops personnel. Referenced in Vol 1 para 3.2.2.',
    publication_date: 'Current Ed.',
    url: 'https://comptroller.defense.gov/FMR/',
    source_section: 'VII-A',
    source_volume: 'Vol. 1',
    category: 'financial',
    pub_type: 'DoD',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['financial management', 'BAS', 'subsistence', 'rotating shift'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VII-B — Scrubbed: FAA Orders (2)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VII_B: RegulationEntry[] = [
  {
    reg_id: 'FAA Order JO 7610.14',
    title: 'Non-Sensitive Procedures for Special Operations',
    description: 'Contains the MOA between DOT/FAA and US Army-Navy-Air Force (Appendix 4-2). Governs ATC evaluation authority and AO-CV guiding regulations. Referenced in Vol 1 Att 7 (A7.1.1.1-A7.1.1.2).',
    publication_date: 'Current Ed.',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1040568',
    source_section: 'VII-B',
    source_volume: 'Vol. 1',
    category: 'atc',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['special operations', 'MOA', 'ATC evaluation', 'AO-CV', 'JO 7610.14'],
  },
  {
    reg_id: 'FAAO 8200.1D',
    title: 'United States Flight Inspection Manual',
    description: 'Flight inspection procedures for RAWS equipment and NAVAID certification. Referenced in Vol 1 DAFGM Att 1 references and A7.1.1.4.',
    publication_date: '6 Nov 2016',
    url: 'https://www.faa.gov/regulations_policies/orders_notices/index.cfm/go/document.information/documentID/1029824',
    source_section: 'VII-B',
    source_volume: 'Vol. 1',
    category: 'lighting',
    pub_type: 'FAA',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['flight inspection', 'RAWS', 'NAVAID certification', '8200.1D'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// SECTION VII-C — Scrubbed: Additional from Vols 2 & 3 (2)
// ═══════════════════════════════════════════════════════════════════

const SECTION_VII_C: RegulationEntry[] = [
  {
    reg_id: 'AFI 11-208',
    title: 'Department of the Air Force NOTAM System',
    description: 'Establishes NOTAM issuance, verification, and dissemination procedures for airfield restrictions and closures. Referenced in Vol 2 for airfield management NOTAM duties.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a3/publication/afi11-208/afi11-208.pdf',
    source_section: 'VII-C',
    source_volume: 'Vol. 2',
    category: 'notams',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['NOTAM', 'issuance', 'verification', 'dissemination', 'closures'],
  },
  {
    reg_id: 'AFI 36-2110',
    title: 'Total Force Assignments',
    description: 'Personnel assignment procedures for ATC and AM career fields. Referenced in Vol 3 Attachment 1 references for controller assignment management.',
    publication_date: 'Current Ed.',
    url: 'https://static.e-publishing.af.mil/production/1/af_a1/publication/afi36-2110/afi36-2110.pdf',
    source_section: 'VII-C',
    source_volume: 'Vol. 3',
    category: 'personnel',
    pub_type: 'DAF',
    is_core: false,
    is_cross_ref: false,
    is_scrubbed: true,
    tags: ['assignments', 'ATC', 'AM', 'controller assignment', 'total force'],
  },
]

// ═══════════════════════════════════════════════════════════════════
// COMBINED EXPORT — All 78 Regulations
// ═══════════════════════════════════════════════════════════════════

export const ALL_REGULATIONS: RegulationEntry[] = [
  ...CORE_PUBLICATIONS,
  ...SECTION_I,
  ...SECTION_II,
  ...SECTION_III,
  ...SECTION_IV,
  ...SECTION_V,
  ...SECTION_VI_A,
  ...SECTION_VI_B,
  ...SECTION_VI_C,
  ...SECTION_VII_A,
  ...SECTION_VII_B,
  ...SECTION_VII_C,
]

// Verification: 3 + 6 + 6 + 5 + 9 + 5 + 15 + 8 + 6 + 11 + 2 + 2 = 78
