// Wildlife Species Reference Database
// ~254 airfield hazard species curated from FAA National Wildlife Strike Database
// Photo URLs sourced from USFWS National Digital Library (public domain)
// Primary: IIIF endpoint at digitalmedia.fws.gov (CONTENTdm natdiglib collection)
// Fallback: fws.gov/media pages (Drupal CMS)
// All images are public domain (U.S. Government work)
//
// Offline images: run `python scripts/scrape_wildlife_images.py` to download
// all species photos to /public/wildlife_images/. The resolveWildlifeImage()
// function will prefer the local path when available.

export type WildlifeSpecies = {
  common_name: string
  scientific_name: string
  group: 'bird' | 'mammal' | 'reptile' | 'bat'
  size_category: 'small' | 'medium' | 'large'
  mean_mass_g: number
  strike_risk: 'low' | 'medium' | 'high' | 'critical'
  image_url: string | null
  image_credit: string
}

// ── Offline image manifest (generated by scripts/scrape_wildlife_images.py) ──
// When the scraper has been run, it creates /public/wildlife_image_manifest.json.
// To use offline images, import the manifest and pass it to setWildlifeImageManifest()
// at app startup, or simply rely on remote USFWS URLs (the default).
type ManifestEntry = { filename: string; source_url: string; license: string; group: string }
let _manifestCache: Record<string, ManifestEntry> = {}

/**
 * Set the wildlife image manifest (call at app init if offline images are available).
 * Example: import manifest from '../public/wildlife_image_manifest.json'
 *          setWildlifeImageManifest(manifest)
 */
export function setWildlifeImageManifest(manifest: Record<string, ManifestEntry>) {
  _manifestCache = manifest
}

function getWildlifeImageManifest(): Record<string, ManifestEntry> {
  return _manifestCache
}

/**
 * Resolve the best available image URL for a species.
 * 1. Manifest entry (if loaded via setWildlifeImageManifest)
 * 2. Deterministic local path: /wildlife_images/{group}/{safe_name}.jpg
 *    (relies on img onError handler to hide if file doesn't exist)
 * 3. Remote USFWS URL (image_url field) as last resort
 */
export function resolveWildlifeImage(species: WildlifeSpecies): string | null {
  // Check manifest first
  const entry = getWildlifeImageManifest()[species.common_name]
  if (entry?.filename) {
    return `/wildlife_images/${entry.filename}`
  }
  // Deterministic local path (matches scraper filename convention)
  const safeName = species.common_name.toLowerCase().replace(/[' ()-]/g, '_').replace(/[^a-z0-9_]/g, '').replace(/_+/g, '_')
  return `/wildlife_images/${species.group}/${safeName}.jpg`
}

/**
 * Return all species with image_url resolved to local paths when available.
 */
export function getSpeciesWithLocalImages(): WildlifeSpecies[] {
  return WILDLIFE_SPECIES.map(sp => ({
    ...sp,
    image_url: resolveWildlifeImage(sp),
  }))
}

// USFWS NCTC Image Library — IIIF endpoint (800px wide thumbnails)
const IIIF = 'https://digitalmedia.fws.gov/digital/iiif/natdiglib'
// Generates URL: {IIIF}/{ID}/full/800,/0/default.jpg

export const WILDLIFE_SPECIES: WildlifeSpecies[] = [
  // ══════════════════════════════════════════════════
  // BIRDS — Large (>1kg) — High/Critical Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Canada Goose',
    scientific_name: 'Branta canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 3600,
    strike_risk: 'critical',
    image_url: `${IIIF}/1489/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snow Goose',
    scientific_name: 'Anser caerulescens',
    group: 'bird', size_category: 'large', mean_mass_g: 2700,
    strike_risk: 'critical',
    image_url: `${IIIF}/15275/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Turkey Vulture',
    scientific_name: 'Cathartes aura',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'critical',
    image_url: `${IIIF}/1611/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Vulture',
    scientific_name: 'Coragyps atratus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${IIIF}/7747/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-tailed Hawk',
    scientific_name: 'Buteo jamaicensis',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/18455/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Blue Heron',
    scientific_name: 'Ardea herodias',
    group: 'bird', size_category: 'large', mean_mass_g: 2400,
    strike_risk: 'high',
    image_url: `${IIIF}/6891/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Horned Owl',
    scientific_name: 'Bubo virginianus',
    group: 'bird', size_category: 'large', mean_mass_g: 1400,
    strike_risk: 'high',
    image_url: `${IIIF}/8058/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bald Eagle',
    scientific_name: 'Haliaeetus leucocephalus',
    group: 'bird', size_category: 'large', mean_mass_g: 4300,
    strike_risk: 'critical',
    image_url: `${IIIF}/6773/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Osprey',
    scientific_name: 'Pandion haliaetus',
    group: 'bird', size_category: 'large', mean_mass_g: 1600,
    strike_risk: 'high',
    image_url: `${IIIF}/8094/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Sandhill Crane',
    scientific_name: 'Antigone canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 4500,
    strike_risk: 'critical',
    image_url: `${IIIF}/5590/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Egret',
    scientific_name: 'Ardea alba',
    group: 'bird', size_category: 'large', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${IIIF}/6879/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wild Turkey',
    scientific_name: 'Meleagris gallopavo',
    group: 'bird', size_category: 'large', mean_mass_g: 5800,
    strike_risk: 'critical',
    image_url: `${IIIF}/8756/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Double-crested Cormorant',
    scientific_name: 'Nannopterum auritum',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'high',
    image_url: `${IIIF}/7289/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown Pelican',
    scientific_name: 'Pelecanus occidentalis',
    group: 'bird', size_category: 'large', mean_mass_g: 3500,
    strike_risk: 'critical',
    image_url: `${IIIF}/3771/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American White Pelican',
    scientific_name: 'Pelecanus erythrorhynchos',
    group: 'bird', size_category: 'large', mean_mass_g: 7000,
    strike_risk: 'critical',
    image_url: `${IIIF}/8136/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-shouldered Hawk',
    scientific_name: 'Buteo lineatus',
    group: 'bird', size_category: 'large', mean_mass_g: 600,
    strike_risk: 'high',
    image_url: `${IIIF}/7515/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cooper\'s Hawk',
    scientific_name: 'Accipiter cooperii',
    group: 'bird', size_category: 'large', mean_mass_g: 440,
    strike_risk: 'high',
    image_url: `${IIIF}/7494/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Harrier',
    scientific_name: 'Circus hudsonius',
    group: 'bird', size_category: 'large', mean_mass_g: 400,
    strike_risk: 'high',
    image_url: `${IIIF}/7501/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snowy Owl',
    scientific_name: 'Bubo scandiacus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${IIIF}/8072/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Medium (100g–1kg) — Medium Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Mallard',
    scientific_name: 'Anas platyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/9090/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Herring Gull',
    scientific_name: 'Larus argentatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${IIIF}/6800/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Ring-billed Gull',
    scientific_name: 'Larus delawarensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 500,
    strike_risk: 'high',
    image_url: `${IIIF}/6804/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Laughing Gull',
    scientific_name: 'Leucophaeus atricilla',
    group: 'bird', size_category: 'medium', mean_mass_g: 330,
    strike_risk: 'high',
    image_url: `${IIIF}/6796/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Rock Pigeon',
    scientific_name: 'Columba livia',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'high',
    image_url: `${IIIF}/17706/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mourning Dove',
    scientific_name: 'Zenaida macroura',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${IIIF}/7372/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Crow',
    scientific_name: 'Corvus brachyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 450,
    strike_risk: 'medium',
    image_url: `${IIIF}/7330/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Kestrel',
    scientific_name: 'Falco sparverius',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${IIIF}/776/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Owl',
    scientific_name: 'Tyto alba',
    group: 'bird', size_category: 'medium', mean_mass_g: 460,
    strike_risk: 'medium',
    image_url: `${IIIF}/8038/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Killdeer',
    scientific_name: 'Charadrius vociferus',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${IIIF}/12311/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Nighthawk',
    scientific_name: 'Chordeiles minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${IIIF}/7938/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Peregrine Falcon',
    scientific_name: 'Falco peregrinus',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'high',
    image_url: `${IIIF}/7474/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Short-eared Owl',
    scientific_name: 'Asio flammeus',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/8066/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Robin',
    scientific_name: 'Turdus migratorius',
    group: 'bird', size_category: 'medium', mean_mass_g: 77,
    strike_risk: 'medium',
    image_url: `${IIIF}/7691/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Mockingbird',
    scientific_name: 'Mimus polyglottos',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${IIIF}/7680/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue Jay',
    scientific_name: 'Cyanocitta cristata',
    group: 'bird', size_category: 'medium', mean_mass_g: 90,
    strike_risk: 'low',
    image_url: `${IIIF}/7326/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Flicker',
    scientific_name: 'Colaptes auratus',
    group: 'bird', size_category: 'medium', mean_mass_g: 130,
    strike_risk: 'medium',
    image_url: `${IIIF}/8000/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-winged Blackbird',
    scientific_name: 'Agelaius phoeniceus',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${IIIF}/7205/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Grackle',
    scientific_name: 'Quiscalus quiscula',
    group: 'bird', size_category: 'medium', mean_mass_g: 115,
    strike_risk: 'medium',
    image_url: `${IIIF}/7215/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Meadowlark',
    scientific_name: 'Sturnella magna',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${IIIF}/7218/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown-headed Cowbird',
    scientific_name: 'Molothrus ater',
    group: 'bird', size_category: 'medium', mean_mass_g: 44,
    strike_risk: 'low',
    image_url: `${IIIF}/7210/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great-tailed Grackle',
    scientific_name: 'Quiscalus mexicanus',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/7217/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cattle Egret',
    scientific_name: 'Bubulcus ibis',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/6876/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green Heron',
    scientific_name: 'Butorides virescens',
    group: 'bird', size_category: 'medium', mean_mass_g: 210,
    strike_risk: 'medium',
    image_url: `${IIIF}/6895/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-crowned Night-Heron',
    scientific_name: 'Nycticorax nycticorax',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'medium',
    image_url: `${IIIF}/6903/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Chimney Swift',
    scientific_name: 'Chaetura pelagica',
    group: 'bird', size_category: 'medium', mean_mass_g: 23,
    strike_risk: 'low',
    image_url: `${IIIF}/7928/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Scissor-tailed Flycatcher',
    scientific_name: 'Tyrannus forficatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 43,
    strike_risk: 'low',
    image_url: `${IIIF}/7633/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Loggerhead Shrike',
    scientific_name: 'Lanius ludovicianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${IIIF}/7670/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mississippi Kite',
    scientific_name: 'Ictinia mississippiensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 290,
    strike_risk: 'medium',
    image_url: `${IIIF}/7507/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Upland Sandpiper',
    scientific_name: 'Bartramia longicauda',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${IIIF}/4358/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eurasian Collared-Dove',
    scientific_name: 'Streptopelia decaocto',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/7369/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Boat-tailed Grackle',
    scientific_name: 'Quiscalus major',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: null,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Black-backed Gull',
    scientific_name: 'Larus marinus',
    group: 'bird', size_category: 'large', mean_mass_g: 1700,
    strike_risk: 'high',
    image_url: `${IIIF}/6808/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bonaparte\'s Gull',
    scientific_name: 'Chroicocephalus philadelphia',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/6792/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Small (<100g) — Low Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'European Starling',
    scientific_name: 'Sturnus vulgaris',
    group: 'bird', size_category: 'small', mean_mass_g: 80,
    strike_risk: 'high', // Flocking behavior increases risk
    image_url: `${IIIF}/7700/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Horned Lark',
    scientific_name: 'Eremophila alpestris',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Common on airfields
    image_url: `${IIIF}/7649/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Swallow',
    scientific_name: 'Hirundo rustica',
    group: 'bird', size_category: 'small', mean_mass_g: 19,
    strike_risk: 'medium',
    image_url: `${IIIF}/7584/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Sparrow',
    scientific_name: 'Passer domesticus',
    group: 'bird', size_category: 'small', mean_mass_g: 28,
    strike_risk: 'low',
    image_url: `${IIIF}/7697/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Song Sparrow',
    scientific_name: 'Melospiza melodia',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${IIIF}/7254/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Savannah Sparrow',
    scientific_name: 'Passerculus sandwichensis',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'low',
    image_url: `${IIIF}/7248/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cliff Swallow',
    scientific_name: 'Petrochelidon pyrrhonota',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'medium',
    image_url: `${IIIF}/7590/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Tree Swallow',
    scientific_name: 'Tachycineta bicolor',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'medium',
    image_url: `${IIIF}/7598/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Bluebird',
    scientific_name: 'Sialia sialis',
    group: 'bird', size_category: 'small', mean_mass_g: 30,
    strike_risk: 'low',
    image_url: `${IIIF}/7684/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Purple Martin',
    scientific_name: 'Progne subis',
    group: 'bird', size_category: 'small', mean_mass_g: 56,
    strike_risk: 'medium',
    image_url: `${IIIF}/7594/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Goldfinch',
    scientific_name: 'Spinus tristis',
    group: 'bird', size_category: 'small', mean_mass_g: 13,
    strike_risk: 'low',
    image_url: `${IIIF}/7232/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Finch',
    scientific_name: 'Haemorhous mexicanus',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${IIIF}/7226/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cedar Waxwing',
    scientific_name: 'Bombycilla cedrorum',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Flocking behavior
    image_url: `${IIIF}/7711/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // WATERFOWL — Medium/Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Black Duck',
    scientific_name: 'Anas rubripes',
    group: 'bird', size_category: 'large', mean_mass_g: 1200,
    strike_risk: 'high',
    image_url: `${IIIF}/9082/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Pintail',
    scientific_name: 'Anas acuta',
    group: 'bird', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'high',
    image_url: `${IIIF}/9104/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green-winged Teal',
    scientific_name: 'Anas crecca',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/9118/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue-winged Teal',
    scientific_name: 'Spatula discors',
    group: 'bird', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${IIIF}/9114/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wood Duck',
    scientific_name: 'Aix sponsa',
    group: 'bird', size_category: 'medium', mean_mass_g: 680,
    strike_risk: 'medium',
    image_url: `${IIIF}/9072/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // SHOREBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Woodcock',
    scientific_name: 'Scolopax minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${IIIF}/4345/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wilson\'s Snipe',
    scientific_name: 'Gallinago delicata',
    group: 'bird', size_category: 'medium', mean_mass_g: 105,
    strike_risk: 'medium',
    image_url: `${IIIF}/4389/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Semipalmated Plover',
    scientific_name: 'Charadrius semipalmatus',
    group: 'bird', size_category: 'small', mean_mass_g: 47,
    strike_risk: 'low',
    image_url: `${IIIF}/4367/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // GAMEBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Ring-necked Pheasant',
    scientific_name: 'Phasianus colchicus',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/8747/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Bobwhite',
    scientific_name: 'Colinus virginianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 175,
    strike_risk: 'medium',
    image_url: `${IIIF}/8741/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'White-tailed Deer',
    scientific_name: 'Odocoileus virginianus',
    group: 'mammal', size_category: 'large', mean_mass_g: 68000,
    strike_risk: 'critical',
    image_url: `${IIIF}/17496/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mule Deer',
    scientific_name: 'Odocoileus hemionus',
    group: 'mammal', size_category: 'large', mean_mass_g: 70000,
    strike_risk: 'critical',
    image_url: `${IIIF}/5010/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Coyote',
    scientific_name: 'Canis latrans',
    group: 'mammal', size_category: 'large', mean_mass_g: 14000,
    strike_risk: 'critical',
    image_url: `${IIIF}/11774/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red Fox',
    scientific_name: 'Vulpes vulpes',
    group: 'mammal', size_category: 'large', mean_mass_g: 5000,
    strike_risk: 'high',
    image_url: `${IIIF}/4915/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Gray Fox',
    scientific_name: 'Urocyon cinereoargenteus',
    group: 'mammal', size_category: 'large', mean_mass_g: 4000,
    strike_risk: 'high',
    image_url: `${IIIF}/4911/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Feral Pig',
    scientific_name: 'Sus scrofa',
    group: 'mammal', size_category: 'large', mean_mass_g: 80000,
    strike_risk: 'critical',
    image_url: `${IIIF}/5031/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Pronghorn',
    scientific_name: 'Antilocapra americana',
    group: 'mammal', size_category: 'large', mean_mass_g: 55000,
    strike_risk: 'critical',
    image_url: `${IIIF}/4998/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Medium/Small
  // ══════════════════════════════════════════════════
  {
    common_name: 'Eastern Cottontail',
    scientific_name: 'Sylvilagus floridanus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 1200,
    strike_risk: 'medium',
    image_url: `${IIIF}/12317/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Striped Skunk',
    scientific_name: 'Mephitis mephitis',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3200,
    strike_risk: 'medium',
    image_url: `${IIIF}/4960/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Raccoon',
    scientific_name: 'Procyon lotor',
    group: 'mammal', size_category: 'medium', mean_mass_g: 6000,
    strike_risk: 'high',
    image_url: `${IIIF}/4946/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Virginia Opossum',
    scientific_name: 'Didelphis virginiana',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3000,
    strike_risk: 'medium',
    image_url: `${IIIF}/4865/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Nine-banded Armadillo',
    scientific_name: 'Dasypus novemcinctus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 5500,
    strike_risk: 'medium',
    image_url: `${IIIF}/4860/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Woodchuck',
    scientific_name: 'Marmota monax',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3600,
    strike_risk: 'medium',
    image_url: `${IIIF}/4932/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Thirteen-lined Ground Squirrel',
    scientific_name: 'Ictidomys tridecemlineatus',
    group: 'mammal', size_category: 'small', mean_mass_g: 170,
    strike_risk: 'low',
    image_url: `${IIIF}/4928/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-tailed Prairie Dog',
    scientific_name: 'Cynomys ludovicianus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'medium',
    image_url: `${IIIF}/4920/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // REPTILES
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Alligator',
    scientific_name: 'Alligator mississippiensis',
    group: 'reptile', size_category: 'large', mean_mass_g: 200000,
    strike_risk: 'critical',
    image_url: `${IIIF}/4777/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Snapping Turtle',
    scientific_name: 'Chelydra serpentina',
    group: 'reptile', size_category: 'large', mean_mass_g: 10000,
    strike_risk: 'high',
    image_url: `${IIIF}/4800/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Box Turtle',
    scientific_name: 'Terrapene carolina',
    group: 'reptile', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${IIIF}/4815/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Rat Snake',
    scientific_name: 'Pantherophis obsoletus',
    group: 'reptile', size_category: 'medium', mean_mass_g: 700,
    strike_risk: 'low',
    image_url: null,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BATS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Brazilian Free-tailed Bat',
    scientific_name: 'Tadarida brasiliensis',
    group: 'bat', size_category: 'small', mean_mass_g: 12,
    strike_risk: 'medium', // Large colonies near airfields
    image_url: `${IIIF}/4841/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Big Brown Bat',
    scientific_name: 'Eptesicus fuscus',
    group: 'bat', size_category: 'small', mean_mass_g: 16,
    strike_risk: 'low',
    image_url: `${IIIF}/4835/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Little Brown Bat',
    scientific_name: 'Myotis lucifugus',
    group: 'bat', size_category: 'small', mean_mass_g: 8,
    strike_risk: 'low',
    image_url: `${IIIF}/4845/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Hoary Bat',
    scientific_name: 'Lasiurus cinereus',
    group: 'bat', size_category: 'small', mean_mass_g: 26,
    strike_risk: 'low',
    image_url: `${IIIF}/4849/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Red Bat',
    scientific_name: 'Lasiurus borealis',
    group: 'bat', size_category: 'small', mean_mass_g: 10,
    strike_risk: 'low',
    image_url: `${IIIF}/4838/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════════════════
  // ADDITIONAL SPECIES — Comprehensive BASH coverage
  // FAA Wildlife Strike Database top species + regional coverage
  // ══════════════════════════════════════════════════════════════

  // ── Swans ──
  { common_name: 'Mute Swan', scientific_name: 'Cygnus olor', group: 'bird', size_category: 'large', mean_mass_g: 10000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Tundra Swan', scientific_name: 'Cygnus columbianus', group: 'bird', size_category: 'large', mean_mass_g: 6500, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Trumpeter Swan', scientific_name: 'Cygnus buccinator', group: 'bird', size_category: 'large', mean_mass_g: 10500, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },

  // ── Additional Geese ──
  { common_name: 'Greater White-fronted Goose', scientific_name: 'Anser albifrons', group: 'bird', size_category: 'large', mean_mass_g: 2700, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Cackling Goose', scientific_name: 'Branta hutchinsii', group: 'bird', size_category: 'large', mean_mass_g: 1800, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: "Ross's Goose", scientific_name: 'Anser rossii', group: 'bird', size_category: 'large', mean_mass_g: 1400, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Hawaiian Goose (Nene)', scientific_name: 'Branta sandvicensis', group: 'bird', size_category: 'large', mean_mass_g: 2200, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },

  // ── Additional Raptors ──
  { common_name: 'Golden Eagle', scientific_name: 'Aquila chrysaetos', group: 'bird', size_category: 'large', mean_mass_g: 4000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Ferruginous Hawk', scientific_name: 'Buteo regalis', group: 'bird', size_category: 'large', mean_mass_g: 1500, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Rough-legged Hawk', scientific_name: 'Buteo lagopus', group: 'bird', size_category: 'large', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: "Swainson's Hawk", scientific_name: 'Buteo swainsoni', group: 'bird', size_category: 'large', mean_mass_g: 900, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Broad-winged Hawk', scientific_name: 'Buteo platypterus', group: 'bird', size_category: 'large', mean_mass_g: 450, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: "Harris's Hawk", scientific_name: 'Parabuteo unicinctus', group: 'bird', size_category: 'large', mean_mass_g: 900, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White-tailed Hawk', scientific_name: 'Geranoaetus albicaudatus', group: 'bird', size_category: 'large', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Sharp-shinned Hawk', scientific_name: 'Accipiter striatus', group: 'bird', size_category: 'medium', mean_mass_g: 150, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Crested Caracara', scientific_name: 'Caracara plancus', group: 'bird', size_category: 'large', mean_mass_g: 1050, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Merlin', scientific_name: 'Falco columbarius', group: 'bird', size_category: 'medium', mean_mass_g: 200, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Prairie Falcon', scientific_name: 'Falco mexicanus', group: 'bird', size_category: 'large', mean_mass_g: 720, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },

  // ── Additional Owls ──
  { common_name: 'Barred Owl', scientific_name: 'Strix varia', group: 'bird', size_category: 'large', mean_mass_g: 750, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Burrowing Owl', scientific_name: 'Athene cunicularia', group: 'bird', size_category: 'medium', mean_mass_g: 150, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Eastern Screech-Owl', scientific_name: 'Megascops asio', group: 'bird', size_category: 'small', mean_mass_g: 170, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Long-eared Owl', scientific_name: 'Asio otus', group: 'bird', size_category: 'medium', mean_mass_g: 280, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Great Gray Owl', scientific_name: 'Strix nebulosa', group: 'bird', size_category: 'large', mean_mass_g: 1100, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },

  // ── Additional Herons, Egrets, Wading Birds ──
  { common_name: 'Snowy Egret', scientific_name: 'Egretta thula', group: 'bird', size_category: 'medium', mean_mass_g: 370, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Little Blue Heron', scientific_name: 'Egretta caerulea', group: 'bird', size_category: 'medium', mean_mass_g: 350, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Tricolored Heron', scientific_name: 'Egretta tricolor', group: 'bird', size_category: 'medium', mean_mass_g: 350, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Yellow-crowned Night-Heron', scientific_name: 'Nyctanassa violacea', group: 'bird', size_category: 'medium', mean_mass_g: 700, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White Ibis', scientific_name: 'Eudocimus albus', group: 'bird', size_category: 'medium', mean_mass_g: 900, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Glossy Ibis', scientific_name: 'Plegadis falcinellus', group: 'bird', size_category: 'medium', mean_mass_g: 600, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White-faced Ibis', scientific_name: 'Plegadis chihi', group: 'bird', size_category: 'medium', mean_mass_g: 550, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Roseate Spoonbill', scientific_name: 'Platalea ajaja', group: 'bird', size_category: 'large', mean_mass_g: 1400, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Wood Stork', scientific_name: 'Mycteria americana', group: 'bird', size_category: 'large', mean_mass_g: 2600, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Anhinga', scientific_name: 'Anhinga anhinga', group: 'bird', size_category: 'large', mean_mass_g: 1200, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },

  // ── Other Large/Medium Water Birds ──
  { common_name: 'American Coot', scientific_name: 'Fulica americana', group: 'bird', size_category: 'medium', mean_mass_g: 650, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Loon', scientific_name: 'Gavia immer', group: 'bird', size_category: 'large', mean_mass_g: 4100, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Whooping Crane', scientific_name: 'Grus americana', group: 'bird', size_category: 'large', mean_mass_g: 7000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },

  // ── Additional Waterfowl (Ducks) ──
  { common_name: 'Gadwall', scientific_name: 'Mareca strepera', group: 'bird', size_category: 'medium', mean_mass_g: 900, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Wigeon', scientific_name: 'Mareca americana', group: 'bird', size_category: 'medium', mean_mass_g: 770, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Northern Shoveler', scientific_name: 'Spatula clypeata', group: 'bird', size_category: 'medium', mean_mass_g: 620, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Canvasback', scientific_name: 'Aythya valisineria', group: 'bird', size_category: 'large', mean_mass_g: 1200, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Redhead', scientific_name: 'Aythya americana', group: 'bird', size_category: 'medium', mean_mass_g: 950, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Ring-necked Duck', scientific_name: 'Aythya collaris', group: 'bird', size_category: 'medium', mean_mass_g: 700, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Lesser Scaup', scientific_name: 'Aythya affinis', group: 'bird', size_category: 'medium', mean_mass_g: 800, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Greater Scaup', scientific_name: 'Aythya marila', group: 'bird', size_category: 'medium', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Bufflehead', scientific_name: 'Bucephala albeola', group: 'bird', size_category: 'medium', mean_mass_g: 400, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Goldeneye', scientific_name: 'Bucephala clangula', group: 'bird', size_category: 'medium', mean_mass_g: 900, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Hooded Merganser', scientific_name: 'Lophodytes cucullatus', group: 'bird', size_category: 'medium', mean_mass_g: 680, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Merganser', scientific_name: 'Mergus merganser', group: 'bird', size_category: 'large', mean_mass_g: 1500, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Red-breasted Merganser', scientific_name: 'Mergus serrator', group: 'bird', size_category: 'medium', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Ruddy Duck', scientific_name: 'Oxyura jamaicensis', group: 'bird', size_category: 'medium', mean_mass_g: 540, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ── Additional Gulls and Terns ──
  { common_name: 'California Gull', scientific_name: 'Larus californicus', group: 'bird', size_category: 'medium', mean_mass_g: 600, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Western Gull', scientific_name: 'Larus occidentalis', group: 'bird', size_category: 'large', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Glaucous-winged Gull', scientific_name: 'Larus glaucescens', group: 'bird', size_category: 'large', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Glaucous Gull', scientific_name: 'Larus hyperboreus', group: 'bird', size_category: 'large', mean_mass_g: 1500, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Iceland Gull', scientific_name: 'Larus glaucoides', group: 'bird', size_category: 'medium', mean_mass_g: 850, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Lesser Black-backed Gull', scientific_name: 'Larus fuscus', group: 'bird', size_category: 'large', mean_mass_g: 800, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: "Franklin's Gull", scientific_name: 'Leucophaeus pipixcan', group: 'bird', size_category: 'medium', mean_mass_g: 280, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Royal Tern', scientific_name: 'Thalasseus maximus', group: 'bird', size_category: 'medium', mean_mass_g: 450, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Caspian Tern', scientific_name: 'Hydroprogne caspia', group: 'bird', size_category: 'medium', mean_mass_g: 660, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Tern', scientific_name: 'Sterna hirundo', group: 'bird', size_category: 'medium', mean_mass_g: 120, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Least Tern', scientific_name: 'Sternula antillarum', group: 'bird', size_category: 'small', mean_mass_g: 45, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: "Forster's Tern", scientific_name: 'Sterna forsteri', group: 'bird', size_category: 'medium', mean_mass_g: 170, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black Skimmer', scientific_name: 'Rynchops niger', group: 'bird', size_category: 'medium', mean_mass_g: 300, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ── Additional Shorebirds ──
  { common_name: 'Willet', scientific_name: 'Tringa semipalmata', group: 'bird', size_category: 'medium', mean_mass_g: 250, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Greater Yellowlegs', scientific_name: 'Tringa melanoleuca', group: 'bird', size_category: 'medium', mean_mass_g: 170, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Lesser Yellowlegs', scientific_name: 'Tringa flavipes', group: 'bird', size_category: 'medium', mean_mass_g: 80, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Spotted Sandpiper', scientific_name: 'Actitis macularius', group: 'bird', size_category: 'small', mean_mass_g: 40, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Least Sandpiper', scientific_name: 'Calidris minutilla', group: 'bird', size_category: 'small', mean_mass_g: 22, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Dunlin', scientific_name: 'Calidris alpina', group: 'bird', size_category: 'small', mean_mass_g: 55, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Long-billed Curlew', scientific_name: 'Numenius americanus', group: 'bird', size_category: 'large', mean_mass_g: 600, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Marbled Godwit', scientific_name: 'Limosa fedoa', group: 'bird', size_category: 'medium', mean_mass_g: 370, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Avocet', scientific_name: 'Recurvirostra americana', group: 'bird', size_category: 'medium', mean_mass_g: 310, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black-necked Stilt', scientific_name: 'Himantopus mexicanus', group: 'bird', size_category: 'medium', mean_mass_g: 180, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black-bellied Plover', scientific_name: 'Pluvialis squatarola', group: 'bird', size_category: 'medium', mean_mass_g: 230, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Golden-Plover', scientific_name: 'Pluvialis dominica', group: 'bird', size_category: 'medium', mean_mass_g: 145, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Piping Plover', scientific_name: 'Charadrius melodus', group: 'bird', size_category: 'small', mean_mass_g: 55, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },

  // ── Corvids and Other Medium Birds ──
  { common_name: 'Fish Crow', scientific_name: 'Corvus ossifragus', group: 'bird', size_category: 'medium', mean_mass_g: 280, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Raven', scientific_name: 'Corvus corax', group: 'bird', size_category: 'large', mean_mass_g: 1100, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black-billed Magpie', scientific_name: 'Pica hudsonia', group: 'bird', size_category: 'medium', mean_mass_g: 180, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: "Brewer's Blackbird", scientific_name: 'Euphagus cyanocephalus', group: 'bird', size_category: 'medium', mean_mass_g: 63, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Western Meadowlark', scientific_name: 'Sturnella neglecta', group: 'bird', size_category: 'medium', mean_mass_g: 100, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Yellow-headed Blackbird', scientific_name: 'Xanthocephalus xanthocephalus', group: 'bird', size_category: 'medium', mean_mass_g: 65, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Rusty Blackbird', scientific_name: 'Euphagus carolinus', group: 'bird', size_category: 'medium', mean_mass_g: 60, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Western Kingbird', scientific_name: 'Tyrannus verticalis', group: 'bird', size_category: 'medium', mean_mass_g: 40, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Eastern Kingbird', scientific_name: 'Tyrannus tyrannus', group: 'bird', size_category: 'medium', mean_mass_g: 40, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: "Say's Phoebe", scientific_name: 'Sayornis saya', group: 'bird', size_category: 'small', mean_mass_g: 21, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Eastern Phoebe', scientific_name: 'Sayornis phoebe', group: 'bird', size_category: 'small', mean_mass_g: 20, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Belted Kingfisher', scientific_name: 'Megaceryle alcyon', group: 'bird', size_category: 'medium', mean_mass_g: 150, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Red-bellied Woodpecker', scientific_name: 'Melanerpes carolinus', group: 'bird', size_category: 'medium', mean_mass_g: 70, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Downy Woodpecker', scientific_name: 'Dryobates pubescens', group: 'bird', size_category: 'small', mean_mass_g: 27, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Red-headed Woodpecker', scientific_name: 'Melanerpes erythrocephalus', group: 'bird', size_category: 'medium', mean_mass_g: 70, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ── Small Songbirds and Passerines ──
  { common_name: 'Western Bluebird', scientific_name: 'Sialia mexicana', group: 'bird', size_category: 'small', mean_mass_g: 28, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Mountain Bluebird', scientific_name: 'Sialia currucoides', group: 'bird', size_category: 'small', mean_mass_g: 30, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Vesper Sparrow', scientific_name: 'Pooecetes gramineus', group: 'bird', size_category: 'small', mean_mass_g: 25, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Grasshopper Sparrow', scientific_name: 'Ammodramus savannarum', group: 'bird', size_category: 'small', mean_mass_g: 17, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Lark Sparrow', scientific_name: 'Chondestes grammacus', group: 'bird', size_category: 'small', mean_mass_g: 29, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White-crowned Sparrow', scientific_name: 'Zonotrichia leucophrys', group: 'bird', size_category: 'small', mean_mass_g: 29, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Dark-eyed Junco', scientific_name: 'Junco hyemalis', group: 'bird', size_category: 'small', mean_mass_g: 20, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Dickcissel', scientific_name: 'Spiza americana', group: 'bird', size_category: 'small', mean_mass_g: 27, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Bobolink', scientific_name: 'Dolichonyx oryzivorus', group: 'bird', size_category: 'small', mean_mass_g: 38, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Pipit', scientific_name: 'Anthus rubescens', group: 'bird', size_category: 'small', mean_mass_g: 21, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Bank Swallow', scientific_name: 'Riparia riparia', group: 'bird', size_category: 'small', mean_mass_g: 13, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Northern Rough-winged Swallow', scientific_name: 'Stelgidopteryx serripennis', group: 'bird', size_category: 'small', mean_mass_g: 16, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Ruby-throated Hummingbird', scientific_name: 'Archilochus colubris', group: 'bird', size_category: 'small', mean_mass_g: 3, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Snow Bunting', scientific_name: 'Plectrophenax nivalis', group: 'bird', size_category: 'small', mean_mass_g: 35, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Lapland Longspur', scientific_name: 'Calcarius lapponicus', group: 'bird', size_category: 'small', mean_mass_g: 27, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ── Additional Gamebirds ──
  { common_name: 'Greater Sage-Grouse', scientific_name: 'Centrocercus urophasianus', group: 'bird', size_category: 'large', mean_mass_g: 2500, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Greater Prairie-Chicken', scientific_name: 'Tympanuchus cupido', group: 'bird', size_category: 'large', mean_mass_g: 1000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'California Quail', scientific_name: 'Callipepla californica', group: 'bird', size_category: 'medium', mean_mass_g: 175, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: "Gambel's Quail", scientific_name: 'Callipepla gambelii', group: 'bird', size_category: 'medium', mean_mass_g: 165, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Scaled Quail', scientific_name: 'Callipepla squamata', group: 'bird', size_category: 'medium', mean_mass_g: 185, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Chukar', scientific_name: 'Alectoris chukar', group: 'bird', size_category: 'medium', mean_mass_g: 500, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Gray Partridge', scientific_name: 'Perdix perdix', group: 'bird', size_category: 'medium', mean_mass_g: 400, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Greater Roadrunner', scientific_name: 'Geococcyx californianus', group: 'bird', size_category: 'medium', mean_mass_g: 340, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ── Alaska / Hawaii / Overseas Specialties ──
  { common_name: 'Laysan Albatross', scientific_name: 'Phoebastria immutabilis', group: 'bird', size_category: 'large', mean_mass_g: 3200, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black-footed Albatross', scientific_name: 'Phoebastria nigripes', group: 'bird', size_category: 'large', mean_mass_g: 3100, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Short-tailed Albatross', scientific_name: 'Phoebastria albatrus', group: 'bird', size_category: 'large', mean_mass_g: 4500, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Wedge-tailed Shearwater', scientific_name: 'Ardenna pacifica', group: 'bird', size_category: 'medium', mean_mass_g: 400, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Common Myna', scientific_name: 'Acridotheres tristis', group: 'bird', size_category: 'medium', mean_mass_g: 120, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Pacific Golden-Plover', scientific_name: 'Pluvialis fulva', group: 'bird', size_category: 'medium', mean_mass_g: 145, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Willow Ptarmigan', scientific_name: 'Lagopus lagopus', group: 'bird', size_category: 'medium', mean_mass_g: 550, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Rock Ptarmigan', scientific_name: 'Lagopus muta', group: 'bird', size_category: 'medium', mean_mass_g: 450, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: "Steller's Sea-Eagle", scientific_name: 'Haliaeetus pelagicus', group: 'bird', size_category: 'large', mean_mass_g: 6200, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },

  // ══════════════════════════════════════════════════
  // MAMMALS — Additional
  // ══════════════════════════════════════════════════

  // ── Large Mammals ──
  { common_name: 'Elk', scientific_name: 'Cervus canadensis', group: 'mammal', size_category: 'large', mean_mass_g: 300000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Moose', scientific_name: 'Alces alces', group: 'mammal', size_category: 'large', mean_mass_g: 450000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Black Bear', scientific_name: 'Ursus americanus', group: 'mammal', size_category: 'large', mean_mass_g: 120000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Bobcat', scientific_name: 'Lynx rufus', group: 'mammal', size_category: 'large', mean_mass_g: 9000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Feral Dog', scientific_name: 'Canis lupus familiaris', group: 'mammal', size_category: 'large', mean_mass_g: 20000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Feral Cat', scientific_name: 'Felis catus', group: 'mammal', size_category: 'medium', mean_mass_g: 4000, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Javelina (Collared Peccary)', scientific_name: 'Pecari tajacu', group: 'mammal', size_category: 'large', mean_mass_g: 22000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Bison', scientific_name: 'Bison bison', group: 'mammal', size_category: 'large', mean_mass_g: 700000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Caribou', scientific_name: 'Rangifer tarandus', group: 'mammal', size_category: 'large', mean_mass_g: 150000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Mountain Lion', scientific_name: 'Puma concolor', group: 'mammal', size_category: 'large', mean_mass_g: 60000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Kit Fox', scientific_name: 'Vulpes macrotis', group: 'mammal', size_category: 'medium', mean_mass_g: 2000, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Swift Fox', scientific_name: 'Vulpes velox', group: 'mammal', size_category: 'medium', mean_mass_g: 2300, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Arctic Fox', scientific_name: 'Vulpes lagopus', group: 'mammal', size_category: 'medium', mean_mass_g: 3500, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Badger', scientific_name: 'Taxidea taxus', group: 'mammal', size_category: 'medium', mean_mass_g: 8000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },

  // ── Small/Medium Mammals ──
  { common_name: 'Desert Cottontail', scientific_name: 'Sylvilagus audubonii', group: 'mammal', size_category: 'medium', mean_mass_g: 1000, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black-tailed Jackrabbit', scientific_name: 'Lepus californicus', group: 'mammal', size_category: 'medium', mean_mass_g: 2500, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White-tailed Jackrabbit', scientific_name: 'Lepus townsendii', group: 'mammal', size_category: 'medium', mean_mass_g: 3200, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Snowshoe Hare', scientific_name: 'Lepus americanus', group: 'mammal', size_category: 'medium', mean_mass_g: 1500, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Nutria (Coypu)', scientific_name: 'Myocastor coypus', group: 'mammal', size_category: 'medium', mean_mass_g: 6000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Muskrat', scientific_name: 'Ondatra zibethicus', group: 'mammal', size_category: 'medium', mean_mass_g: 1100, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Beaver', scientific_name: 'Castor canadensis', group: 'mammal', size_category: 'large', mean_mass_g: 20000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Fox Squirrel', scientific_name: 'Sciurus niger', group: 'mammal', size_category: 'medium', mean_mass_g: 800, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Eastern Gray Squirrel', scientific_name: 'Sciurus carolinensis', group: 'mammal', size_category: 'medium', mean_mass_g: 500, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Rock Squirrel', scientific_name: 'Otospermophilus variegatus', group: 'mammal', size_category: 'medium', mean_mass_g: 700, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: "Richardson's Ground Squirrel", scientific_name: 'Urocitellus richardsonii', group: 'mammal', size_category: 'small', mean_mass_g: 300, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'California Ground Squirrel', scientific_name: 'Otospermophilus beecheyi', group: 'mammal', size_category: 'medium', mean_mass_g: 600, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Kangaroo Rat (spp.)', scientific_name: 'Dipodomys spp.', group: 'mammal', size_category: 'small', mean_mass_g: 45, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'White-tailed Prairie Dog', scientific_name: 'Cynomys leucurus', group: 'mammal', size_category: 'medium', mean_mass_g: 800, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: "Gunnison's Prairie Dog", scientific_name: 'Cynomys gunnisoni', group: 'mammal', size_category: 'medium', mean_mass_g: 700, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Long-tailed Weasel', scientific_name: 'Mustela frenata', group: 'mammal', size_category: 'small', mean_mass_g: 200, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Small Indian Mongoose', scientific_name: 'Urva auropunctata', group: 'mammal', size_category: 'medium', mean_mass_g: 600, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },

  // ══════════════════════════════════════════════════
  // REPTILES — Additional
  // ══════════════════════════════════════════════════
  { common_name: 'Gopher Tortoise', scientific_name: 'Gopherus polyphemus', group: 'reptile', size_category: 'medium', mean_mass_g: 5000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Desert Tortoise', scientific_name: 'Gopherus agassizii', group: 'reptile', size_category: 'medium', mean_mass_g: 4000, strike_risk: 'high', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Eastern Diamondback Rattlesnake', scientific_name: 'Crotalus adamanteus', group: 'reptile', size_category: 'medium', mean_mass_g: 2300, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Western Diamondback Rattlesnake', scientific_name: 'Crotalus atrox', group: 'reptile', size_category: 'medium', mean_mass_g: 1800, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Cottonmouth', scientific_name: 'Agkistrodon piscivorus', group: 'reptile', size_category: 'medium', mean_mass_g: 600, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Black Racer', scientific_name: 'Coluber constrictor', group: 'reptile', size_category: 'medium', mean_mass_g: 350, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Gopher Snake', scientific_name: 'Pituophis catenifer', group: 'reptile', size_category: 'medium', mean_mass_g: 500, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Green Iguana', scientific_name: 'Iguana iguana', group: 'reptile', size_category: 'medium', mean_mass_g: 4000, strike_risk: 'medium', image_url: null, image_credit: 'USFWS' },
  { common_name: 'American Crocodile', scientific_name: 'Crocodylus acutus', group: 'reptile', size_category: 'large', mean_mass_g: 200000, strike_risk: 'critical', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Red-eared Slider', scientific_name: 'Trachemys scripta elegans', group: 'reptile', size_category: 'medium', mean_mass_g: 300, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Painted Turtle', scientific_name: 'Chrysemys picta', group: 'reptile', size_category: 'medium', mean_mass_g: 350, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },

  // ══════════════════════════════════════════════════
  // BATS — Additional
  // ══════════════════════════════════════════════════
  { common_name: 'Silver-haired Bat', scientific_name: 'Lasionycteris noctivagans', group: 'bat', size_category: 'small', mean_mass_g: 11, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Tri-colored Bat', scientific_name: 'Perimyotis subflavus', group: 'bat', size_category: 'small', mean_mass_g: 6, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Evening Bat', scientific_name: 'Nycticeius humeralis', group: 'bat', size_category: 'small', mean_mass_g: 10, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Indiana Bat', scientific_name: 'Myotis sodalis', group: 'bat', size_category: 'small', mean_mass_g: 7, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Northern Long-eared Bat', scientific_name: 'Myotis septentrionalis', group: 'bat', size_category: 'small', mean_mass_g: 8, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Pallid Bat', scientific_name: 'Antrozous pallidus', group: 'bat', size_category: 'small', mean_mass_g: 20, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Cave Myotis', scientific_name: 'Myotis velifer', group: 'bat', size_category: 'small', mean_mass_g: 12, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: 'Western Small-footed Myotis', scientific_name: 'Myotis ciliolabrum', group: 'bat', size_category: 'small', mean_mass_g: 5, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
  { common_name: "Townsend's Big-eared Bat", scientific_name: 'Corynorhinus townsendii', group: 'bat', size_category: 'small', mean_mass_g: 10, strike_risk: 'low', image_url: null, image_credit: 'USFWS' },
]
