// Wildlife Species Reference Database
// ~80 common airfield hazard species curated from FAA National Wildlife Strike Database
// Photo URLs sourced from USFWS National Digital Library (public domain)
// URL pattern: https://digitalmedia.fws.gov/digital/api/singleitem/image/natdiglib/{ID}/default.jpg

export type WildlifeSpecies = {
  common_name: string
  scientific_name: string
  group: 'bird' | 'mammal' | 'reptile' | 'bat'
  size_category: 'small' | 'medium' | 'large'
  mean_mass_g: number
  strike_risk: 'low' | 'medium' | 'high' | 'critical'
  image_url: string | null
  image_credit: string
}

// USFWS NCTC Image Library base URL
const USFWS = 'https://digitalmedia.fws.gov/digital/api/singleitem/image/natdiglib'

export const WILDLIFE_SPECIES: WildlifeSpecies[] = [
  // ══════════════════════════════════════════════════
  // BIRDS — Large (>1kg) — High/Critical Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Canada Goose',
    scientific_name: 'Branta canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 3600,
    strike_risk: 'critical',
    image_url: `${USFWS}/9222/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snow Goose',
    scientific_name: 'Anser caerulescens',
    group: 'bird', size_category: 'large', mean_mass_g: 2700,
    strike_risk: 'critical',
    image_url: `${USFWS}/4058/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Turkey Vulture',
    scientific_name: 'Cathartes aura',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'critical',
    image_url: `${USFWS}/7756/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Vulture',
    scientific_name: 'Coragyps atratus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${USFWS}/7747/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-tailed Hawk',
    scientific_name: 'Buteo jamaicensis',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${USFWS}/7519/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Blue Heron',
    scientific_name: 'Ardea herodias',
    group: 'bird', size_category: 'large', mean_mass_g: 2400,
    strike_risk: 'high',
    image_url: `${USFWS}/6891/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Horned Owl',
    scientific_name: 'Bubo virginianus',
    group: 'bird', size_category: 'large', mean_mass_g: 1400,
    strike_risk: 'high',
    image_url: `${USFWS}/8058/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bald Eagle',
    scientific_name: 'Haliaeetus leucocephalus',
    group: 'bird', size_category: 'large', mean_mass_g: 4300,
    strike_risk: 'critical',
    image_url: `${USFWS}/6773/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Osprey',
    scientific_name: 'Pandion haliaetus',
    group: 'bird', size_category: 'large', mean_mass_g: 1600,
    strike_risk: 'high',
    image_url: `${USFWS}/8094/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Sandhill Crane',
    scientific_name: 'Antigone canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 4500,
    strike_risk: 'critical',
    image_url: `${USFWS}/5590/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Egret',
    scientific_name: 'Ardea alba',
    group: 'bird', size_category: 'large', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${USFWS}/6879/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wild Turkey',
    scientific_name: 'Meleagris gallopavo',
    group: 'bird', size_category: 'large', mean_mass_g: 5800,
    strike_risk: 'critical',
    image_url: `${USFWS}/8756/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Double-crested Cormorant',
    scientific_name: 'Nannopterum auritum',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'high',
    image_url: `${USFWS}/7289/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown Pelican',
    scientific_name: 'Pelecanus occidentalis',
    group: 'bird', size_category: 'large', mean_mass_g: 3500,
    strike_risk: 'critical',
    image_url: `${USFWS}/3771/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American White Pelican',
    scientific_name: 'Pelecanus erythrorhynchos',
    group: 'bird', size_category: 'large', mean_mass_g: 7000,
    strike_risk: 'critical',
    image_url: `${USFWS}/8136/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-shouldered Hawk',
    scientific_name: 'Buteo lineatus',
    group: 'bird', size_category: 'large', mean_mass_g: 600,
    strike_risk: 'high',
    image_url: `${USFWS}/7515/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cooper\'s Hawk',
    scientific_name: 'Accipiter cooperii',
    group: 'bird', size_category: 'large', mean_mass_g: 440,
    strike_risk: 'high',
    image_url: `${USFWS}/7494/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Harrier',
    scientific_name: 'Circus hudsonius',
    group: 'bird', size_category: 'large', mean_mass_g: 400,
    strike_risk: 'high',
    image_url: `${USFWS}/7501/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snowy Owl',
    scientific_name: 'Bubo scandiacus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${USFWS}/8072/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Medium (100g–1kg) — Medium Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Mallard',
    scientific_name: 'Anas platyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${USFWS}/9090/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Herring Gull',
    scientific_name: 'Larus argentatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${USFWS}/6800/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Ring-billed Gull',
    scientific_name: 'Larus delawarensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 500,
    strike_risk: 'high',
    image_url: `${USFWS}/6804/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Laughing Gull',
    scientific_name: 'Leucophaeus atricilla',
    group: 'bird', size_category: 'medium', mean_mass_g: 330,
    strike_risk: 'high',
    image_url: `${USFWS}/6796/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Rock Pigeon',
    scientific_name: 'Columba livia',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'high',
    image_url: `${USFWS}/7361/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mourning Dove',
    scientific_name: 'Zenaida macroura',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${USFWS}/7372/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Crow',
    scientific_name: 'Corvus brachyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 450,
    strike_risk: 'medium',
    image_url: `${USFWS}/7330/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Kestrel',
    scientific_name: 'Falco sparverius',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${USFWS}/7468/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Owl',
    scientific_name: 'Tyto alba',
    group: 'bird', size_category: 'medium', mean_mass_g: 460,
    strike_risk: 'medium',
    image_url: `${USFWS}/8038/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Killdeer',
    scientific_name: 'Charadrius vociferus',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${USFWS}/4371/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Nighthawk',
    scientific_name: 'Chordeiles minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${USFWS}/7938/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Peregrine Falcon',
    scientific_name: 'Falco peregrinus',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'high',
    image_url: `${USFWS}/7474/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Short-eared Owl',
    scientific_name: 'Asio flammeus',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${USFWS}/8066/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Robin',
    scientific_name: 'Turdus migratorius',
    group: 'bird', size_category: 'medium', mean_mass_g: 77,
    strike_risk: 'medium',
    image_url: `${USFWS}/7691/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Mockingbird',
    scientific_name: 'Mimus polyglottos',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${USFWS}/7680/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue Jay',
    scientific_name: 'Cyanocitta cristata',
    group: 'bird', size_category: 'medium', mean_mass_g: 90,
    strike_risk: 'low',
    image_url: `${USFWS}/7326/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Flicker',
    scientific_name: 'Colaptes auratus',
    group: 'bird', size_category: 'medium', mean_mass_g: 130,
    strike_risk: 'medium',
    image_url: `${USFWS}/8000/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-winged Blackbird',
    scientific_name: 'Agelaius phoeniceus',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${USFWS}/7205/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Grackle',
    scientific_name: 'Quiscalus quiscula',
    group: 'bird', size_category: 'medium', mean_mass_g: 115,
    strike_risk: 'medium',
    image_url: `${USFWS}/7215/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Meadowlark',
    scientific_name: 'Sturnella magna',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${USFWS}/7218/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown-headed Cowbird',
    scientific_name: 'Molothrus ater',
    group: 'bird', size_category: 'medium', mean_mass_g: 44,
    strike_risk: 'low',
    image_url: `${USFWS}/7210/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great-tailed Grackle',
    scientific_name: 'Quiscalus mexicanus',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${USFWS}/7217/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cattle Egret',
    scientific_name: 'Bubulcus ibis',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${USFWS}/6876/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green Heron',
    scientific_name: 'Butorides virescens',
    group: 'bird', size_category: 'medium', mean_mass_g: 210,
    strike_risk: 'medium',
    image_url: `${USFWS}/6895/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-crowned Night-Heron',
    scientific_name: 'Nycticorax nycticorax',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'medium',
    image_url: `${USFWS}/6903/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Chimney Swift',
    scientific_name: 'Chaetura pelagica',
    group: 'bird', size_category: 'medium', mean_mass_g: 23,
    strike_risk: 'low',
    image_url: `${USFWS}/7928/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Scissor-tailed Flycatcher',
    scientific_name: 'Tyrannus forficatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 43,
    strike_risk: 'low',
    image_url: `${USFWS}/7633/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Loggerhead Shrike',
    scientific_name: 'Lanius ludovicianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${USFWS}/7670/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mississippi Kite',
    scientific_name: 'Ictinia mississippiensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 290,
    strike_risk: 'medium',
    image_url: `${USFWS}/7507/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Upland Sandpiper',
    scientific_name: 'Bartramia longicauda',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${USFWS}/4358/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eurasian Collared-Dove',
    scientific_name: 'Streptopelia decaocto',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${USFWS}/7369/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Boat-tailed Grackle',
    scientific_name: 'Quiscalus major',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: null,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Black-backed Gull',
    scientific_name: 'Larus marinus',
    group: 'bird', size_category: 'large', mean_mass_g: 1700,
    strike_risk: 'high',
    image_url: `${USFWS}/6808/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bonaparte\'s Gull',
    scientific_name: 'Chroicocephalus philadelphia',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${USFWS}/6792/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Small (<100g) — Low Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'European Starling',
    scientific_name: 'Sturnus vulgaris',
    group: 'bird', size_category: 'small', mean_mass_g: 80,
    strike_risk: 'high', // Flocking behavior increases risk
    image_url: `${USFWS}/7700/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Horned Lark',
    scientific_name: 'Eremophila alpestris',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Common on airfields
    image_url: `${USFWS}/7649/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Swallow',
    scientific_name: 'Hirundo rustica',
    group: 'bird', size_category: 'small', mean_mass_g: 19,
    strike_risk: 'medium',
    image_url: `${USFWS}/7584/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Sparrow',
    scientific_name: 'Passer domesticus',
    group: 'bird', size_category: 'small', mean_mass_g: 28,
    strike_risk: 'low',
    image_url: `${USFWS}/7697/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Song Sparrow',
    scientific_name: 'Melospiza melodia',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${USFWS}/7254/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Savannah Sparrow',
    scientific_name: 'Passerculus sandwichensis',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'low',
    image_url: `${USFWS}/7248/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cliff Swallow',
    scientific_name: 'Petrochelidon pyrrhonota',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'medium',
    image_url: `${USFWS}/7590/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Tree Swallow',
    scientific_name: 'Tachycineta bicolor',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'medium',
    image_url: `${USFWS}/7598/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Bluebird',
    scientific_name: 'Sialia sialis',
    group: 'bird', size_category: 'small', mean_mass_g: 30,
    strike_risk: 'low',
    image_url: `${USFWS}/7684/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Purple Martin',
    scientific_name: 'Progne subis',
    group: 'bird', size_category: 'small', mean_mass_g: 56,
    strike_risk: 'medium',
    image_url: `${USFWS}/7594/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Goldfinch',
    scientific_name: 'Spinus tristis',
    group: 'bird', size_category: 'small', mean_mass_g: 13,
    strike_risk: 'low',
    image_url: `${USFWS}/7232/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Finch',
    scientific_name: 'Haemorhous mexicanus',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${USFWS}/7226/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cedar Waxwing',
    scientific_name: 'Bombycilla cedrorum',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Flocking behavior
    image_url: `${USFWS}/7711/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // WATERFOWL — Medium/Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Black Duck',
    scientific_name: 'Anas rubripes',
    group: 'bird', size_category: 'large', mean_mass_g: 1200,
    strike_risk: 'high',
    image_url: `${USFWS}/9082/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Pintail',
    scientific_name: 'Anas acuta',
    group: 'bird', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'high',
    image_url: `${USFWS}/9104/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green-winged Teal',
    scientific_name: 'Anas crecca',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${USFWS}/9118/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue-winged Teal',
    scientific_name: 'Spatula discors',
    group: 'bird', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${USFWS}/9114/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wood Duck',
    scientific_name: 'Aix sponsa',
    group: 'bird', size_category: 'medium', mean_mass_g: 680,
    strike_risk: 'medium',
    image_url: `${USFWS}/9072/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // SHOREBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Woodcock',
    scientific_name: 'Scolopax minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${USFWS}/4345/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wilson\'s Snipe',
    scientific_name: 'Gallinago delicata',
    group: 'bird', size_category: 'medium', mean_mass_g: 105,
    strike_risk: 'medium',
    image_url: `${USFWS}/4389/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Semipalmated Plover',
    scientific_name: 'Charadrius semipalmatus',
    group: 'bird', size_category: 'small', mean_mass_g: 47,
    strike_risk: 'low',
    image_url: `${USFWS}/4367/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // GAMEBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Ring-necked Pheasant',
    scientific_name: 'Phasianus colchicus',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${USFWS}/8747/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Bobwhite',
    scientific_name: 'Colinus virginianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 175,
    strike_risk: 'medium',
    image_url: `${USFWS}/8741/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'White-tailed Deer',
    scientific_name: 'Odocoileus virginianus',
    group: 'mammal', size_category: 'large', mean_mass_g: 68000,
    strike_risk: 'critical',
    image_url: `${USFWS}/5005/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mule Deer',
    scientific_name: 'Odocoileus hemionus',
    group: 'mammal', size_category: 'large', mean_mass_g: 70000,
    strike_risk: 'critical',
    image_url: `${USFWS}/5010/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Coyote',
    scientific_name: 'Canis latrans',
    group: 'mammal', size_category: 'large', mean_mass_g: 14000,
    strike_risk: 'critical',
    image_url: `${USFWS}/4905/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red Fox',
    scientific_name: 'Vulpes vulpes',
    group: 'mammal', size_category: 'large', mean_mass_g: 5000,
    strike_risk: 'high',
    image_url: `${USFWS}/4915/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Gray Fox',
    scientific_name: 'Urocyon cinereoargenteus',
    group: 'mammal', size_category: 'large', mean_mass_g: 4000,
    strike_risk: 'high',
    image_url: `${USFWS}/4911/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Feral Pig',
    scientific_name: 'Sus scrofa',
    group: 'mammal', size_category: 'large', mean_mass_g: 80000,
    strike_risk: 'critical',
    image_url: `${USFWS}/5031/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Pronghorn',
    scientific_name: 'Antilocapra americana',
    group: 'mammal', size_category: 'large', mean_mass_g: 55000,
    strike_risk: 'critical',
    image_url: `${USFWS}/4998/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Medium/Small
  // ══════════════════════════════════════════════════
  {
    common_name: 'Eastern Cottontail',
    scientific_name: 'Sylvilagus floridanus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 1200,
    strike_risk: 'medium',
    image_url: `${USFWS}/4975/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Striped Skunk',
    scientific_name: 'Mephitis mephitis',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3200,
    strike_risk: 'medium',
    image_url: `${USFWS}/4960/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Raccoon',
    scientific_name: 'Procyon lotor',
    group: 'mammal', size_category: 'medium', mean_mass_g: 6000,
    strike_risk: 'high',
    image_url: `${USFWS}/4946/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Virginia Opossum',
    scientific_name: 'Didelphis virginiana',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3000,
    strike_risk: 'medium',
    image_url: `${USFWS}/4865/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Nine-banded Armadillo',
    scientific_name: 'Dasypus novemcinctus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 5500,
    strike_risk: 'medium',
    image_url: `${USFWS}/4860/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Woodchuck',
    scientific_name: 'Marmota monax',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3600,
    strike_risk: 'medium',
    image_url: `${USFWS}/4932/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Thirteen-lined Ground Squirrel',
    scientific_name: 'Ictidomys tridecemlineatus',
    group: 'mammal', size_category: 'small', mean_mass_g: 170,
    strike_risk: 'low',
    image_url: `${USFWS}/4928/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-tailed Prairie Dog',
    scientific_name: 'Cynomys ludovicianus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'medium',
    image_url: `${USFWS}/4920/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // REPTILES
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Alligator',
    scientific_name: 'Alligator mississippiensis',
    group: 'reptile', size_category: 'large', mean_mass_g: 200000,
    strike_risk: 'critical',
    image_url: `${USFWS}/4777/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Snapping Turtle',
    scientific_name: 'Chelydra serpentina',
    group: 'reptile', size_category: 'large', mean_mass_g: 10000,
    strike_risk: 'high',
    image_url: `${USFWS}/4800/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Box Turtle',
    scientific_name: 'Terrapene carolina',
    group: 'reptile', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${USFWS}/4815/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Rat Snake',
    scientific_name: 'Pantherophis obsoletus',
    group: 'reptile', size_category: 'medium', mean_mass_g: 700,
    strike_risk: 'low',
    image_url: null,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BATS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Brazilian Free-tailed Bat',
    scientific_name: 'Tadarida brasiliensis',
    group: 'bat', size_category: 'small', mean_mass_g: 12,
    strike_risk: 'medium', // Large colonies near airfields
    image_url: `${USFWS}/4841/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Big Brown Bat',
    scientific_name: 'Eptesicus fuscus',
    group: 'bat', size_category: 'small', mean_mass_g: 16,
    strike_risk: 'low',
    image_url: `${USFWS}/4835/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Little Brown Bat',
    scientific_name: 'Myotis lucifugus',
    group: 'bat', size_category: 'small', mean_mass_g: 8,
    strike_risk: 'low',
    image_url: `${USFWS}/4845/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Hoary Bat',
    scientific_name: 'Lasiurus cinereus',
    group: 'bat', size_category: 'small', mean_mass_g: 26,
    strike_risk: 'low',
    image_url: `${USFWS}/4849/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Red Bat',
    scientific_name: 'Lasiurus borealis',
    group: 'bat', size_category: 'small', mean_mass_g: 10,
    strike_risk: 'low',
    image_url: `${USFWS}/4838/default.jpg`,
    image_credit: 'USFWS',
  },
]
