// Wildlife Species Reference Database
// ~80 common airfield hazard species curated from FAA National Wildlife Strike Database
// Photo URLs sourced from USFWS National Digital Library (public domain)
// Primary: IIIF endpoint at digitalmedia.fws.gov (CONTENTdm natdiglib collection)
// Fallback: fws.gov/media pages (Drupal CMS)
// All images are public domain (U.S. Government work)

export type WildlifeSpecies = {
  common_name: string
  scientific_name: string
  group: 'bird' | 'mammal' | 'reptile' | 'bat'
  size_category: 'small' | 'medium' | 'large'
  mean_mass_g: number
  strike_risk: 'low' | 'medium' | 'high' | 'critical'
  image_url: string | null
  image_credit: string
}

// USFWS NCTC Image Library — IIIF endpoint (800px wide thumbnails)
const IIIF = 'https://digitalmedia.fws.gov/digital/iiif/natdiglib'
// Generates URL: {IIIF}/{ID}/full/800,/0/default.jpg

export const WILDLIFE_SPECIES: WildlifeSpecies[] = [
  // ══════════════════════════════════════════════════
  // BIRDS — Large (>1kg) — High/Critical Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Canada Goose',
    scientific_name: 'Branta canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 3600,
    strike_risk: 'critical',
    image_url: `${IIIF}/1489/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snow Goose',
    scientific_name: 'Anser caerulescens',
    group: 'bird', size_category: 'large', mean_mass_g: 2700,
    strike_risk: 'critical',
    image_url: `${IIIF}/15275/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Turkey Vulture',
    scientific_name: 'Cathartes aura',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'critical',
    image_url: `${IIIF}/1611/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Vulture',
    scientific_name: 'Coragyps atratus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${IIIF}/7747/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-tailed Hawk',
    scientific_name: 'Buteo jamaicensis',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/18455/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Blue Heron',
    scientific_name: 'Ardea herodias',
    group: 'bird', size_category: 'large', mean_mass_g: 2400,
    strike_risk: 'high',
    image_url: `${IIIF}/6891/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Horned Owl',
    scientific_name: 'Bubo virginianus',
    group: 'bird', size_category: 'large', mean_mass_g: 1400,
    strike_risk: 'high',
    image_url: `${IIIF}/8058/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bald Eagle',
    scientific_name: 'Haliaeetus leucocephalus',
    group: 'bird', size_category: 'large', mean_mass_g: 4300,
    strike_risk: 'critical',
    image_url: `${IIIF}/6773/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Osprey',
    scientific_name: 'Pandion haliaetus',
    group: 'bird', size_category: 'large', mean_mass_g: 1600,
    strike_risk: 'high',
    image_url: `${IIIF}/8094/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Sandhill Crane',
    scientific_name: 'Antigone canadensis',
    group: 'bird', size_category: 'large', mean_mass_g: 4500,
    strike_risk: 'critical',
    image_url: `${IIIF}/5590/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Egret',
    scientific_name: 'Ardea alba',
    group: 'bird', size_category: 'large', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${IIIF}/6879/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wild Turkey',
    scientific_name: 'Meleagris gallopavo',
    group: 'bird', size_category: 'large', mean_mass_g: 5800,
    strike_risk: 'critical',
    image_url: `${IIIF}/8756/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Double-crested Cormorant',
    scientific_name: 'Nannopterum auritum',
    group: 'bird', size_category: 'large', mean_mass_g: 1800,
    strike_risk: 'high',
    image_url: `${IIIF}/7289/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown Pelican',
    scientific_name: 'Pelecanus occidentalis',
    group: 'bird', size_category: 'large', mean_mass_g: 3500,
    strike_risk: 'critical',
    image_url: `${IIIF}/3771/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American White Pelican',
    scientific_name: 'Pelecanus erythrorhynchos',
    group: 'bird', size_category: 'large', mean_mass_g: 7000,
    strike_risk: 'critical',
    image_url: `${IIIF}/8136/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-shouldered Hawk',
    scientific_name: 'Buteo lineatus',
    group: 'bird', size_category: 'large', mean_mass_g: 600,
    strike_risk: 'high',
    image_url: `${IIIF}/7515/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cooper\'s Hawk',
    scientific_name: 'Accipiter cooperii',
    group: 'bird', size_category: 'large', mean_mass_g: 440,
    strike_risk: 'high',
    image_url: `${IIIF}/7494/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Harrier',
    scientific_name: 'Circus hudsonius',
    group: 'bird', size_category: 'large', mean_mass_g: 400,
    strike_risk: 'high',
    image_url: `${IIIF}/7501/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Snowy Owl',
    scientific_name: 'Bubo scandiacus',
    group: 'bird', size_category: 'large', mean_mass_g: 2000,
    strike_risk: 'critical',
    image_url: `${IIIF}/8072/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Medium (100g–1kg) — Medium Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'Mallard',
    scientific_name: 'Anas platyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/9090/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Herring Gull',
    scientific_name: 'Larus argentatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 1000,
    strike_risk: 'high',
    image_url: `${IIIF}/6800/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Ring-billed Gull',
    scientific_name: 'Larus delawarensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 500,
    strike_risk: 'high',
    image_url: `${IIIF}/6804/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Laughing Gull',
    scientific_name: 'Leucophaeus atricilla',
    group: 'bird', size_category: 'medium', mean_mass_g: 330,
    strike_risk: 'high',
    image_url: `${IIIF}/6796/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Rock Pigeon',
    scientific_name: 'Columba livia',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'high',
    image_url: `${IIIF}/17706/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mourning Dove',
    scientific_name: 'Zenaida macroura',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${IIIF}/7372/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Crow',
    scientific_name: 'Corvus brachyrhynchos',
    group: 'bird', size_category: 'medium', mean_mass_g: 450,
    strike_risk: 'medium',
    image_url: `${IIIF}/7330/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Kestrel',
    scientific_name: 'Falco sparverius',
    group: 'bird', size_category: 'medium', mean_mass_g: 120,
    strike_risk: 'medium',
    image_url: `${IIIF}/776/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Owl',
    scientific_name: 'Tyto alba',
    group: 'bird', size_category: 'medium', mean_mass_g: 460,
    strike_risk: 'medium',
    image_url: `${IIIF}/8038/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Killdeer',
    scientific_name: 'Charadrius vociferus',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${IIIF}/12311/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Nighthawk',
    scientific_name: 'Chordeiles minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${IIIF}/7938/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Peregrine Falcon',
    scientific_name: 'Falco peregrinus',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'high',
    image_url: `${IIIF}/7474/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Short-eared Owl',
    scientific_name: 'Asio flammeus',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/8066/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Robin',
    scientific_name: 'Turdus migratorius',
    group: 'bird', size_category: 'medium', mean_mass_g: 77,
    strike_risk: 'medium',
    image_url: `${IIIF}/7691/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Mockingbird',
    scientific_name: 'Mimus polyglottos',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${IIIF}/7680/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue Jay',
    scientific_name: 'Cyanocitta cristata',
    group: 'bird', size_category: 'medium', mean_mass_g: 90,
    strike_risk: 'low',
    image_url: `${IIIF}/7326/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Flicker',
    scientific_name: 'Colaptes auratus',
    group: 'bird', size_category: 'medium', mean_mass_g: 130,
    strike_risk: 'medium',
    image_url: `${IIIF}/8000/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red-winged Blackbird',
    scientific_name: 'Agelaius phoeniceus',
    group: 'bird', size_category: 'medium', mean_mass_g: 65,
    strike_risk: 'medium',
    image_url: `${IIIF}/7205/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Grackle',
    scientific_name: 'Quiscalus quiscula',
    group: 'bird', size_category: 'medium', mean_mass_g: 115,
    strike_risk: 'medium',
    image_url: `${IIIF}/7215/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Meadowlark',
    scientific_name: 'Sturnella magna',
    group: 'bird', size_category: 'medium', mean_mass_g: 95,
    strike_risk: 'medium',
    image_url: `${IIIF}/7218/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Brown-headed Cowbird',
    scientific_name: 'Molothrus ater',
    group: 'bird', size_category: 'medium', mean_mass_g: 44,
    strike_risk: 'low',
    image_url: `${IIIF}/7210/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great-tailed Grackle',
    scientific_name: 'Quiscalus mexicanus',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/7217/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cattle Egret',
    scientific_name: 'Bubulcus ibis',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/6876/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green Heron',
    scientific_name: 'Butorides virescens',
    group: 'bird', size_category: 'medium', mean_mass_g: 210,
    strike_risk: 'medium',
    image_url: `${IIIF}/6895/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-crowned Night-Heron',
    scientific_name: 'Nycticorax nycticorax',
    group: 'bird', size_category: 'medium', mean_mass_g: 800,
    strike_risk: 'medium',
    image_url: `${IIIF}/6903/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Chimney Swift',
    scientific_name: 'Chaetura pelagica',
    group: 'bird', size_category: 'medium', mean_mass_g: 23,
    strike_risk: 'low',
    image_url: `${IIIF}/7928/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Scissor-tailed Flycatcher',
    scientific_name: 'Tyrannus forficatus',
    group: 'bird', size_category: 'medium', mean_mass_g: 43,
    strike_risk: 'low',
    image_url: `${IIIF}/7633/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Loggerhead Shrike',
    scientific_name: 'Lanius ludovicianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 48,
    strike_risk: 'low',
    image_url: `${IIIF}/7670/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mississippi Kite',
    scientific_name: 'Ictinia mississippiensis',
    group: 'bird', size_category: 'medium', mean_mass_g: 290,
    strike_risk: 'medium',
    image_url: `${IIIF}/7507/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Upland Sandpiper',
    scientific_name: 'Bartramia longicauda',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${IIIF}/4358/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eurasian Collared-Dove',
    scientific_name: 'Streptopelia decaocto',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/7369/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Boat-tailed Grackle',
    scientific_name: 'Quiscalus major',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: null,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Great Black-backed Gull',
    scientific_name: 'Larus marinus',
    group: 'bird', size_category: 'large', mean_mass_g: 1700,
    strike_risk: 'high',
    image_url: `${IIIF}/6808/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Bonaparte\'s Gull',
    scientific_name: 'Chroicocephalus philadelphia',
    group: 'bird', size_category: 'medium', mean_mass_g: 200,
    strike_risk: 'medium',
    image_url: `${IIIF}/6792/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BIRDS — Small (<100g) — Low Strike Risk
  // ══════════════════════════════════════════════════
  {
    common_name: 'European Starling',
    scientific_name: 'Sturnus vulgaris',
    group: 'bird', size_category: 'small', mean_mass_g: 80,
    strike_risk: 'high', // Flocking behavior increases risk
    image_url: `${IIIF}/7700/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Horned Lark',
    scientific_name: 'Eremophila alpestris',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Common on airfields
    image_url: `${IIIF}/7649/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Barn Swallow',
    scientific_name: 'Hirundo rustica',
    group: 'bird', size_category: 'small', mean_mass_g: 19,
    strike_risk: 'medium',
    image_url: `${IIIF}/7584/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Sparrow',
    scientific_name: 'Passer domesticus',
    group: 'bird', size_category: 'small', mean_mass_g: 28,
    strike_risk: 'low',
    image_url: `${IIIF}/7697/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Song Sparrow',
    scientific_name: 'Melospiza melodia',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${IIIF}/7254/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Savannah Sparrow',
    scientific_name: 'Passerculus sandwichensis',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'low',
    image_url: `${IIIF}/7248/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cliff Swallow',
    scientific_name: 'Petrochelidon pyrrhonota',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'medium',
    image_url: `${IIIF}/7590/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Tree Swallow',
    scientific_name: 'Tachycineta bicolor',
    group: 'bird', size_category: 'small', mean_mass_g: 20,
    strike_risk: 'medium',
    image_url: `${IIIF}/7598/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Bluebird',
    scientific_name: 'Sialia sialis',
    group: 'bird', size_category: 'small', mean_mass_g: 30,
    strike_risk: 'low',
    image_url: `${IIIF}/7684/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Purple Martin',
    scientific_name: 'Progne subis',
    group: 'bird', size_category: 'small', mean_mass_g: 56,
    strike_risk: 'medium',
    image_url: `${IIIF}/7594/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'American Goldfinch',
    scientific_name: 'Spinus tristis',
    group: 'bird', size_category: 'small', mean_mass_g: 13,
    strike_risk: 'low',
    image_url: `${IIIF}/7232/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'House Finch',
    scientific_name: 'Haemorhous mexicanus',
    group: 'bird', size_category: 'small', mean_mass_g: 22,
    strike_risk: 'low',
    image_url: `${IIIF}/7226/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Cedar Waxwing',
    scientific_name: 'Bombycilla cedrorum',
    group: 'bird', size_category: 'small', mean_mass_g: 32,
    strike_risk: 'medium', // Flocking behavior
    image_url: `${IIIF}/7711/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // WATERFOWL — Medium/Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Black Duck',
    scientific_name: 'Anas rubripes',
    group: 'bird', size_category: 'large', mean_mass_g: 1200,
    strike_risk: 'high',
    image_url: `${IIIF}/9082/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Pintail',
    scientific_name: 'Anas acuta',
    group: 'bird', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'high',
    image_url: `${IIIF}/9104/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Green-winged Teal',
    scientific_name: 'Anas crecca',
    group: 'bird', size_category: 'medium', mean_mass_g: 350,
    strike_risk: 'medium',
    image_url: `${IIIF}/9118/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Blue-winged Teal',
    scientific_name: 'Spatula discors',
    group: 'bird', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${IIIF}/9114/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wood Duck',
    scientific_name: 'Aix sponsa',
    group: 'bird', size_category: 'medium', mean_mass_g: 680,
    strike_risk: 'medium',
    image_url: `${IIIF}/9072/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // SHOREBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Woodcock',
    scientific_name: 'Scolopax minor',
    group: 'bird', size_category: 'medium', mean_mass_g: 170,
    strike_risk: 'medium',
    image_url: `${IIIF}/4345/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Wilson\'s Snipe',
    scientific_name: 'Gallinago delicata',
    group: 'bird', size_category: 'medium', mean_mass_g: 105,
    strike_risk: 'medium',
    image_url: `${IIIF}/4389/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Semipalmated Plover',
    scientific_name: 'Charadrius semipalmatus',
    group: 'bird', size_category: 'small', mean_mass_g: 47,
    strike_risk: 'low',
    image_url: `${IIIF}/4367/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // GAMEBIRDS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Ring-necked Pheasant',
    scientific_name: 'Phasianus colchicus',
    group: 'bird', size_category: 'large', mean_mass_g: 1100,
    strike_risk: 'high',
    image_url: `${IIIF}/8747/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Northern Bobwhite',
    scientific_name: 'Colinus virginianus',
    group: 'bird', size_category: 'medium', mean_mass_g: 175,
    strike_risk: 'medium',
    image_url: `${IIIF}/8741/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Large
  // ══════════════════════════════════════════════════
  {
    common_name: 'White-tailed Deer',
    scientific_name: 'Odocoileus virginianus',
    group: 'mammal', size_category: 'large', mean_mass_g: 68000,
    strike_risk: 'critical',
    image_url: `${IIIF}/17496/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Mule Deer',
    scientific_name: 'Odocoileus hemionus',
    group: 'mammal', size_category: 'large', mean_mass_g: 70000,
    strike_risk: 'critical',
    image_url: `${IIIF}/5010/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Coyote',
    scientific_name: 'Canis latrans',
    group: 'mammal', size_category: 'large', mean_mass_g: 14000,
    strike_risk: 'critical',
    image_url: `${IIIF}/11774/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Red Fox',
    scientific_name: 'Vulpes vulpes',
    group: 'mammal', size_category: 'large', mean_mass_g: 5000,
    strike_risk: 'high',
    image_url: `${IIIF}/4915/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Gray Fox',
    scientific_name: 'Urocyon cinereoargenteus',
    group: 'mammal', size_category: 'large', mean_mass_g: 4000,
    strike_risk: 'high',
    image_url: `${IIIF}/4911/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Feral Pig',
    scientific_name: 'Sus scrofa',
    group: 'mammal', size_category: 'large', mean_mass_g: 80000,
    strike_risk: 'critical',
    image_url: `${IIIF}/5031/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Pronghorn',
    scientific_name: 'Antilocapra americana',
    group: 'mammal', size_category: 'large', mean_mass_g: 55000,
    strike_risk: 'critical',
    image_url: `${IIIF}/4998/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // MAMMALS — Medium/Small
  // ══════════════════════════════════════════════════
  {
    common_name: 'Eastern Cottontail',
    scientific_name: 'Sylvilagus floridanus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 1200,
    strike_risk: 'medium',
    image_url: `${IIIF}/12317/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Striped Skunk',
    scientific_name: 'Mephitis mephitis',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3200,
    strike_risk: 'medium',
    image_url: `${IIIF}/4960/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Raccoon',
    scientific_name: 'Procyon lotor',
    group: 'mammal', size_category: 'medium', mean_mass_g: 6000,
    strike_risk: 'high',
    image_url: `${IIIF}/4946/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Virginia Opossum',
    scientific_name: 'Didelphis virginiana',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3000,
    strike_risk: 'medium',
    image_url: `${IIIF}/4865/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Nine-banded Armadillo',
    scientific_name: 'Dasypus novemcinctus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 5500,
    strike_risk: 'medium',
    image_url: `${IIIF}/4860/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Woodchuck',
    scientific_name: 'Marmota monax',
    group: 'mammal', size_category: 'medium', mean_mass_g: 3600,
    strike_risk: 'medium',
    image_url: `${IIIF}/4932/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Thirteen-lined Ground Squirrel',
    scientific_name: 'Ictidomys tridecemlineatus',
    group: 'mammal', size_category: 'small', mean_mass_g: 170,
    strike_risk: 'low',
    image_url: `${IIIF}/4928/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black-tailed Prairie Dog',
    scientific_name: 'Cynomys ludovicianus',
    group: 'mammal', size_category: 'medium', mean_mass_g: 900,
    strike_risk: 'medium',
    image_url: `${IIIF}/4920/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // REPTILES
  // ══════════════════════════════════════════════════
  {
    common_name: 'American Alligator',
    scientific_name: 'Alligator mississippiensis',
    group: 'reptile', size_category: 'large', mean_mass_g: 200000,
    strike_risk: 'critical',
    image_url: `${IIIF}/4777/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Common Snapping Turtle',
    scientific_name: 'Chelydra serpentina',
    group: 'reptile', size_category: 'large', mean_mass_g: 10000,
    strike_risk: 'high',
    image_url: `${IIIF}/4800/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Box Turtle',
    scientific_name: 'Terrapene carolina',
    group: 'reptile', size_category: 'medium', mean_mass_g: 400,
    strike_risk: 'medium',
    image_url: `${IIIF}/4815/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Black Rat Snake',
    scientific_name: 'Pantherophis obsoletus',
    group: 'reptile', size_category: 'medium', mean_mass_g: 700,
    strike_risk: 'low',
    image_url: null,
    image_credit: 'USFWS',
  },

  // ══════════════════════════════════════════════════
  // BATS
  // ══════════════════════════════════════════════════
  {
    common_name: 'Brazilian Free-tailed Bat',
    scientific_name: 'Tadarida brasiliensis',
    group: 'bat', size_category: 'small', mean_mass_g: 12,
    strike_risk: 'medium', // Large colonies near airfields
    image_url: `${IIIF}/4841/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Big Brown Bat',
    scientific_name: 'Eptesicus fuscus',
    group: 'bat', size_category: 'small', mean_mass_g: 16,
    strike_risk: 'low',
    image_url: `${IIIF}/4835/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Little Brown Bat',
    scientific_name: 'Myotis lucifugus',
    group: 'bat', size_category: 'small', mean_mass_g: 8,
    strike_risk: 'low',
    image_url: `${IIIF}/4845/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Hoary Bat',
    scientific_name: 'Lasiurus cinereus',
    group: 'bat', size_category: 'small', mean_mass_g: 26,
    strike_risk: 'low',
    image_url: `${IIIF}/4849/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
  {
    common_name: 'Eastern Red Bat',
    scientific_name: 'Lasiurus borealis',
    group: 'bat', size_category: 'small', mean_mass_g: 10,
    strike_risk: 'low',
    image_url: `${IIIF}/4838/full/800,/0/default.jpg`,
    image_credit: 'USFWS',
  },
]
