import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { AgingDiscrepanciesData } from './aging-discrepancies-data'
import { formatDiscrepancyType } from './open-discrepancies-data'

interface Options {
  generatedBy: string
  baseName?: string
  baseIcao?: string
}

const STATUS_LABELS: Record<string, string> = {
  submitted_to_afm: 'Submitted to AFM',
  submitted_to_ces: 'Submitted to CES',
  awaiting_action_by_ces: 'Awaiting CES Action',
  work_completed_awaiting_verification: 'Awaiting Verification',
  open: 'Open',
}

const SEVERITY_LABELS: Record<string, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  no: 'None',
}

export function generateAgingDiscrepanciesPdf(data: AgingDiscrepanciesData, opts: Options) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 12
  const contentWidth = pageWidth - margin * 2
  let y = margin
  let pageNum = 1

  function addPageNumber() {
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 6, { align: 'center' })
  }

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 14) {
      addPageNumber()
      doc.addPage()
      pageNum++
      y = margin
    }
  }

  function sectionHeader(title: string) {
    checkPageBreak(14)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0)
    doc.text(title, margin, y)
    y += 1
    doc.setDrawColor(0)
    doc.setLineWidth(0.4)
    doc.line(margin, y, margin + contentWidth, y)
    y += 5
    doc.setFont('helvetica', 'normal')
  }

  // ── HEADER ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text('GLIDEPATH', margin, y)
  y += 5

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.setFont('helvetica', 'bold')
  doc.text('AGING DISCREPANCIES REPORT', margin, y)
  y += 6

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(opts.baseName && opts.baseIcao ? `${opts.baseName} (${opts.baseIcao})` : 'Airfield Operations', margin, y)
  y += 5

  doc.setFontSize(9)
  doc.setTextColor(60)
  const now = new Date()
  doc.text(`As of: ${now.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`, margin, y)
  y += 4
  doc.text(`Generated by: ${opts.generatedBy}`, margin, y)
  y += 4
  doc.text(`Total Open: ${data.summary.total}`, margin, y)
  if (data.summary.avgDaysOpen !== null) {
    doc.text(`   |   Avg Days Open: ${data.summary.avgDaysOpen}`, margin + 35, y)
  }
  y += 7

  // ── SUMMARY ──
  sectionHeader('AGING SUMMARY')

  // Tier summary table
  const tierSummaryBody = data.tiers.map((t) => [
    t.label,
    t.discrepancies.length.toString(),
    data.summary.total > 0
      ? `${Math.round((t.discrepancies.length / data.summary.total) * 100)}%`
      : '0%',
  ])

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Aging Tier', 'Count', '% of Total']],
    body: tierSummaryBody,
    styles: { fontSize: 8, cellPadding: 2, textColor: [0, 0, 0] },
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 25, halign: 'center' },
      2: { cellWidth: 25, halign: 'center' },
    },
    didParseCell: (hookData) => {
      if (hookData.section !== 'body') return
      // Color-code tiers with non-zero counts
      const tier = data.tiers[hookData.row.index]
      if (tier && tier.discrepancies.length > 0 && hookData.column.index === 1) {
        if (tier.min >= 31) {
          hookData.cell.styles.textColor = [220, 38, 38]
          hookData.cell.styles.fontStyle = 'bold'
        }
      }
    },
  })
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4

  // By severity
  doc.setFontSize(9)
  doc.setTextColor(0)
  const sevEntries = Object.entries(data.summary.bySeverity).sort((a, b) => b[1] - a[1])
  if (sevEntries.length > 0) {
    const sevText = 'By Severity: ' + sevEntries.map(([s, c]) => `${SEVERITY_LABELS[s] || s} (${c})`).join(', ')
    const sevLines = doc.splitTextToSize(sevText, contentWidth)
    doc.text(sevLines, margin, y)
    y += sevLines.length * 4
  }

  // By shop
  if (data.summary.byShop.length > 0) {
    const shopText = 'By Shop: ' + data.summary.byShop.map((s) => `${s.shop} (${s.count})`).join(', ')
    const shopLines = doc.splitTextToSize(shopText, contentWidth)
    doc.text(shopLines, margin, y)
    y += shopLines.length * 4
  }

  if (data.summary.oldest) {
    doc.text(`Oldest: ${data.summary.oldest.display_id} - ${data.summary.oldest.title} (${data.summary.oldest.days_open} days)`, margin, y)
    y += 5
  }
  y += 3

  // ── DETAIL TABLES PER TIER (only tiers with items) ──
  for (const tier of data.tiers) {
    if (tier.discrepancies.length === 0) continue

    sectionHeader(`${tier.label.toUpperCase()} (${tier.discrepancies.length})`)

    const body = tier.discrepancies.map((d) => {
      const lastUpdate = d.last_update_at
        ? new Date(d.last_update_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
        : ''
      return [
        d.display_id,
        d.title,
        formatDiscrepancyType(d.type),
        SEVERITY_LABELS[d.severity] || d.severity,
        d.location_text,
        d.assigned_shop || 'Unassigned',
        d.work_order_number || '',
        STATUS_LABELS[d.current_status] || d.current_status,
        d.days_open.toString(),
        lastUpdate,
      ]
    })

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['ID', 'Title', 'Type', 'Severity', 'Location', 'Shop', 'W/O #', 'Status', 'Days', 'Last Update']],
      body,
      styles: { fontSize: 7, cellPadding: 1.5, textColor: [0, 0, 0] },
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7 },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        0: { cellWidth: 18 },
        1: { cellWidth: 32 },
        8: { cellWidth: 10, halign: 'center' },
      },
      didParseCell: (hookData) => {
        if (hookData.section !== 'body') return
        const disc = tier.discrepancies[hookData.row.index]
        if (!disc) return
        // Red for severity critical/high
        if (hookData.column.index === 3 && (disc.severity === 'critical' || disc.severity === 'high')) {
          hookData.cell.styles.textColor = [220, 38, 38]
          hookData.cell.styles.fontStyle = 'bold'
        }
      },
    })
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6
  }

  // Footer
  addPageNumber()

  const dateStr = now.toISOString().split('T')[0]
  const filename = `${opts.baseIcao ?? 'AIRFIELD'}_Aging_Discrepancies_${dateStr}.pdf`
  return { doc, filename }
}
