import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { DiscrepancyTrendsData } from './discrepancy-trends-data'
import { formatDiscrepancyType } from './open-discrepancies-data'

interface Options {
  generatedBy: string
}

export function generateDiscrepancyTrendsPdf(data: DiscrepancyTrendsData, opts: Options) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 12
  const contentWidth = pageWidth - margin * 2
  let y = margin
  let pageNum = 1

  function addPageNumber() {
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 6, { align: 'center' })
  }

  function sectionHeader(title: string) {
    if (y + 14 > pageHeight - 14) {
      addPageNumber()
      doc.addPage()
      pageNum++
      y = margin
    }
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0)
    doc.text(title, margin, y)
    y += 1
    doc.setDrawColor(0)
    doc.setLineWidth(0.4)
    doc.line(margin, y, margin + contentWidth, y)
    y += 5
    doc.setFont('helvetica', 'normal')
  }

  // ── HEADER ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text('GLIDEPATH', margin, y)
  y += 5

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.setFont('helvetica', 'bold')
  doc.text('DISCREPANCY TRENDS REPORT', margin, y)
  y += 6

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Selfridge ANGB (KMTC)', margin, y)
  y += 5

  doc.setFontSize(9)
  doc.setTextColor(60)
  const now = new Date()
  doc.text(`Period: ${data.periodLabel}`, margin, y)
  y += 4
  doc.text(`Generated: ${now.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`, margin, y)
  y += 4
  doc.text(`Generated by: ${opts.generatedBy}`, margin, y)
  y += 7

  // ── SUMMARY ──
  sectionHeader('SUMMARY')

  doc.setFontSize(9)
  doc.setTextColor(0)
  const { summary } = data
  doc.text(`Opened: ${summary.totalOpened}     Closed: ${summary.totalClosed}     Net Change: ${summary.net >= 0 ? '+' : ''}${summary.net}`, margin, y)
  y += 5
  if (summary.avgDaysToClose !== null) {
    doc.text(`Average Days to Close: ${summary.avgDaysToClose}`, margin, y)
    y += 5
  }

  // Top areas
  if (summary.topAreas.length > 0) {
    const areasText = 'Top Areas: ' + summary.topAreas.map((a) => `${a.area} (${a.count})`).join(', ')
    const areaLines = doc.splitTextToSize(areasText, contentWidth)
    doc.text(areaLines, margin, y)
    y += areaLines.length * 4
  }

  // Top types
  if (summary.topTypes.length > 0) {
    const typesText = 'Top Types: ' + summary.topTypes.map((t) => `${formatDiscrepancyType(t.type)} (${t.count})`).join(', ')
    const typeLines = doc.splitTextToSize(typesText, contentWidth)
    doc.text(typeLines, margin, y)
    y += typeLines.length * 4
  }
  y += 3

  // ── TREND TABLE ──
  sectionHeader('OPENED vs CLOSED BY PERIOD')

  const tableBody = data.buckets.map((b) => [
    b.label,
    b.opened.toString(),
    b.closed.toString(),
    `${b.net >= 0 ? '+' : ''}${b.net}`,
  ])

  // Add totals row
  tableBody.push([
    'TOTAL',
    summary.totalOpened.toString(),
    summary.totalClosed.toString(),
    `${summary.net >= 0 ? '+' : ''}${summary.net}`,
  ])

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Period', 'Opened', 'Closed', 'Net Change']],
    body: tableBody,
    styles: { fontSize: 8, cellPadding: 2, textColor: [0, 0, 0] },
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30, halign: 'center' },
      2: { cellWidth: 30, halign: 'center' },
      3: { cellWidth: 30, halign: 'center' },
    },
    didParseCell: (hookData) => {
      if (hookData.section !== 'body') return
      // Bold totals row
      if (hookData.row.index === tableBody.length - 1) {
        hookData.cell.styles.fontStyle = 'bold'
      }
      // Color the net change column
      if (hookData.column.index === 3 && hookData.row.index < tableBody.length - 1) {
        const bucket = data.buckets[hookData.row.index]
        if (bucket && bucket.net > 0) {
          hookData.cell.styles.textColor = [220, 38, 38] // red = growing backlog
        } else if (bucket && bucket.net < 0) {
          hookData.cell.styles.textColor = [34, 197, 94] // green = shrinking backlog
        }
      }
    },
  })

  // Footer
  addPageNumber()

  const dateStr = now.toISOString().split('T')[0]
  doc.save(`KMTC_Discrepancy_Trends_${dateStr}.pdf`)
}
