import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { LightingReportData } from './lighting-report-data'
import { formatFeatureType } from '@/lib/supabase/infrastructure-features'
import { formatZuluDateTime, formatZuluDate } from '@/lib/utils'
import { getAlertTier, ALERT_TIER_CONFIG } from '@/lib/outage-rules'

interface Options {
  generatedBy: string
  baseName?: string
  baseIcao?: string
}

export function generateLightingReportPdf(data: LightingReportData, opts: Options) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 12
  const contentWidth = pageWidth - margin * 2
  let y = margin
  const now = new Date()

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 14) {
      doc.addPage()
      y = margin
    }
  }

  function sectionHeader(title: string) {
    checkPageBreak(14)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0)
    doc.text(title, margin, y)
    y += 1
    doc.setDrawColor(0)
    doc.setLineWidth(0.4)
    doc.line(margin, y, margin + contentWidth, y)
    y += 5
    doc.setFont('helvetica', 'normal')
  }

  // ── HEADER ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text('GLIDEPATH', margin, y)
  y += 5

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.setFont('helvetica', 'bold')
  doc.text('AIRFIELD LIGHTING REPORT', margin, y)
  y += 6

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    opts.baseName && opts.baseIcao
      ? `${opts.baseName} (${opts.baseIcao})`
      : 'Airfield Operations',
    margin,
    y,
  )
  y += 5

  doc.setFontSize(9)
  doc.setTextColor(60)
  doc.text(`Generated: ${formatZuluDateTime(now)}`, margin, y)
  y += 4
  doc.text(`Generated by: ${opts.generatedBy}`, margin, y)
  y += 7

  // ── SUMMARY ──
  sectionHeader('SUMMARY')

  const inopPct = data.totalFeatures > 0
    ? ((data.totalInoperative / data.totalFeatures) * 100).toFixed(1)
    : '0.0'

  doc.setFontSize(9)
  doc.setTextColor(0)
  doc.text(`Total Features: ${data.totalFeatures}`, margin, y)
  y += 4
  doc.text(`Inoperative: ${data.totalInoperative}`, margin, y)
  y += 4
  doc.text(`Inoperative Rate: ${inopPct}%`, margin, y)
  y += 7

  // ── SYSTEM HEALTH TABLE ──
  if (data.systemHealths.length > 0) {
    sectionHeader('SYSTEM HEALTH')

    const healthBody = data.systemHealths.map((h) => {
      const tier = getAlertTier(h)
      const tierConfig = ALERT_TIER_CONFIG[tier]
      return [
        h.systemName,
        tierConfig.label,
        `${h.inoperativeFeatures} / ${h.totalFeatures}`,
        `${h.overallOutagePct}%`,
      ]
    })

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['System Name', 'Status', 'Inop / Total', 'Outage %']],
      body: healthBody,
      styles: { fontSize: 8, cellPadding: 2, textColor: [0, 0, 0] },
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        0: { cellWidth: 70 },
        2: { halign: 'center' },
        3: { halign: 'center' },
      },
      didParseCell: (hookData) => {
        if (hookData.section !== 'body') return
        if (hookData.column.index === 1) {
          const rowIdx = hookData.row.index
          const health = data.systemHealths[rowIdx]
          if (health) {
            const tier = getAlertTier(health)
            if (tier === 'red' || tier === 'black') {
              hookData.cell.styles.textColor = [239, 68, 68]
              hookData.cell.styles.fontStyle = 'bold'
            } else if (tier === 'yellow') {
              hookData.cell.styles.textColor = [245, 158, 11]
              hookData.cell.styles.fontStyle = 'bold'
            } else {
              hookData.cell.styles.textColor = [34, 197, 94]
            }
          }
        }
      },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── FEATURES BY TYPE TABLE ──
  const typeEntries = Object.entries(data.featuresByType).sort((a, b) => b[1].total - a[1].total)
  if (typeEntries.length > 0) {
    sectionHeader('FEATURES BY TYPE')

    const typeBody = typeEntries.map(([type, counts]) => {
      const pct = counts.total > 0 ? ((counts.inop / counts.total) * 100).toFixed(1) : '0.0'
      return [formatFeatureType(type), counts.total.toString(), counts.inop.toString(), `${pct}%`]
    })

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Feature Type', 'Total', 'Inop', '% Inop']],
      body: typeBody,
      styles: { fontSize: 8, cellPadding: 2, textColor: [0, 0, 0] },
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        1: { halign: 'center' },
        2: { halign: 'center' },
        3: { halign: 'center' },
      },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── RECENT OUTAGE EVENTS TABLE ──
  const events = data.recentOutageEvents.slice(0, 20)
  if (events.length > 0) {
    sectionHeader('RECENT OUTAGE EVENTS')

    const eventBody = events.map((e) => [
      formatZuluDate(e.created_at),
      e.feature_label || '—',
      e.event_type === 'reported' ? 'Reported' : 'Resolved',
      e.reporter_name || '—',
    ])

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Date', 'Feature', 'Event', 'User']],
      body: eventBody,
      styles: { fontSize: 8, cellPadding: 2, textColor: [0, 0, 0] },
      headStyles: {
        fillColor: [30, 41, 59],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8,
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      didParseCell: (hookData) => {
        if (hookData.section !== 'body') return
        if (hookData.column.index === 2) {
          const evt = events[hookData.row.index]
          if (evt?.event_type === 'reported') {
            hookData.cell.styles.textColor = [239, 68, 68]
          } else {
            hookData.cell.styles.textColor = [34, 197, 94]
          }
        }
      },
    })
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    y = (doc as any).lastAutoTable.finalY + 6
  }

  // ── PAGE NUMBERS ──
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 6, { align: 'center' })
  }

  const dateStr = now.toISOString().split('T')[0]
  const filename = `${opts.baseIcao ?? 'AIRFIELD'}_Lighting_Report_${dateStr}.pdf`
  return { doc, filename }
}
