import jsPDF from 'jspdf'
import type { OpenDiscrepanciesData } from './open-discrepancies-data'
import { formatDiscrepancyType } from './open-discrepancies-data'
import { formatZuluDateTime, formatZuluDateShort } from '@/lib/utils'
import {
  PDF_STATUS_LABELS,
  BASIC_COLUMNS,
  ALL_OPTIONAL_COLUMNS,
  buildDiscrepancyTable,
  type DiscrepancyRowData,
} from '@/lib/pdf-config'

interface Options {
  generatedBy: string
  baseName?: string
  baseIcao?: string
  selectedColumns?: string[]
}

export function generateOpenDiscrepanciesPdf(data: OpenDiscrepanciesData, opts: Options) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'letter' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 12
  const contentWidth = pageWidth - margin * 2
  let y = margin
  let pageNum = 1

  // Default to all columns for backward compatibility
  const selectedColumns = opts.selectedColumns || [...BASIC_COLUMNS, ...ALL_OPTIONAL_COLUMNS]

  function addPageNumber() {
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Page ${pageNum}`, pageWidth / 2, pageHeight - 6, { align: 'center' })
  }

  function checkPageBreak(needed: number) {
    if (y + needed > pageHeight - 14) {
      addPageNumber()
      doc.addPage()
      pageNum++
      y = margin
    }
  }

  function sectionHeader(title: string) {
    checkPageBreak(14)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(0)
    doc.text(title, margin, y)
    y += 1
    doc.setDrawColor(0)
    doc.setLineWidth(0.4)
    doc.line(margin, y, margin + contentWidth, y)
    y += 5
    doc.setFont('helvetica', 'normal')
  }

  // ── HEADER ──
  doc.setFontSize(8)
  doc.setTextColor(100)
  doc.text('GLIDEPATH', margin, y)
  y += 5

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.setFont('helvetica', 'bold')
  doc.text('OPEN DISCREPANCIES REPORT', margin, y)
  y += 6

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(opts.baseName && opts.baseIcao ? `${opts.baseName} (${opts.baseIcao})` : 'Airfield Operations', margin, y)
  y += 5

  doc.setFontSize(9)
  doc.setTextColor(60)
  const now = new Date()
  doc.text(`As of: ${formatZuluDateTime(now)}`, margin, y)
  y += 4
  doc.text(`Generated by: ${opts.generatedBy}`, margin, y)
  y += 4
  doc.text(`Total Open: ${data.summary.total}`, margin, y)
  if (data.summary.agingOver30 > 0) {
    doc.text(`   |   > 30 Days: ${data.summary.agingOver30}`, margin + 40, y)
  }
  y += 7

  // ── SUMMARY STATISTICS ──
  sectionHeader('SUMMARY')

  // By Area
  const areaEntries = Object.entries(data.summary.byArea).sort((a, b) => b[1] - a[1])
  if (areaEntries.length > 0) {
    doc.setFontSize(9)
    doc.setTextColor(0)
    const areaText = 'By Area: ' + areaEntries.map(([a, c]) => `${a} (${c})`).join(', ')
    const areaLines = doc.splitTextToSize(areaText, contentWidth)
    doc.text(areaLines, margin, y)
    y += areaLines.length * 4
  }

  // By Type
  const typeEntries = Object.entries(data.summary.byType).sort((a, b) => b[1] - a[1])
  if (typeEntries.length > 0) {
    doc.setFontSize(9)
    const typeText = 'By Type: ' + typeEntries.map(([t, c]) => `${formatDiscrepancyType(t)} (${c})`).join(', ')
    const typeLines = doc.splitTextToSize(typeText, contentWidth)
    doc.text(typeLines, margin, y)
    y += typeLines.length * 4
  }

  // By Shop
  const shopEntries = Object.entries(data.summary.byShop).sort((a, b) => b[1] - a[1])
  if (shopEntries.length > 0) {
    doc.setFontSize(9)
    const shopText = 'By Shop: ' + shopEntries.map(([s, c]) => `${s} (${c})`).join(', ')
    const shopLines = doc.splitTextToSize(shopText, contentWidth)
    doc.text(shopLines, margin, y)
    y += shopLines.length * 4
  }
  y += 3

  // ── DISCREPANCY ENTRIES ──
  const sorted = [...data.discrepancies].sort((a, b) => b.days_open - a.days_open)

  sectionHeader('ALL OPEN DISCREPANCIES')

  // Build comment history strings per discrepancy (last 3 notes, newest first)
  const commentsById: Record<string, string> = {}
  for (const disc of sorted) {
    const notes = data.notesHistory[disc.id] || []
    if (notes.length > 0) {
      commentsById[disc.id] = notes.map((n) => {
        const date = formatZuluDateShort(n.created_at)
        const name = n.user_rank ? `${n.user_rank} ${n.user_name}` : n.user_name
        const text = n.notes || '(status change)'
        return `${date} - ${name}: ${text}`
      }).join('\n')
    } else {
      commentsById[disc.id] = ''
    }
  }

  // Map to DiscrepancyRowData
  const tableRows: DiscrepancyRowData[] = sorted.map((d) => {
    const reporter = d.reporter_rank ? `${d.reporter_rank} ${d.reporter_name}` : d.reporter_name
    const lastUpdate = d.last_update_at ? formatZuluDateShort(d.last_update_at) : ''
    const photos = data.photos[d.id] || []

    return {
      id: d.id,
      work_order: d.work_order_number || '',
      title: d.title,
      status_label: PDF_STATUS_LABELS[d.current_status] || d.current_status,
      location: d.location_text,
      type_label: formatDiscrepancyType(d.type),
      shop: d.assigned_shop || 'Unassigned',
      days_open: d.days_open,
      reported_by: reporter,
      last_update: lastUpdate,
      comments: commentsById[d.id] || '',
      photos,
    }
  })

  const finalY = buildDiscrepancyTable({
    doc,
    startY: y,
    margin,
    selectedColumns,
    rows: tableRows,
    pageWidth,
  })
  y = finalY + 6

  // Footer
  addPageNumber()

  const dateStr = now.toISOString().split('T')[0]
  const filename = `${opts.baseIcao ?? 'AIRFIELD'}_Open_Discrepancies_${dateStr}.pdf`
  return { doc, filename }
}
