import type jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import {
  createPdf, drawBaseHeader, drawReportTitle, drawStatBox, drawFooter,
} from '@/lib/pdf-utils'
import { sanitizePdfText } from '@/lib/pdf-config'
import { formatZuluDate } from '@/lib/utils'
import type { DomainDef, UserActivityData, UserActivityRow } from './user-activity-data'

// ── NAMO/NAMT Report Tool — PDF generator ───────────────────
// Spec: docs/superpowers/specs/2026-07-16-namo-namt-report-tool-design.md §Exports & PDF
// pdf-utils-based generator: shared header/title/stat-box/footer chrome, one
// autoTable (Users × selected domains + Total) with a totals foot row.

export interface UserActivityPdfOptions {
  baseName?: string | null
  baseIcao?: string | null
  startDate: string
  endDate: string
  generatedBy: string
  domains: DomainDef[]
}

/** >7 domain columns: shrink to 8pt and truncate long labels/names (full names live in Excel). */
const MANY_COLUMNS_THRESHOLD = 7

function truncateLabel(label: string, max: number): string {
  if (label.length <= max) return label
  return `${label.slice(0, Math.max(1, max - 1))}…`
}

/**
 * Row label for the User column — unlinked (free-text) rows get an explicit
 * "(unlinked)" suffix. Truncate the NAME first, then append the suffix, so a
 * long unlinked name never loses its honesty marker to the many-columns
 * 26-char cut (appending before truncating dropped the suffix off the end).
 */
export function rowLabel(row: UserActivityRow, manyColumns: boolean): string {
  if (row.kind === 'unlinked') {
    const name = manyColumns ? truncateLabel(row.display, 26) : row.display
    return sanitizePdfText(`${name} (unlinked)`)
  }
  // Linked profile names are bounded ("Rank First Last (OI)") — let them wrap
  // in the User column rather than truncating (matches the other rows).
  return sanitizePdfText(row.display)
}

export function generateUserActivityPdf(
  data: UserActivityData,
  opts: UserActivityPdfOptions,
): { doc: jsPDF; filename: string } {
  const ctx = createPdf({ orientation: 'landscape' })
  const { doc, margin } = ctx
  let y = margin

  y = drawBaseHeader(ctx, y, { baseName: opts.baseName, baseIcao: opts.baseIcao })
  y = drawReportTitle(ctx, y, {
    title: 'NAMO/NAMT REPORT TOOL',
    subtitle: `${opts.startDate} → ${opts.endDate} · ${opts.domains.length} domain${opts.domains.length === 1 ? '' : 's'} selected`,
  })

  // "Linked Users" counts only rows resolved to a real profile (kind ===
  // 'profile') — data.rows.length also folds in unlinked/unattributed and
  // zero-injected rows, overstating the headcount.
  const linkedUsers = data.rows.filter((r) => r.kind === 'profile').length

  y = drawStatBox(ctx, y, [
    { label: 'Range', value: `${opts.startDate} – ${opts.endDate}` },
    { label: 'Domains', value: String(opts.domains.length) },
    { label: 'Linked Users', value: String(linkedUsers) },
    { label: 'Generated By', value: opts.generatedBy || '—' },
  ])

  const manyColumns = opts.domains.length > MANY_COLUMNS_THRESHOLD
  const bodyFontSize = manyColumns ? 8 : 9
  // Header labels wrap (never truncate) — shrink the header font when there are
  // many columns so full names like "Wildlife Sightings" fit on two lines.
  const headFontSize = manyColumns ? 7 : 9

  const head = [[
    'User',
    ...opts.domains.map((d) => sanitizePdfText(d.label)),
    'Total',
  ]]

  const body = data.rows.map((row) => [
    rowLabel(row, manyColumns),
    ...opts.domains.map((d) => String(row.counts[d.key] ?? 0)),
    String(row.total),
  ])

  const grandTotal = opts.domains.reduce((sum, d) => sum + (data.totals[d.key] ?? 0), 0)
  const foot = [[
    'Totals',
    ...opts.domains.map((d) => String(data.totals[d.key] ?? 0)),
    String(grandTotal),
  ]]

  autoTable(doc, {
    startY: y,
    head,
    body,
    foot,
    theme: 'grid',
    margin: { left: margin, right: margin },
    styles: { fontSize: bodyFontSize, cellPadding: 1.5, overflow: 'linebreak' },
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold', fontSize: headFontSize, valign: 'middle' },
    footStyles: { fillColor: [226, 232, 240], textColor: [15, 23, 42], fontStyle: 'bold', fontSize: bodyFontSize },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    columnStyles: { 0: { halign: 'left', cellWidth: manyColumns ? 30 : 42 } },
    didParseCell: (d) => {
      if (d.column.index > 0) d.cell.styles.halign = 'right'
    },
  })

  let ny = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y) + 8

  if (data.rows.length === 0) {
    doc.setFontSize(9)
    doc.setTextColor(90)
    doc.text('No attributed activity in this range.', margin, ny)
    ny += 8
  }

  if (data.zeroActivityUnavailable) {
    doc.setFontSize(8)
    doc.setTextColor(150, 90, 0)
    const wrapped = doc.splitTextToSize(
      sanitizePdfText('Personnel with zero activity could not be loaded for this base -- the matrix above reflects recorded activity only.'),
      ctx.contentWidth,
    )
    if (ny > ctx.pageHeight - 20) { doc.addPage(); ny = margin }
    doc.text(wrapped, margin, ny)
    ny += wrapped.length * 4 + 4
  }

  if (data.coverageNotes.length > 0) {
    if (ny > ctx.pageHeight - 30) { doc.addPage(); ny = margin }
    doc.setFontSize(10)
    doc.setTextColor(20)
    doc.text('COVERAGE NOTES', margin, ny)
    ny += 5
    doc.setFontSize(8)
    doc.setTextColor(90)
    for (const note of data.coverageNotes) {
      const def = opts.domains.find((d) => d.key === note.domain)
      const text = sanitizePdfText(
        `${def?.label ?? note.domain}: per-user attribution begins ${formatZuluDate(note.coverageStart)}; `
        + `${note.affected} record${note.affected === 1 ? '' : 's'} in this range lack${note.affected === 1 ? 's' : ''} per-user attribution.`,
      )
      const wrapped = doc.splitTextToSize(text, ctx.contentWidth)
      if (ny > ctx.pageHeight - 16) { doc.addPage(); ny = margin }
      doc.text(wrapped, margin, ny)
      ny += wrapped.length * 4 + 2
    }
  }

  // Standard generated-by/Zulu footer on every page (final pass — avoids
  // double-drawing when addPage() above created pages after the table render).
  const totalPages = doc.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    drawFooter(ctx)
  }

  const slug = (opts.baseIcao || opts.baseName || 'base').replace(/[^A-Za-z0-9]+/g, '-')
  const filename = `namo-namt-report_${slug}_${opts.startDate}_${opts.endDate}.pdf`
  return { doc, filename }
}
